#keyInfo=279ea13756393201
#authenticationInfo=a26d0de07667f969a97bc02b8a2464162b7754130ce5165008ee3f0f80318ad8
##########common parameters###########
#alias
PUBLICALIAS=omcPublicKey
#STOREPWD
STOREPWD=bcb9omc6
#SUBJECT
SUBJECT=
#licPath
licPath=omc.lic
#pubPath
pubPath=/omcPublicKey.store

