#!/bin/sh
# Enable the base-station HTTPS file entry only when a complete certificate
# pair is present. Plain HTTP 8080 must keep working on sites that have not
# enabled HTTPS yet.
set -eu

CERT="${OMC_NGINX_HTTPS_CERT:-/etc/nginx/cert/cert.pem}"
KEY="${OMC_NGINX_HTTPS_KEY:-/etc/nginx/cert/key.pem}"
OUT="${OMC_NGINX_HTTPS_CONF:-/etc/nginx/conf.d/https-file-entry.conf}"

rm -f "$OUT"

if [ ! -e "$CERT" ] && [ ! -e "$KEY" ]; then
  echo "INFO: nginx HTTPS file entry is disabled: $CERT and $KEY are not present; HTTP 8080 remains available"
  exit 0
fi

[ -f "$CERT" ] || { echo "ERROR: nginx HTTPS file entry certificate is missing: $CERT" >&2; exit 1; }
[ -f "$KEY" ] || { echo "ERROR: nginx HTTPS file entry private key is missing: $KEY" >&2; exit 1; }
[ -r "$CERT" ] || { echo "ERROR: nginx HTTPS file entry certificate is not readable: $CERT" >&2; exit 1; }
[ -r "$KEY" ] || { echo "ERROR: nginx HTTPS file entry private key is not readable: $KEY" >&2; exit 1; }

if command -v openssl >/dev/null 2>&1; then
  cert_fp="$(openssl x509 -in "$CERT" -pubkey -noout 2>/dev/null | openssl pkey -pubin -outform DER 2>/dev/null | sha256sum | awk '{print $1}')" ||
    { echo "ERROR: nginx HTTPS file entry certificate cannot be parsed: $CERT" >&2; exit 1; }
  key_fp="$(openssl pkey -in "$KEY" -pubout 2>/dev/null | openssl pkey -pubin -outform DER 2>/dev/null | sha256sum | awk '{print $1}')" ||
    { echo "ERROR: nginx HTTPS file entry private key cannot be parsed: $KEY" >&2; exit 1; }
  [ -n "$cert_fp" ] && [ -n "$key_fp" ] && [ "$cert_fp" = "$key_fp" ] ||
    { echo "ERROR: nginx HTTPS file entry certificate and private key do not match: $CERT / $KEY" >&2; exit 1; }
fi

cat >"$OUT" <<EOF
# Generated by 10-enable-https-file-entry.sh when /etc/nginx/cert is present.
server {
    listen 8443 ssl;

    ssl_certificate     $CERT;
    ssl_certificate_key $KEY;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache   shared:ACSFileSSL:10m;
    ssl_session_timeout 10m;

    access_log off; # ACS 文件入口高频请求由应用指标观测，避免与数据盘竞争 IO
    error_log  /var/log/nginx/app_error.log warn;

    location / {
        # 无 URI 部分的 upstream proxy_pass 原样透传 \$request_uri。
        proxy_pass http://acs_backend;

        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_socket_keepalive on;

        proxy_connect_timeout 10s;
        proxy_read_timeout    300s;
        proxy_send_timeout    300s;

        client_max_body_size 500m;
        client_body_buffer_size 256k;

        proxy_request_buffering off;
        proxy_buffering off;
    }
}
EOF

echo "INFO: nginx HTTPS file entry enabled on :8443 with $CERT / $KEY"
