apiVersion: v1
kind: Secret
metadata:
  name: omcgo-secrets
  namespace: omcgo
type: Opaque
stringData:
  DB_DSN: "postgres://omcgo:CHANGE_ME@postgres:5432/omcgo?sslmode=require"
  TSDB_DSN: "postgres://omcgo:CHANGE_ME@timescale:5432/omcgo?sslmode=require"
  REDIS_PASSWORD: "CHANGE_ME"
  MINIO_ACCESS_KEY: "CHANGE_ME"
  MINIO_SECRET_KEY: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_MINIMUM_32_CHARACTERS_LONG!!"
  NATS_URL: "nats://nats:4222"
