// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/admin (interfaces: ApiEndpointRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_api_endpoint_repository_test.go -package=admin . ApiEndpointRepository
//

// Package admin is a generated GoMock package.
package admin

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/omcgo/omcgo/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockApiEndpointRepository is a mock of ApiEndpointRepository interface.
type MockApiEndpointRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApiEndpointRepositoryMockRecorder
	isgomock struct{}
}

// MockApiEndpointRepositoryMockRecorder is the mock recorder for MockApiEndpointRepository.
type MockApiEndpointRepositoryMockRecorder struct {
	mock *MockApiEndpointRepository
}

// NewMockApiEndpointRepository creates a new mock instance.
func NewMockApiEndpointRepository(ctrl *gomock.Controller) *MockApiEndpointRepository {
	mock := &MockApiEndpointRepository{ctrl: ctrl}
	mock.recorder = &MockApiEndpointRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiEndpointRepository) EXPECT() *MockApiEndpointRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApiEndpointRepository) Create(ctx context.Context, ep *ApiEndpointDB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApiEndpointRepositoryMockRecorder) Create(ctx, ep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApiEndpointRepository)(nil).Create), ctx, ep)
}

// Delete mocks base method.
func (m *MockApiEndpointRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApiEndpointRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApiEndpointRepository)(nil).Delete), ctx, id)
}

// DeleteByIDs mocks base method.
func (m *MockApiEndpointRepository) DeleteByIDs(ctx context.Context, ids []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDs", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDs indicates an expected call of DeleteByIDs.
func (mr *MockApiEndpointRepositoryMockRecorder) DeleteByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDs", reflect.TypeOf((*MockApiEndpointRepository)(nil).DeleteByIDs), ctx, ids)
}

// GetByID mocks base method.
func (m *MockApiEndpointRepository) GetByID(ctx context.Context, id uuid.UUID) (*ApiEndpointDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*ApiEndpointDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockApiEndpointRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockApiEndpointRepository)(nil).GetByID), ctx, id)
}

// GetGroups mocks base method.
func (m *MockApiEndpointRepository) GetGroups(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroups", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroups indicates an expected call of GetGroups.
func (mr *MockApiEndpointRepositoryMockRecorder) GetGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroups", reflect.TypeOf((*MockApiEndpointRepository)(nil).GetGroups), ctx)
}

// List mocks base method.
func (m *MockApiEndpointRepository) List(ctx context.Context, filter ApiEndpointFilter) (*model.ListResponse[ApiEndpointDB], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*model.ListResponse[ApiEndpointDB])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockApiEndpointRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApiEndpointRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockApiEndpointRepository) Update(ctx context.Context, id uuid.UUID, req UpdateApiEndpointRequest) (*ApiEndpointDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*ApiEndpointDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockApiEndpointRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApiEndpointRepository)(nil).Update), ctx, id, req)
}

// Upsert mocks base method.
func (m *MockApiEndpointRepository) Upsert(ctx context.Context, path, method, name, description, apiGroup string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, path, method, name, description, apiGroup)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockApiEndpointRepositoryMockRecorder) Upsert(ctx, path, method, name, description, apiGroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockApiEndpointRepository)(nil).Upsert), ctx, path, method, name, description, apiGroup)
}
