// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/admin (interfaces: RoleRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_role_repository_test.go -package=admin . RoleRepository
//

// Package admin is a generated GoMock package.
package admin

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/omcgo/omcgo/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// AddPermissions mocks base method.
func (m *MockRoleRepository) AddPermissions(ctx context.Context, roleID uuid.UUID, perms []Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPermissions", ctx, roleID, perms)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPermissions indicates an expected call of AddPermissions.
func (mr *MockRoleRepositoryMockRecorder) AddPermissions(ctx, roleID, perms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPermissions", reflect.TypeOf((*MockRoleRepository)(nil).AddPermissions), ctx, roleID, perms)
}

// AssignRole mocks base method.
func (m *MockRoleRepository) AssignRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRoleRepositoryMockRecorder) AssignRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRoleRepository)(nil).AssignRole), ctx, userID, roleID)
}

// CheckPermission mocks base method.
func (m *MockRoleRepository) CheckPermission(ctx context.Context, userID uuid.UUID, resource, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, userID, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockRoleRepositoryMockRecorder) CheckPermission(ctx, userID, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockRoleRepository)(nil).CheckPermission), ctx, userID, resource, action)
}

// Create mocks base method.
func (m *MockRoleRepository) Create(ctx context.Context, role *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryMockRecorder) Create(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepository)(nil).Create), ctx, role)
}

// Delete mocks base method.
func (m *MockRoleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRoleRepository) GetByID(ctx context.Context, id uuid.UUID) (*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockRoleRepository) GetByName(ctx context.Context, name string) (*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockRoleRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockRoleRepository)(nil).GetByName), ctx, name)
}

// GetDefaultRoleID mocks base method.
func (m *MockRoleRepository) GetDefaultRoleID(ctx context.Context, userID uuid.UUID) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultRoleID", ctx, userID)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultRoleID indicates an expected call of GetDefaultRoleID.
func (mr *MockRoleRepositoryMockRecorder) GetDefaultRoleID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultRoleID", reflect.TypeOf((*MockRoleRepository)(nil).GetDefaultRoleID), ctx, userID)
}

// GetPermissions mocks base method.
func (m *MockRoleRepository) GetPermissions(ctx context.Context, roleID uuid.UUID) ([]Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", ctx, roleID)
	ret0, _ := ret[0].([]Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockRoleRepositoryMockRecorder) GetPermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockRoleRepository)(nil).GetPermissions), ctx, roleID)
}

// GetUserRoles mocks base method.
func (m *MockRoleRepository) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userID)
	ret0, _ := ret[0].([]Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockRoleRepositoryMockRecorder) GetUserRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockRoleRepository)(nil).GetUserRoles), ctx, userID)
}

// GetUserRolesBatch mocks base method.
func (m *MockRoleRepository) GetUserRolesBatch(ctx context.Context, userIds []uuid.UUID) (map[uuid.UUID][]Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRolesBatch", ctx, userIds)
	ret0, _ := ret[0].(map[uuid.UUID][]Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRolesBatch indicates an expected call of GetUserRolesBatch.
func (mr *MockRoleRepositoryMockRecorder) GetUserRolesBatch(ctx, userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRolesBatch", reflect.TypeOf((*MockRoleRepository)(nil).GetUserRolesBatch), ctx, userIds)
}

// List mocks base method.
func (m *MockRoleRepository) List(ctx context.Context) ([]Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleRepository)(nil).List), ctx)
}

// ListAllPermissions mocks base method.
func (m *MockRoleRepository) ListAllPermissions(ctx context.Context) ([]Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPermissions", ctx)
	ret0, _ := ret[0].([]Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPermissions indicates an expected call of ListAllPermissions.
func (mr *MockRoleRepositoryMockRecorder) ListAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPermissions", reflect.TypeOf((*MockRoleRepository)(nil).ListAllPermissions), ctx)
}

// ListWithPagination mocks base method.
func (m *MockRoleRepository) ListWithPagination(ctx context.Context, filter RoleFilter) (*model.ListResponse[Role], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithPagination", ctx, filter)
	ret0, _ := ret[0].(*model.ListResponse[Role])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithPagination indicates an expected call of ListWithPagination.
func (mr *MockRoleRepositoryMockRecorder) ListWithPagination(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithPagination", reflect.TypeOf((*MockRoleRepository)(nil).ListWithPagination), ctx, filter)
}

// ListRoleUsers mocks base method.
func (m *MockRoleRepository) ListRoleUsers(ctx context.Context, roleID uuid.UUID, limit, offset int) ([]RoleUserItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleUsers", ctx, roleID, limit, offset)
	ret0, _ := ret[0].([]RoleUserItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRoleUsers indicates an expected call of ListRoleUsers.
func (mr *MockRoleRepositoryMockRecorder) ListRoleUsers(ctx, roleID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleUsers", reflect.TypeOf((*MockRoleRepository)(nil).ListRoleUsers), ctx, roleID, limit, offset)
}

// RemoveAllPermissions mocks base method.
func (m *MockRoleRepository) RemoveAllPermissions(ctx context.Context, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllPermissions", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllPermissions indicates an expected call of RemoveAllPermissions.
func (mr *MockRoleRepositoryMockRecorder) RemoveAllPermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllPermissions", reflect.TypeOf((*MockRoleRepository)(nil).RemoveAllPermissions), ctx, roleID)
}

// RemoveRole mocks base method.
func (m *MockRoleRepository) RemoveRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockRoleRepositoryMockRecorder) RemoveRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockRoleRepository)(nil).RemoveRole), ctx, userID, roleID)
}

// SetDefaultRole mocks base method.
func (m *MockRoleRepository) SetDefaultRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultRole indicates an expected call of SetDefaultRole.
func (mr *MockRoleRepositoryMockRecorder) SetDefaultRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultRole", reflect.TypeOf((*MockRoleRepository)(nil).SetDefaultRole), ctx, userID, roleID)
}

// Update mocks base method.
func (m *MockRoleRepository) Update(ctx context.Context, role *Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepositoryMockRecorder) Update(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepository)(nil).Update), ctx, role)
}
