// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package adminsqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type DashboardWidget struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Layout    []byte    `json:"layout"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Permission struct {
	ID       uuid.UUID `json:"id"`
	RoleID   uuid.UUID `json:"role_id"`
	Resource string    `json:"resource"`
	Action   string    `json:"action"`
}

type Role struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type RoleInheritance struct {
	ParentRoleID uuid.UUID `json:"parent_role_id"`
	ChildRoleID  uuid.UUID `json:"child_role_id"`
	Domain       string    `json:"domain"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Username            string             `json:"username"`
	PasswordHash        string             `json:"password_hash"`
	DisplayName         pgtype.Text        `json:"display_name"`
	Email               pgtype.Text        `json:"email"`
	Carrier             pgtype.Text        `json:"carrier"`
	Status              string             `json:"status"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	LastFailedLoginAt   pgtype.Timestamptz `json:"last_failed_login_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	Phone               pgtype.Text        `json:"phone"`
	Source              string             `json:"source"`
	Description         pgtype.Text        `json:"description"`
	ExpireAt            pgtype.Timestamptz `json:"expire_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
}

type UserColumnConfig struct {
	UserID    uuid.UUID `json:"user_id"`
	PageKey   string    `json:"page_key"`
	Columns   []byte    `json:"columns"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	IsDefault bool      `json:"is_default"`
	CreatedAt time.Time `json:"created_at"`
}
