// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package adminsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE (carrier = $1 OR $1 IS NULL)
  AND (status = $2 OR $2 IS NULL)
  AND (username ILIKE '%' || $3 || '%' OR $3 = '')
`

type CountUsersParams struct {
	Carrier pgtype.Text `json:"carrier"`
	Status  string      `json:"status"`
	Column3 pgtype.Text `json:"column_3"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Carrier, arg.Status, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, display_name, email, phone, carrier, status, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, username, password_hash, display_name, email, carrier, status, last_login_at, failed_login_attempts, locked_until, last_failed_login_at, created_at, updated_at, phone, source, description, expire_at, created_by, updated_by
`

type CreateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Carrier      pgtype.Text `json:"carrier"`
	Status       string      `json:"status"`
	Source       string      `json:"source"`
}

// source 由调用方决定（admin/builtIn/LDAP）；DB CHECK 约束限定取值。
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.Carrier,
		arg.Status,
		arg.Source,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Carrier,
		&i.Status,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
		&i.Source,
		&i.Description,
		&i.ExpireAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, email, carrier, status, last_login_at, failed_login_attempts, locked_until, last_failed_login_at, created_at, updated_at, phone, source, description, expire_at, created_by, updated_by FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Carrier,
		&i.Status,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
		&i.Source,
		&i.Description,
		&i.ExpireAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, email, carrier, status, last_login_at, failed_login_attempts, locked_until, last_failed_login_at, created_at, updated_at, phone, source, description, expire_at, created_by, updated_by FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Carrier,
		&i.Status,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
		&i.Source,
		&i.Description,
		&i.ExpireAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, display_name, email, carrier, status, last_login_at, failed_login_attempts, locked_until, last_failed_login_at, created_at, updated_at, phone, source, description, expire_at, created_by, updated_by FROM users
WHERE (carrier = $1 OR $1 IS NULL)
  AND (status = $2 OR $2 IS NULL)
  AND (username ILIKE '%' || $3 || '%' OR $3 = '')
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListUsersParams struct {
	Carrier pgtype.Text `json:"carrier"`
	Status  string      `json:"status"`
	Column3 pgtype.Text `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Carrier,
		arg.Status,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Email,
			&i.Carrier,
			&i.Status,
			&i.LastLoginAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastFailedLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Phone,
			&i.Source,
			&i.Description,
			&i.ExpireAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW(), failed_login_attempts = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    email = COALESCE($3, email),
    phone = COALESCE($4, phone),
    carrier = COALESCE($5, carrier),
    status = COALESCE($6, status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, password_hash, display_name, email, carrier, status, last_login_at, failed_login_attempts, locked_until, last_failed_login_at, created_at, updated_at, phone, source, description, expire_at, created_by, updated_by
`

type UpdateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	Carrier     pgtype.Text `json:"carrier"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.Carrier,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Carrier,
		&i.Status,
		&i.LastLoginAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastFailedLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
		&i.Source,
		&i.Description,
		&i.ExpireAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
