// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/device (interfaces: DeviceRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_device_repository_test.go -package=device . DeviceRepository
//

// Package device is a generated GoMock package.
package device

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	model "github.com/omcgo/omcgo/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceRepository is a mock of DeviceRepository interface.
type MockDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceRepositoryMockRecorder is the mock recorder for MockDeviceRepository.
type MockDeviceRepositoryMockRecorder struct {
	mock *MockDeviceRepository
}

// NewMockDeviceRepository creates a new mock instance.
func NewMockDeviceRepository(ctrl *gomock.Controller) *MockDeviceRepository {
	mock := &MockDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepository) EXPECT() *MockDeviceRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockDeviceRepository) BatchDelete(ctx context.Context, ids []uuid.UUID, deletedBy string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, ids, deletedBy)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockDeviceRepositoryMockRecorder) BatchDelete(ctx, ids, deletedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockDeviceRepository)(nil).BatchDelete), ctx, ids, deletedBy)
}

// CountByStatus mocks base method.
func (m *MockDeviceRepository) CountByStatus(ctx context.Context, carrier *model.CarrierCode) (map[model.DeviceStatus]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx, carrier)
	ret0, _ := ret[0].(map[model.DeviceStatus]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockDeviceRepositoryMockRecorder) CountByStatus(ctx, carrier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockDeviceRepository)(nil).CountByStatus), ctx, carrier)
}

// Create mocks base method.
func (m *MockDeviceRepository) Create(ctx context.Context, device *model.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceRepositoryMockRecorder) Create(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceRepository)(nil).Create), ctx, device)
}

// Delete mocks base method.
func (m *MockDeviceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceRepository)(nil).Delete), ctx, id)
}

// FindStaleDevices mocks base method.
func (m *MockDeviceRepository) FindStaleDevices(ctx context.Context, threshold time.Time, limit int) ([]*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStaleDevices", ctx, threshold, limit)
	ret0, _ := ret[0].([]*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStaleDevices indicates an expected call of FindStaleDevices.
func (mr *MockDeviceRepositoryMockRecorder) FindStaleDevices(ctx, threshold, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStaleDevices", reflect.TypeOf((*MockDeviceRepository)(nil).FindStaleDevices), ctx, threshold, limit)
}

// ListStaleForParamSync mocks base method.
func (m *MockDeviceRepository) ListStaleForParamSync(ctx context.Context, threshold time.Time, limit int) ([]*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStaleForParamSync", ctx, threshold, limit)
	ret0, _ := ret[0].([]*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStaleForParamSync indicates an expected call of ListStaleForParamSync.
func (mr *MockDeviceRepositoryMockRecorder) ListStaleForParamSync(ctx, threshold, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStaleForParamSync", reflect.TypeOf((*MockDeviceRepository)(nil).ListStaleForParamSync), ctx, threshold, limit)
}

// UpdateLastParamSyncAt mocks base method.
func (m *MockDeviceRepository) UpdateLastParamSyncAt(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastParamSyncAt", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastParamSyncAt indicates an expected call of UpdateLastParamSyncAt.
func (mr *MockDeviceRepositoryMockRecorder) UpdateLastParamSyncAt(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastParamSyncAt", reflect.TypeOf((*MockDeviceRepository)(nil).UpdateLastParamSyncAt), ctx, id, at)
}

// ListSerialsByIDs mocks base method.
func (m *MockDeviceRepository) ListSerialsByIDs(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSerialsByIDs", ctx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSerialsByIDs indicates an expected call of ListSerialsByIDs.
func (mr *MockDeviceRepositoryMockRecorder) ListSerialsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSerialsByIDs", reflect.TypeOf((*MockDeviceRepository)(nil).ListSerialsByIDs), ctx, ids)
}

// GetByID mocks base method.
func (m *MockDeviceRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceRepository)(nil).GetByID), ctx, id)
}

// GetBySerialNumber mocks base method.
func (m *MockDeviceRepository) GetBySerialNumber(ctx context.Context, sn string) (*model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySerialNumber", ctx, sn)
	ret0, _ := ret[0].(*model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySerialNumber indicates an expected call of GetBySerialNumber.
func (mr *MockDeviceRepositoryMockRecorder) GetBySerialNumber(ctx, sn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySerialNumber", reflect.TypeOf((*MockDeviceRepository)(nil).GetBySerialNumber), ctx, sn)
}

// GetGeoStats mocks base method.
func (m *MockDeviceRepository) GetGeoStats(ctx context.Context, groupIDs []string) (*GeoStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeoStats", ctx, groupIDs)
	ret0, _ := ret[0].(*GeoStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeoStats indicates an expected call of GetGeoStats.
func (mr *MockDeviceRepositoryMockRecorder) GetGeoStats(ctx, groupIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeoStats", reflect.TypeOf((*MockDeviceRepository)(nil).GetGeoStats), ctx, groupIDs)
}

// List mocks base method.
func (m *MockDeviceRepository) List(ctx context.Context, filter DeviceFilter) (*model.ListResponse[model.Device], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*model.ListResponse[model.Device])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDeviceRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceRepository)(nil).List), ctx, filter)
}

// ListActiveByLastInform mocks base method.
func (m *MockDeviceRepository) ListActiveByLastInform(ctx context.Context, cursorTime *time.Time, cursorID *uuid.UUID, limit int) ([]model.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByLastInform", ctx, cursorTime, cursorID, limit)
	ret0, _ := ret[0].([]model.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByLastInform indicates an expected call of ListActiveByLastInform.
func (mr *MockDeviceRepositoryMockRecorder) ListActiveByLastInform(ctx, cursorTime, cursorID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByLastInform", reflect.TypeOf((*MockDeviceRepository)(nil).ListActiveByLastInform), ctx, cursorTime, cursorID, limit)
}

// ListGeo mocks base method.
func (m *MockDeviceRepository) ListGeo(ctx context.Context, filter GeoDeviceFilter) ([]GeoDevice, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGeo", ctx, filter)
	ret0, _ := ret[0].([]GeoDevice)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGeo indicates an expected call of ListGeo.
func (mr *MockDeviceRepositoryMockRecorder) ListGeo(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGeo", reflect.TypeOf((*MockDeviceRepository)(nil).ListGeo), ctx, filter)
}

// ListRecycleBin mocks base method.
func (m *MockDeviceRepository) ListRecycleBin(ctx context.Context, filter RecycleBinFilter) (*model.ListResponse[model.Device], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecycleBin", ctx, filter)
	ret0, _ := ret[0].(*model.ListResponse[model.Device])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecycleBin indicates an expected call of ListRecycleBin.
func (mr *MockDeviceRepositoryMockRecorder) ListRecycleBin(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecycleBin", reflect.TypeOf((*MockDeviceRepository)(nil).ListRecycleBin), ctx, filter)
}

// PermanentDelete mocks base method.
func (m *MockDeviceRepository) PermanentDelete(ctx context.Context, ids []uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermanentDelete", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PermanentDelete indicates an expected call of PermanentDelete.
func (mr *MockDeviceRepositoryMockRecorder) PermanentDelete(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermanentDelete", reflect.TypeOf((*MockDeviceRepository)(nil).PermanentDelete), ctx, ids)
}

// RestoreDevices mocks base method.
func (m *MockDeviceRepository) RestoreDevices(ctx context.Context, ids []uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDevices", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDevices indicates an expected call of RestoreDevices.
func (mr *MockDeviceRepositoryMockRecorder) RestoreDevices(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDevices", reflect.TypeOf((*MockDeviceRepository)(nil).RestoreDevices), ctx, ids)
}

// SearchDevices mocks base method.
func (m *MockDeviceRepository) SearchDevices(ctx context.Context, keyword string, limit int) ([]GeoDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDevices", ctx, keyword, limit)
	ret0, _ := ret[0].([]GeoDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDevices indicates an expected call of SearchDevices.
func (mr *MockDeviceRepositoryMockRecorder) SearchDevices(ctx, keyword, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDevices", reflect.TypeOf((*MockDeviceRepository)(nil).SearchDevices), ctx, keyword, limit)
}

// Update mocks base method.
func (m *MockDeviceRepository) Update(ctx context.Context, device *model.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceRepositoryMockRecorder) Update(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceRepository)(nil).Update), ctx, device)
}

// UpdateLastInform mocks base method.
func (m *MockDeviceRepository) UpdateLastInform(ctx context.Context, sn string, at time.Time, events []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastInform", ctx, sn, at, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastInform indicates an expected call of UpdateLastInform.
func (mr *MockDeviceRepositoryMockRecorder) UpdateLastInform(ctx, sn, at, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastInform", reflect.TypeOf((*MockDeviceRepository)(nil).UpdateLastInform), ctx, sn, at, events)
}

// RecordBoot mocks base method.
func (m *MockDeviceRepository) RecordBoot(ctx context.Context, sn string, at time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBoot", ctx, sn, at)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordBoot indicates an expected call of RecordBoot.
func (mr *MockDeviceRepositoryMockRecorder) RecordBoot(ctx, sn, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBoot", reflect.TypeOf((*MockDeviceRepository)(nil).RecordBoot), ctx, sn, at)
}

// UpdateStatus mocks base method.
func (m *MockDeviceRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status model.DeviceStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDeviceRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDeviceRepository)(nil).UpdateStatus), ctx, id, status)
}

// T-0162 新接口方法 — 手写 gomock 桩（避免重新运行 go generate）

func (m *MockDeviceRepository) UpdateLifecycle(ctx context.Context, id uuid.UUID, lifecycle model.DeviceLifecycle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLifecycle", ctx, id, lifecycle)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDeviceRepositoryMockRecorder) UpdateLifecycle(ctx, id, lifecycle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLifecycle", reflect.TypeOf((*MockDeviceRepository)(nil).UpdateLifecycle), ctx, id, lifecycle)
}

func (m *MockDeviceRepository) UpdateOnlineStatus(ctx context.Context, id uuid.UUID, isOnline bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnlineStatus", ctx, id, isOnline)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDeviceRepositoryMockRecorder) UpdateOnlineStatus(ctx, id, isOnline any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnlineStatus", reflect.TypeOf((*MockDeviceRepository)(nil).UpdateOnlineStatus), ctx, id, isOnline)
}
