// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/device (interfaces: DeviceInfoRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_device_info_repository_test.go -package=device . DeviceInfoRepository
//

// Package device is a generated GoMock package.
package device

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/omcgo/omcgo/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceInfoRepository is a mock of DeviceInfoRepository interface.
type MockDeviceInfoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceInfoRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceInfoRepositoryMockRecorder is the mock recorder for MockDeviceInfoRepository.
type MockDeviceInfoRepositoryMockRecorder struct {
	mock *MockDeviceInfoRepository
}

// NewMockDeviceInfoRepository creates a new mock instance.
func NewMockDeviceInfoRepository(ctrl *gomock.Controller) *MockDeviceInfoRepository {
	mock := &MockDeviceInfoRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceInfoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceInfoRepository) EXPECT() *MockDeviceInfoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceInfoRepository) Create(ctx context.Context, info *DeviceInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceInfoRepositoryMockRecorder) Create(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceInfoRepository)(nil).Create), ctx, info)
}

// GetByDeviceID mocks base method.
func (m *MockDeviceInfoRepository) GetByDeviceID(ctx context.Context, deviceID uuid.UUID) (*DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDeviceID", ctx, deviceID)
	ret0, _ := ret[0].(*DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDeviceID indicates an expected call of GetByDeviceID.
func (mr *MockDeviceInfoRepositoryMockRecorder) GetByDeviceID(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDeviceID", reflect.TypeOf((*MockDeviceInfoRepository)(nil).GetByDeviceID), ctx, deviceID)
}

// GetByIDWithInfo mocks base method.
func (m *MockDeviceInfoRepository) GetByIDWithInfo(ctx context.Context, deviceID uuid.UUID) (*DeviceWithInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithInfo", ctx, deviceID)
	ret0, _ := ret[0].(*DeviceWithInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithInfo indicates an expected call of GetByIDWithInfo.
func (mr *MockDeviceInfoRepositoryMockRecorder) GetByIDWithInfo(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithInfo", reflect.TypeOf((*MockDeviceInfoRepository)(nil).GetByIDWithInfo), ctx, deviceID)
}

// ListDevicesWithInfo mocks base method.
func (m *MockDeviceInfoRepository) ListDevicesWithInfo(ctx context.Context, filter DeviceFilter) (*model.ListResponse[DeviceWithInfo], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevicesWithInfo", ctx, filter)
	ret0, _ := ret[0].(*model.ListResponse[DeviceWithInfo])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevicesWithInfo indicates an expected call of ListDevicesWithInfo.
func (mr *MockDeviceInfoRepositoryMockRecorder) ListDevicesWithInfo(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevicesWithInfo", reflect.TypeOf((*MockDeviceInfoRepository)(nil).ListDevicesWithInfo), ctx, filter)
}

// UpdateManualFields mocks base method.
func (m *MockDeviceInfoRepository) UpdateManualFields(ctx context.Context, deviceID uuid.UUID, req UpdateDeviceInfoRequest, updater string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateManualFields", ctx, deviceID, req, updater)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateManualFields indicates an expected call of UpdateManualFields.
func (mr *MockDeviceInfoRepositoryMockRecorder) UpdateManualFields(ctx, deviceID, req, updater any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateManualFields", reflect.TypeOf((*MockDeviceInfoRepository)(nil).UpdateManualFields), ctx, deviceID, req, updater)
}

// UpdateSyncFields mocks base method.
func (m *MockDeviceInfoRepository) UpdateSyncFields(ctx context.Context, deviceID uuid.UUID, fields map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncFields", ctx, deviceID, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncFields indicates an expected call of UpdateSyncFields.
func (mr *MockDeviceInfoRepositoryMockRecorder) UpdateSyncFields(ctx, deviceID, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncFields", reflect.TypeOf((*MockDeviceInfoRepository)(nil).UpdateSyncFields), ctx, deviceID, fields)
}
