// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/device (interfaces: DeviceParameterRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_device_param_repository_test.go -package=device . DeviceParameterRepository
//

// Package device is a generated GoMock package.
package device

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/omcgo/omcgo/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceParameterRepository is a mock of DeviceParameterRepository interface.
type MockDeviceParameterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceParameterRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceParameterRepositoryMockRecorder is the mock recorder for MockDeviceParameterRepository.
type MockDeviceParameterRepositoryMockRecorder struct {
	mock *MockDeviceParameterRepository
}

// NewMockDeviceParameterRepository creates a new mock instance.
func NewMockDeviceParameterRepository(ctrl *gomock.Controller) *MockDeviceParameterRepository {
	mock := &MockDeviceParameterRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceParameterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceParameterRepository) EXPECT() *MockDeviceParameterRepositoryMockRecorder {
	return m.recorder
}

// BatchUpsert mocks base method.
func (m *MockDeviceParameterRepository) BatchUpsert(ctx context.Context, deviceID uuid.UUID, params []model.DeviceParameter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpsert", ctx, deviceID, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpsert indicates an expected call of BatchUpsert.
func (mr *MockDeviceParameterRepositoryMockRecorder) BatchUpsert(ctx, deviceID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsert", reflect.TypeOf((*MockDeviceParameterRepository)(nil).BatchUpsert), ctx, deviceID, params)
}

// CountByPathPrefix mocks base method.
func (m *MockDeviceParameterRepository) CountByPathPrefix(ctx context.Context, deviceID uuid.UUID, prefix string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPathPrefix", ctx, deviceID, prefix)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPathPrefix indicates an expected call of CountByPathPrefix.
func (mr *MockDeviceParameterRepositoryMockRecorder) CountByPathPrefix(ctx, deviceID, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPathPrefix", reflect.TypeOf((*MockDeviceParameterRepository)(nil).CountByPathPrefix), ctx, deviceID, prefix)
}

// DeleteByDevice mocks base method.
func (m *MockDeviceParameterRepository) DeleteByDevice(ctx context.Context, deviceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByDevice", ctx, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByDevice indicates an expected call of DeleteByDevice.
func (mr *MockDeviceParameterRepositoryMockRecorder) DeleteByDevice(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByDevice", reflect.TypeOf((*MockDeviceParameterRepository)(nil).DeleteByDevice), ctx, deviceID)
}

// GetByDevice mocks base method.
func (m *MockDeviceParameterRepository) GetByDevice(ctx context.Context, deviceID uuid.UUID) ([]model.DeviceParameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDevice", ctx, deviceID)
	ret0, _ := ret[0].([]model.DeviceParameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDevice indicates an expected call of GetByDevice.
func (mr *MockDeviceParameterRepositoryMockRecorder) GetByDevice(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDevice", reflect.TypeOf((*MockDeviceParameterRepository)(nil).GetByDevice), ctx, deviceID)
}

// GetByFAPInstance mocks base method.
func (m *MockDeviceParameterRepository) GetByFAPInstance(ctx context.Context, deviceID uuid.UUID, instance int) ([]model.DeviceParameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFAPInstance", ctx, deviceID, instance)
	ret0, _ := ret[0].([]model.DeviceParameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFAPInstance indicates an expected call of GetByFAPInstance.
func (mr *MockDeviceParameterRepositoryMockRecorder) GetByFAPInstance(ctx, deviceID, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFAPInstance", reflect.TypeOf((*MockDeviceParameterRepository)(nil).GetByFAPInstance), ctx, deviceID, instance)
}

// GetByFAPInstanceAndGroup mocks base method.
func (m *MockDeviceParameterRepository) GetByFAPInstanceAndGroup(ctx context.Context, deviceID uuid.UUID, instance int, group string) ([]model.DeviceParameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFAPInstanceAndGroup", ctx, deviceID, instance, group)
	ret0, _ := ret[0].([]model.DeviceParameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFAPInstanceAndGroup indicates an expected call of GetByFAPInstanceAndGroup.
func (mr *MockDeviceParameterRepositoryMockRecorder) GetByFAPInstanceAndGroup(ctx, deviceID, instance, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFAPInstanceAndGroup", reflect.TypeOf((*MockDeviceParameterRepository)(nil).GetByFAPInstanceAndGroup), ctx, deviceID, instance, group)
}

// GetByGroup mocks base method.
func (m *MockDeviceParameterRepository) GetByGroup(ctx context.Context, deviceID uuid.UUID, group string) ([]model.DeviceParameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGroup", ctx, deviceID, group)
	ret0, _ := ret[0].([]model.DeviceParameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGroup indicates an expected call of GetByGroup.
func (mr *MockDeviceParameterRepositoryMockRecorder) GetByGroup(ctx, deviceID, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGroup", reflect.TypeOf((*MockDeviceParameterRepository)(nil).GetByGroup), ctx, deviceID, group)
}

// GetByPath mocks base method.
func (m *MockDeviceParameterRepository) GetByPath(ctx context.Context, deviceID uuid.UUID, path string) (*model.DeviceParameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", ctx, deviceID, path)
	ret0, _ := ret[0].(*model.DeviceParameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockDeviceParameterRepositoryMockRecorder) GetByPath(ctx, deviceID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockDeviceParameterRepository)(nil).GetByPath), ctx, deviceID, path)
}

// GetByPathPrefix mocks base method.
func (m *MockDeviceParameterRepository) GetByPathPrefix(ctx context.Context, deviceID uuid.UUID, prefix string) ([]model.DeviceParameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPathPrefix", ctx, deviceID, prefix)
	ret0, _ := ret[0].([]model.DeviceParameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPathPrefix indicates an expected call of GetByPathPrefix.
func (mr *MockDeviceParameterRepositoryMockRecorder) GetByPathPrefix(ctx, deviceID, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPathPrefix", reflect.TypeOf((*MockDeviceParameterRepository)(nil).GetByPathPrefix), ctx, deviceID, prefix)
}

// GetDirectChildLeaves mocks base method.
func (m *MockDeviceParameterRepository) GetDirectChildLeaves(ctx context.Context, deviceID uuid.UUID, prefix string, limit, offset int) ([]model.DeviceParameter, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirectChildLeaves", ctx, deviceID, prefix, limit, offset)
	ret0, _ := ret[0].([]model.DeviceParameter)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDirectChildLeaves indicates an expected call of GetDirectChildLeaves.
func (mr *MockDeviceParameterRepositoryMockRecorder) GetDirectChildLeaves(ctx, deviceID, prefix, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectChildLeaves", reflect.TypeOf((*MockDeviceParameterRepository)(nil).GetDirectChildLeaves), ctx, deviceID, prefix, limit, offset)
}

// SearchByKeyword mocks base method.
func (m *MockDeviceParameterRepository) SearchByKeyword(ctx context.Context, deviceID uuid.UUID, keyword string, limit int) ([]model.DeviceParameter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByKeyword", ctx, deviceID, keyword, limit)
	ret0, _ := ret[0].([]model.DeviceParameter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByKeyword indicates an expected call of SearchByKeyword.
func (mr *MockDeviceParameterRepositoryMockRecorder) SearchByKeyword(ctx, deviceID, keyword, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByKeyword", reflect.TypeOf((*MockDeviceParameterRepository)(nil).SearchByKeyword), ctx, deviceID, keyword, limit)
}
