DROP TABLE IF EXISTS sys_task_logs CASCADE;
DROP TABLE IF EXISTS sys_oper_logs CASCADE;
DROP TABLE IF EXISTS sys_login_logs CASCADE;
DROP TABLE IF EXISTS sys_configs CASCADE;
DROP TABLE IF EXISTS sys_dictionary_details CASCADE;
DROP TABLE IF EXISTS sys_dictionaries CASCADE;
DROP TABLE IF EXISTS role_menus CASCADE;
DROP TABLE IF EXISTS menus CASCADE;
