FROM node:20-alpine AS builder

WORKDIR /app
COPY omcmb/webcode/package.json omcmb/webcode/package-lock.json ./

# 配置 npm 镜像源并安装依赖
RUN npm config set registry https://registry.npmmirror.com
RUN npm install --legacy-peer-deps

COPY omcmb/webcode/ .

# 构建前端
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY deployments/docker/nginx.conf /etc/nginx/nginx.conf
COPY deployments/docker/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080 8081
