# DNS 覆盖配置
# 使用方法: docker compose -f docker-compose.yml -f docker-compose.dns.yml build

services:
  migrate:
    dns:
      - 223.5.5.5
      - 223.6.6.6
      - 114.114.114.114

  acs:
    dns:
      - 223.5.5.5
      - 223.6.6.6
      - 114.114.114.114

  app:
    dns:
      - 223.5.5.5
      - 223.6.6.6
      - 114.114.114.114

  worker:
    dns:
      - 223.5.5.5
      - 223.6.6.6
      - 114.114.114.114

  web:
    dns:
      - 223.5.5.5
      - 223.6.6.6
      - 114.114.114.114
