apiVersion: v1
kind: Service
metadata:
  name: omcgo-acs
  namespace: omcgo
  labels:
    app: omcgo-acs
spec:
  type: LoadBalancer
  selector:
    app: omcgo-acs
  ports:
    - name: http
      port: 7547
      targetPort: 7547
      protocol: TCP
    - name: https
      port: 7548
      targetPort: 7548
      protocol: TCP
