// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/topology (interfaces: DeviceLister)
//
// Generated by this command:
//
//	mockgen -destination=internal/topology/mock_device_lister_test.go -package=topology github.com/omcgo/omcgo/internal/topology DeviceLister
//

// Package topology is a generated GoMock package.
package topology

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceLister is a mock of DeviceLister interface.
type MockDeviceLister struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceListerMockRecorder
	isgomock struct{}
}

// MockDeviceListerMockRecorder is the mock recorder for MockDeviceLister.
type MockDeviceListerMockRecorder struct {
	mock *MockDeviceLister
}

// NewMockDeviceLister creates a new mock instance.
func NewMockDeviceLister(ctrl *gomock.Controller) *MockDeviceLister {
	mock := &MockDeviceLister{ctrl: ctrl}
	mock.recorder = &MockDeviceListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceLister) EXPECT() *MockDeviceListerMockRecorder {
	return m.recorder
}

// ListAllForRuleEval mocks base method.
func (m *MockDeviceLister) ListAllForRuleEval(ctx context.Context) ([]DeviceForMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllForRuleEval", ctx)
	ret0, _ := ret[0].([]DeviceForMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllForRuleEval indicates an expected call of ListAllForRuleEval.
func (mr *MockDeviceListerMockRecorder) ListAllForRuleEval(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllForRuleEval", reflect.TypeOf((*MockDeviceLister)(nil).ListAllForRuleEval), ctx)
}
