// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/topology (interfaces: DeviceRuleRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_device_rule_repository_test.go -package=topology github.com/omcgo/omcgo/internal/topology DeviceRuleRepository
//

// Package topology is a generated GoMock package.
package topology

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceRuleRepository is a mock of DeviceRuleRepository interface.
type MockDeviceRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceRuleRepositoryMockRecorder is the mock recorder for MockDeviceRuleRepository.
type MockDeviceRuleRepositoryMockRecorder struct {
	mock *MockDeviceRuleRepository
}

// NewMockDeviceRuleRepository creates a new mock instance.
func NewMockDeviceRuleRepository(ctrl *gomock.Controller) *MockDeviceRuleRepository {
	mock := &MockDeviceRuleRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRuleRepository) EXPECT() *MockDeviceRuleRepositoryMockRecorder {
	return m.recorder
}

// BatchUpdatePriority mocks base method.
func (m *MockDeviceRuleRepository) BatchUpdatePriority(ctx context.Context, items []RuleSortItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdatePriority", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdatePriority indicates an expected call of BatchUpdatePriority.
func (mr *MockDeviceRuleRepositoryMockRecorder) BatchUpdatePriority(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdatePriority", reflect.TypeOf((*MockDeviceRuleRepository)(nil).BatchUpdatePriority), ctx, items)
}

// Create mocks base method.
func (m *MockDeviceRuleRepository) Create(ctx context.Context, rule *DeviceRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceRuleRepositoryMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceRuleRepository)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockDeviceRuleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceRuleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceRuleRepository)(nil).Delete), ctx, id)
}

// ExistsByPriority mocks base method.
func (m *MockDeviceRuleRepository) ExistsByPriority(ctx context.Context, priority int, excludeID *uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByPriority", ctx, priority, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByPriority indicates an expected call of ExistsByPriority.
func (mr *MockDeviceRuleRepositoryMockRecorder) ExistsByPriority(ctx, priority, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByPriority", reflect.TypeOf((*MockDeviceRuleRepository)(nil).ExistsByPriority), ctx, priority, excludeID)
}

// GetAll mocks base method.
func (m *MockDeviceRuleRepository) GetAll(ctx context.Context) ([]DeviceRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]DeviceRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDeviceRuleRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDeviceRuleRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockDeviceRuleRepository) GetByID(ctx context.Context, id uuid.UUID) (*DeviceRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*DeviceRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceRuleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceRuleRepository)(nil).GetByID), ctx, id)
}

// GetEnabledByPriority mocks base method.
func (m *MockDeviceRuleRepository) GetEnabledByPriority(ctx context.Context) ([]DeviceRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledByPriority", ctx)
	ret0, _ := ret[0].([]DeviceRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledByPriority indicates an expected call of GetEnabledByPriority.
func (mr *MockDeviceRuleRepositoryMockRecorder) GetEnabledByPriority(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledByPriority", reflect.TypeOf((*MockDeviceRuleRepository)(nil).GetEnabledByPriority), ctx)
}

// GetNextPriority mocks base method.
func (m *MockDeviceRuleRepository) GetNextPriority(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextPriority", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextPriority indicates an expected call of GetNextPriority.
func (mr *MockDeviceRuleRepositoryMockRecorder) GetNextPriority(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextPriority", reflect.TypeOf((*MockDeviceRuleRepository)(nil).GetNextPriority), ctx)
}

// List mocks base method.
func (m *MockDeviceRuleRepository) List(ctx context.Context, req *RuleListRequest) ([]DeviceRule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]DeviceRule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDeviceRuleRepositoryMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeviceRuleRepository)(nil).List), ctx, req)
}

// Update mocks base method.
func (m *MockDeviceRuleRepository) Update(ctx context.Context, rule *DeviceRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceRuleRepositoryMockRecorder) Update(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceRuleRepository)(nil).Update), ctx, rule)
}
