// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/topology (interfaces: DeviceGroupRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/topology/mock_device_group_repository_test.go -package=topology github.com/omcgo/omcgo/internal/topology DeviceGroupRepository
//

// Package topology is a generated GoMock package.
package topology

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceGroupRepository is a mock of DeviceGroupRepository interface.
type MockDeviceGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockDeviceGroupRepositoryMockRecorder is the mock recorder for MockDeviceGroupRepository.
type MockDeviceGroupRepositoryMockRecorder struct {
	mock *MockDeviceGroupRepository
}

// NewMockDeviceGroupRepository creates a new mock instance.
func NewMockDeviceGroupRepository(ctrl *gomock.Controller) *MockDeviceGroupRepository {
	mock := &MockDeviceGroupRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceGroupRepository) EXPECT() *MockDeviceGroupRepositoryMockRecorder {
	return m.recorder
}

// AddDevice mocks base method.
func (m *MockDeviceGroupRepository) AddDevice(ctx context.Context, groupID, deviceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDevice", ctx, groupID, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevice indicates an expected call of AddDevice.
func (mr *MockDeviceGroupRepositoryMockRecorder) AddDevice(ctx, groupID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevice", reflect.TypeOf((*MockDeviceGroupRepository)(nil).AddDevice), ctx, groupID, deviceID)
}

// AddDeviceAutoMatched mocks base method.
func (m *MockDeviceGroupRepository) AddDeviceAutoMatched(ctx context.Context, groupID, deviceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeviceAutoMatched", ctx, groupID, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDeviceAutoMatched indicates an expected call of AddDeviceAutoMatched.
func (mr *MockDeviceGroupRepositoryMockRecorder) AddDeviceAutoMatched(ctx, groupID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeviceAutoMatched", reflect.TypeOf((*MockDeviceGroupRepository)(nil).AddDeviceAutoMatched), ctx, groupID, deviceID)
}

// AddDeviceWithSource mocks base method.
func (m *MockDeviceGroupRepository) AddDeviceWithSource(ctx context.Context, groupID, deviceID uuid.UUID, sourceType string, sourceRuleID *uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeviceWithSource", ctx, groupID, deviceID, sourceType, sourceRuleID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDeviceWithSource indicates an expected call of AddDeviceWithSource.
func (mr *MockDeviceGroupRepositoryMockRecorder) AddDeviceWithSource(ctx, groupID, deviceID, sourceType, sourceRuleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeviceWithSource", reflect.TypeOf((*MockDeviceGroupRepository)(nil).AddDeviceWithSource), ctx, groupID, deviceID, sourceType, sourceRuleID)
}

// BatchAddDevices mocks base method.
func (m *MockDeviceGroupRepository) BatchAddDevices(ctx context.Context, groupID uuid.UUID, deviceIDs []uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAddDevices", ctx, groupID, deviceIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchAddDevices indicates an expected call of BatchAddDevices.
func (mr *MockDeviceGroupRepositoryMockRecorder) BatchAddDevices(ctx, groupID, deviceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAddDevices", reflect.TypeOf((*MockDeviceGroupRepository)(nil).BatchAddDevices), ctx, groupID, deviceIDs)
}

// BatchRemoveDevices mocks base method.
func (m *MockDeviceGroupRepository) BatchRemoveDevices(ctx context.Context, groupID uuid.UUID, deviceIDs []uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRemoveDevices", ctx, groupID, deviceIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchRemoveDevices indicates an expected call of BatchRemoveDevices.
func (mr *MockDeviceGroupRepositoryMockRecorder) BatchRemoveDevices(ctx, groupID, deviceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRemoveDevices", reflect.TypeOf((*MockDeviceGroupRepository)(nil).BatchRemoveDevices), ctx, groupID, deviceIDs)
}

// ClearBoundRule mocks base method.
func (m *MockDeviceGroupRepository) ClearBoundRule(ctx context.Context, groupID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearBoundRule", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearBoundRule indicates an expected call of ClearBoundRule.
func (mr *MockDeviceGroupRepositoryMockRecorder) ClearBoundRule(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearBoundRule", reflect.TypeOf((*MockDeviceGroupRepository)(nil).ClearBoundRule), ctx, groupID)
}

// CountDevicesByGroup mocks base method.
func (m *MockDeviceGroupRepository) CountDevicesByGroup(ctx context.Context, groupID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDevicesByGroup", ctx, groupID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDevicesByGroup indicates an expected call of CountDevicesByGroup.
func (mr *MockDeviceGroupRepositoryMockRecorder) CountDevicesByGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDevicesByGroup", reflect.TypeOf((*MockDeviceGroupRepository)(nil).CountDevicesByGroup), ctx, groupID)
}

// Create mocks base method.
func (m *MockDeviceGroupRepository) Create(ctx context.Context, group *DeviceGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceGroupRepositoryMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceGroupRepository)(nil).Create), ctx, group)
}

// Delete mocks base method.
func (m *MockDeviceGroupRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceGroupRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceGroupRepository)(nil).Delete), ctx, id)
}

// ExistsByParentAndName mocks base method.
func (m *MockDeviceGroupRepository) ExistsByParentAndName(ctx context.Context, parentID *uuid.UUID, name string, excludeID *uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByParentAndName", ctx, parentID, name, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByParentAndName indicates an expected call of ExistsByParentAndName.
func (mr *MockDeviceGroupRepositoryMockRecorder) ExistsByParentAndName(ctx, parentID, name, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByParentAndName", reflect.TypeOf((*MockDeviceGroupRepository)(nil).ExistsByParentAndName), ctx, parentID, name, excludeID)
}

// GetByID mocks base method.
func (m *MockDeviceGroupRepository) GetByID(ctx context.Context, id uuid.UUID) (*DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceGroupRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceGroupRepository)(nil).GetByID), ctx, id)
}

// GetStats mocks base method.
func (m *MockDeviceGroupRepository) GetStats(ctx context.Context) (*GroupStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*GroupStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockDeviceGroupRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockDeviceGroupRepository)(nil).GetStats), ctx)
}

// GetTree mocks base method.
func (m *MockDeviceGroupRepository) GetTree(ctx context.Context) ([]DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTree", ctx)
	ret0, _ := ret[0].([]DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTree indicates an expected call of GetTree.
func (mr *MockDeviceGroupRepositoryMockRecorder) GetTree(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTree", reflect.TypeOf((*MockDeviceGroupRepository)(nil).GetTree), ctx)
}

// GetTreeWithCounts mocks base method.
func (m *MockDeviceGroupRepository) GetTreeWithCounts(ctx context.Context) ([]DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreeWithCounts", ctx)
	ret0, _ := ret[0].([]DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreeWithCounts indicates an expected call of GetTreeWithCounts.
func (mr *MockDeviceGroupRepositoryMockRecorder) GetTreeWithCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreeWithCounts", reflect.TypeOf((*MockDeviceGroupRepository)(nil).GetTreeWithCounts), ctx)
}

// ListChildIDs mocks base method.
func (m *MockDeviceGroupRepository) ListChildIDs(ctx context.Context, parentID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChildIDs", ctx, parentID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildIDs indicates an expected call of ListChildIDs.
func (mr *MockDeviceGroupRepositoryMockRecorder) ListChildIDs(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildIDs", reflect.TypeOf((*MockDeviceGroupRepository)(nil).ListChildIDs), ctx, parentID)
}

// ListChildren mocks base method.
func (m *MockDeviceGroupRepository) ListChildren(ctx context.Context, parentID uuid.UUID) ([]DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChildren", ctx, parentID)
	ret0, _ := ret[0].([]DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildren indicates an expected call of ListChildren.
func (mr *MockDeviceGroupRepositoryMockRecorder) ListChildren(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildren", reflect.TypeOf((*MockDeviceGroupRepository)(nil).ListChildren), ctx, parentID)
}

// ListDeviceIDs mocks base method.
func (m *MockDeviceGroupRepository) ListDeviceIDs(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeviceIDs", ctx, groupID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeviceIDs indicates an expected call of ListDeviceIDs.
func (mr *MockDeviceGroupRepositoryMockRecorder) ListDeviceIDs(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeviceIDs", reflect.TypeOf((*MockDeviceGroupRepository)(nil).ListDeviceIDs), ctx, groupID)
}

// ListRoots mocks base method.
func (m *MockDeviceGroupRepository) ListRoots(ctx context.Context) ([]DeviceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoots", ctx)
	ret0, _ := ret[0].([]DeviceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoots indicates an expected call of ListRoots.
func (mr *MockDeviceGroupRepositoryMockRecorder) ListRoots(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoots", reflect.TypeOf((*MockDeviceGroupRepository)(nil).ListRoots), ctx)
}

// MoveDevices mocks base method.
func (m *MockDeviceGroupRepository) MoveDevices(ctx context.Context, deviceIDs []uuid.UUID, targetGroupID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveDevices", ctx, deviceIDs, targetGroupID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveDevices indicates an expected call of MoveDevices.
func (mr *MockDeviceGroupRepositoryMockRecorder) MoveDevices(ctx, deviceIDs, targetGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveDevices", reflect.TypeOf((*MockDeviceGroupRepository)(nil).MoveDevices), ctx, deviceIDs, targetGroupID)
}

// MoveGroupDevicesToDefault mocks base method.
func (m *MockDeviceGroupRepository) MoveGroupDevicesToDefault(ctx context.Context, groupIDs []uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveGroupDevicesToDefault", ctx, groupIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveGroupDevicesToDefault indicates an expected call of MoveGroupDevicesToDefault.
func (mr *MockDeviceGroupRepositoryMockRecorder) MoveGroupDevicesToDefault(ctx, groupIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveGroupDevicesToDefault", reflect.TypeOf((*MockDeviceGroupRepository)(nil).MoveGroupDevicesToDefault), ctx, groupIDs)
}

// RemoveDevice mocks base method.
func (m *MockDeviceGroupRepository) RemoveDevice(ctx context.Context, groupID, deviceID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDevice", ctx, groupID, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDevice indicates an expected call of RemoveDevice.
func (mr *MockDeviceGroupRepositoryMockRecorder) RemoveDevice(ctx, groupID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevice", reflect.TypeOf((*MockDeviceGroupRepository)(nil).RemoveDevice), ctx, groupID, deviceID)
}

// Update mocks base method.
func (m *MockDeviceGroupRepository) Update(ctx context.Context, group *DeviceGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceGroupRepositoryMockRecorder) Update(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceGroupRepository)(nil).Update), ctx, group)
}

// UpdateBoundRule mocks base method.
func (m *MockDeviceGroupRepository) UpdateBoundRule(ctx context.Context, groupID, ruleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBoundRule", ctx, groupID, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBoundRule indicates an expected call of UpdateBoundRule.
func (mr *MockDeviceGroupRepositoryMockRecorder) UpdateBoundRule(ctx, groupID, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBoundRule", reflect.TypeOf((*MockDeviceGroupRepository)(nil).UpdateBoundRule), ctx, groupID, ruleID)
}
