// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/topology (interfaces: TopoEdgeRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/topology/mock_topo_edge_repository_test.go -package=topology github.com/omcgo/omcgo/internal/topology TopoEdgeRepository
//

// Package topology is a generated GoMock package.
package topology

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/omcgo/omcgo/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTopoEdgeRepository is a mock of TopoEdgeRepository interface.
type MockTopoEdgeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTopoEdgeRepositoryMockRecorder
	isgomock struct{}
}

// MockTopoEdgeRepositoryMockRecorder is the mock recorder for MockTopoEdgeRepository.
type MockTopoEdgeRepositoryMockRecorder struct {
	mock *MockTopoEdgeRepository
}

// NewMockTopoEdgeRepository creates a new mock instance.
func NewMockTopoEdgeRepository(ctrl *gomock.Controller) *MockTopoEdgeRepository {
	mock := &MockTopoEdgeRepository{ctrl: ctrl}
	mock.recorder = &MockTopoEdgeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopoEdgeRepository) EXPECT() *MockTopoEdgeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTopoEdgeRepository) Create(ctx context.Context, edge *TopoEdge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, edge)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTopoEdgeRepositoryMockRecorder) Create(ctx, edge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTopoEdgeRepository)(nil).Create), ctx, edge)
}

// Delete mocks base method.
func (m *MockTopoEdgeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTopoEdgeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTopoEdgeRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTopoEdgeRepository) GetByID(ctx context.Context, id uuid.UUID) (*TopoEdge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*TopoEdge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTopoEdgeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTopoEdgeRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTopoEdgeRepository) List(ctx context.Context, filter TopoEdgeFilter) (*model.ListResponse[TopoEdge], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*model.ListResponse[TopoEdge])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTopoEdgeRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTopoEdgeRepository)(nil).List), ctx, filter)
}

// ListAll mocks base method.
func (m *MockTopoEdgeRepository) ListAll(ctx context.Context) ([]TopoEdge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]TopoEdge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockTopoEdgeRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockTopoEdgeRepository)(nil).ListAll), ctx)
}

// Update mocks base method.
func (m *MockTopoEdgeRepository) Update(ctx context.Context, edge *TopoEdge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, edge)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTopoEdgeRepositoryMockRecorder) Update(ctx, edge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTopoEdgeRepository)(nil).Update), ctx, edge)
}

// ListByNodeIDs mocks base method.
func (m *MockTopoEdgeRepository) ListByNodeIDs(ctx context.Context, nodeIDs []uuid.UUID) ([]TopoEdge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByNodeIDs", ctx, nodeIDs)
	ret0, _ := ret[0].([]TopoEdge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByNodeIDs indicates an expected call of ListByNodeIDs.
func (mr *MockTopoEdgeRepositoryMockRecorder) ListByNodeIDs(ctx, nodeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByNodeIDs", reflect.TypeOf((*MockTopoEdgeRepository)(nil).ListByNodeIDs), ctx, nodeIDs)
}
