// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/topology (interfaces: RuleTaskRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_rule_task_repository_test.go -package=topology github.com/omcgo/omcgo/internal/topology RuleTaskRepository
//

// Package topology is a generated GoMock package.
package topology

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleTaskRepository is a mock of RuleTaskRepository interface.
type MockRuleTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRuleTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockRuleTaskRepositoryMockRecorder is the mock recorder for MockRuleTaskRepository.
type MockRuleTaskRepositoryMockRecorder struct {
	mock *MockRuleTaskRepository
}

// NewMockRuleTaskRepository creates a new mock instance.
func NewMockRuleTaskRepository(ctrl *gomock.Controller) *MockRuleTaskRepository {
	mock := &MockRuleTaskRepository{ctrl: ctrl}
	mock.recorder = &MockRuleTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleTaskRepository) EXPECT() *MockRuleTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRuleTaskRepository) Create(ctx context.Context, task *RuleTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRuleTaskRepositoryMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRuleTaskRepository)(nil).Create), ctx, task)
}

// GetByID mocks base method.
func (m *MockRuleTaskRepository) GetByID(ctx context.Context, id uuid.UUID) (*RuleTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*RuleTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRuleTaskRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRuleTaskRepository)(nil).GetByID), ctx, id)
}

// GetLatestByRule mocks base method.
func (m *MockRuleTaskRepository) GetLatestByRule(ctx context.Context, ruleID uuid.UUID) (*RuleTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByRule", ctx, ruleID)
	ret0, _ := ret[0].(*RuleTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByRule indicates an expected call of GetLatestByRule.
func (mr *MockRuleTaskRepositoryMockRecorder) GetLatestByRule(ctx, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByRule", reflect.TypeOf((*MockRuleTaskRepository)(nil).GetLatestByRule), ctx, ruleID)
}

// ListByRule mocks base method.
func (m *MockRuleTaskRepository) ListByRule(ctx context.Context, ruleID uuid.UUID, limit int) ([]RuleTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRule", ctx, ruleID, limit)
	ret0, _ := ret[0].([]RuleTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRule indicates an expected call of ListByRule.
func (mr *MockRuleTaskRepositoryMockRecorder) ListByRule(ctx, ruleID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRule", reflect.TypeOf((*MockRuleTaskRepository)(nil).ListByRule), ctx, ruleID, limit)
}

// Update mocks base method.
func (m *MockRuleTaskRepository) Update(ctx context.Context, task *RuleTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRuleTaskRepositoryMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuleTaskRepository)(nil).Update), ctx, task)
}
