// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/omcgo/omcgo/internal/topology (interfaces: TopoNodeRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/topology/mock_topo_node_repository_test.go -package=topology github.com/omcgo/omcgo/internal/topology TopoNodeRepository
//

// Package topology is a generated GoMock package.
package topology

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/omcgo/omcgo/internal/core/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTopoNodeRepository is a mock of TopoNodeRepository interface.
type MockTopoNodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTopoNodeRepositoryMockRecorder
	isgomock struct{}
}

// MockTopoNodeRepositoryMockRecorder is the mock recorder for MockTopoNodeRepository.
type MockTopoNodeRepositoryMockRecorder struct {
	mock *MockTopoNodeRepository
}

// NewMockTopoNodeRepository creates a new mock instance.
func NewMockTopoNodeRepository(ctrl *gomock.Controller) *MockTopoNodeRepository {
	mock := &MockTopoNodeRepository{ctrl: ctrl}
	mock.recorder = &MockTopoNodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopoNodeRepository) EXPECT() *MockTopoNodeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTopoNodeRepository) Create(ctx context.Context, node *TopoNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTopoNodeRepositoryMockRecorder) Create(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTopoNodeRepository)(nil).Create), ctx, node)
}

// Delete mocks base method.
func (m *MockTopoNodeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTopoNodeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTopoNodeRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTopoNodeRepository) GetByID(ctx context.Context, id uuid.UUID) (*TopoNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*TopoNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTopoNodeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTopoNodeRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTopoNodeRepository) List(ctx context.Context, filter TopoNodeFilter) (*model.ListResponse[TopoNode], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].(*model.ListResponse[TopoNode])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTopoNodeRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTopoNodeRepository)(nil).List), ctx, filter)
}

// ListAll mocks base method.
func (m *MockTopoNodeRepository) ListAll(ctx context.Context, domainID *uuid.UUID, nodeType *string, status *string, limit int) ([]TopoNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx, domainID, nodeType, status, limit)
	ret0, _ := ret[0].([]TopoNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockTopoNodeRepositoryMockRecorder) ListAll(ctx, domainID, nodeType, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockTopoNodeRepository)(nil).ListAll), ctx, domainID, nodeType, status, limit)
}

// Update mocks base method.
func (m *MockTopoNodeRepository) Update(ctx context.Context, node *TopoNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTopoNodeRepositoryMockRecorder) Update(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTopoNodeRepository)(nil).Update), ctx, node)
}
