package pageconfig

const defaultSNMPV2Community = "baicells"

// No built-in delivery targets: delivery destinations are environment-specific and must
// be added manually by the operator. Kept as a function (returning nil) so the no-repo
// fallback and test fakes have a stable empty default.
func defaultDeliveryTargets() []DeliveryTarget {
	return nil
}

func defaultSNMPAlarmFields() []SNMPAlarmField {
	return []SNMPAlarmField{
		{Order: 1, Field: "notificationID", OID: OIDNotificationIDValue, Type: "Integer32(1..2147483647)", Source: "alarm.sequence_id", Required: true},
		{Order: 2, Field: "alarmUniqueId", OID: OIDAlarmUniqueIDValue, Type: "OCTET STRING(5)", Source: "alarm.alarm_identifier", Required: true},
		{Order: 3, Field: "notificationType", OID: OIDNotificationTypeValue, Type: "OCTET STRING(1)", Source: "alarm.status -> 0/1", Required: true},
		{Order: 4, Field: "eventTime", OID: OIDEventTimeValue, Type: "Counter64(13)", Source: "alarm.raised_at / alarm.cleared_at -> epoch_ms", Required: true},
		{Order: 5, Field: "equipmentSDN", OID: OIDEquipmentSDNValue, Type: "OCTET STRING(1..45)", Source: "alarm.device_sn", Required: true},
		{Order: 6, Field: "equipmentName", OID: OIDEquipmentNameValue, Type: "OCTET STRING(0..50)", Source: "alarm.device_name / device_info.device_name", Required: true},
		{Order: 7, Field: "equipmentClass", OID: OIDEquipmentClassValue, Type: "OCTET STRING(0..45)", Source: "device.technology", Required: true},
		{Order: 8, Field: "objectSDN", OID: OIDObjectSDNValue, Type: "OCTET STRING(1..45)", Source: "alarm.alarm_source", Required: true},
		{Order: 9, Field: "objectInstanceName", OID: OIDObjectInstanceNameValue, Type: "OCTET STRING(0..50)", Source: "alarm.network_location", Required: true},
		{Order: 10, Field: "objectClass", OID: OIDObjectClassValue, Type: "OCTET STRING(0..45)", Source: "alarm.event_type", Required: true},
		{Order: 11, Field: "additionalText", OID: OIDAdditionalTextValue, Type: "OCTET STRING(0..256)", Source: "alarm.description", Required: true},
		{Order: 12, Field: "deviceVendorOUI", OID: OIDDeviceVendorOUIValue, Type: "OCTET STRING(0..10)", Source: "device.oui / device.manufacturer", Required: true},
		{Order: 13, Field: "specificProblemID", OID: OIDSpecificProblemIDValue, Type: "OCTET STRING(5)", Source: "alarm.alarm_type / alarm_definition.vendor_code", Required: true},
		{Order: 14, Field: "specificProblem", OID: OIDSpecificProblemValue, Type: "OCTET STRING(0..256)", Source: "alarm.description", Required: true},
		{Order: 15, Field: "alarmType", OID: OIDAlarmTypeValue, Type: "OCTET STRING(5)", Source: "alarm.alarm_type", Required: true},
		{Order: 16, Field: "perceivedSeverity", OID: OIDPerceivedSeverityValue, Type: "OCTET STRING(5..8)", Source: "alarm.severity", Required: true},
		{Order: 17, Field: "probableCause", OID: OIDProbableCauseValue, Type: "OCTET STRING(0..256)", Source: "alarm.probable_cause", Required: true},
		{Order: 18, Field: "additionalInformation", OID: OIDAdditionalInformationValue, Type: "OCTET STRING(0..256)", Source: "alarm.additional_info", Required: true},
	}
}

func defaultSNMPAlarmTargets() []SNMPAlarmTarget {
	return []SNMPAlarmTarget{
		{
			Key:                 "snmp-v2-primary",
			Name:                "SNMP V2C",
			Enabled:             false,
			Version:             "v2",
			NotificationType:    "Trap",
			ListenIP:            "0.0.0.0",
			ListenPort:          161,
			TargetHost:          "",
			TargetPort:          162,
			Community:           defaultSNMPV2Community,
			ClearSeverityPolicy: "保留原级别",
			MIBQueryEnabled:     true,
			TimeoutSeconds:      5,
			Retries:             1,
			MIBFields:           defaultSNMPAlarmFields(),
		},
		{
			Key:                 "snmp-v3-inform",
			Name:                "SNMP V3",
			Enabled:             false,
			Version:             "v3",
			NotificationType:    "Inform",
			ListenIP:            "0.0.0.0",
			ListenPort:          161,
			TargetHost:          "",
			TargetPort:          163,
			SecurityName:        "",
			AuthProtocol:        "SHA",
			PrivProtocol:        "DES",
			ClearSeverityPolicy: "保留原级别",
			MIBQueryEnabled:     false,
			TimeoutSeconds:      5,
			Retries:             1,
			MIBFields:           defaultSNMPAlarmFields(),
		},
	}
}

func defaultSocketAlarmConfigs() []SocketAlarmConfig {
	return []SocketAlarmConfig{
		{
			Key:                 "socket-ctcc-server",
			Name:                "CTCC Socket 告警服务端",
			Enabled:             false,
			Profile:             "CTCC",
			Mode:                "server",
			ListenIP:            "0.0.0.0",
			ListenPort:          31232,
			MaxClients:          20,
			RealtimePushEnabled: true,
			ClientSyncEnabled:   true,
			HeartbeatSeconds:    60,
			HeartbeatTimes:      3,
			IdleTimeoutSeconds:  180,
			Accounts: []SocketAccount{
				{Key: "ctcc-msg", Enabled: false, Channel: "实时/同步账号", Username: "", Type: "msg", Purpose: "实时推送和客户端同步告警"},
			},
		},
		{
			Key:                 "socket-cucc-server",
			Name:                "CUCC Socket 告警服务端",
			Enabled:             false,
			Profile:             "CUCC",
			Mode:                "server",
			ListenIP:            "0.0.0.0",
			ListenPort:          31233,
			MaxClients:          20,
			RealtimePushEnabled: true,
			ClientSyncEnabled:   true,
			HeartbeatSeconds:    60,
			HeartbeatTimes:      3,
			IdleTimeoutSeconds:  180,
			Accounts: []SocketAccount{
				{Key: "cucc-msg", Enabled: false, Channel: "实时/同步账号", Username: "", Type: "msg", Purpose: "实时推送和客户端同步告警"},
				{Key: "cucc-ftp", Enabled: false, Channel: "文件同步账号", Username: "", Type: "ftp", Purpose: "客户端同步历史告警文件"},
			},
		},
	}
}

func defaultAPIConfigs() []APIConfig {
	return []APIConfig{
		{
			Key:                "auth-login",
			Name:               "北向认证：获取访问 Token",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/access/token",
			Kind:               "鉴权管理",
			DataType:           "auth",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/pageconfig/service.go + cmd/app/provider/router.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.token", "data.expires", "data.access_token", "data.expires_at", "data.token_type"}},
		},
		{
			Key:                "api-user-list",
			Name:               "北向API用户：查询用户列表",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/user/users",
			Kind:               "鉴权管理",
			DataType:           "api_user",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_admin_facade.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data[].userId", "data[].userName", "data[].userPwd", "data[].userEnable", "data[].operatorCode", "data[].createTime"}},
		},
		{
			Key:                "api-user-create",
			Name:               "北向API用户：新增用户",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/user",
			Kind:               "鉴权管理",
			DataType:           "api_user",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_admin_facade.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.userId", "data.userName", "data.userPwd", "data.userEnable", "data.createTime"}},
		},
		{
			Key:                "api-user-update",
			Name:               "北向API用户：更新用户",
			Method:             "PUT",
			Path:               "/api/v1/northbound/v1/user/update",
			Kind:               "鉴权管理",
			DataType:           "api_user",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_admin_facade.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.userId", "data.userName", "data.userPwd", "data.userEnable", "data.updateTime"}},
		},
		{
			Key:                "api-user-delete",
			Name:               "北向API用户：删除用户",
			Method:             "DELETE",
			Path:               "/api/v1/northbound/v1/user/{id}",
			Kind:               "鉴权管理",
			DataType:           "api_user",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_admin_facade.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id", "data.userId"}},
		},
		{
			Key:                "api-log-page",
			Name:               "北向调用日志：分页查询",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/log/page",
			Kind:               "日志管理",
			DataType:           "api_log",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_admin_facade.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.rows[].id", "data.rows[].nameEn", "data.rows[].type", "data.rows[].status", "data.rows[].reqParams", "data.total"}},
		},
		{
			Key:                "api-log-export",
			Name:               "北向调用日志：导出CSV",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/log/exportLogToCsvFile",
			Kind:               "日志管理",
			DataType:           "api_log",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_admin_facade.go",
			ResponseContract:   map[string]any{"fields": []string{"CSV:id", "nameEn", "nameCn", "type", "status", "reqParams", "resParams1", "createTime", "updateTime"}},
		},
		{
			Key:                "nb-sync-full-device",
			Name:               "设备全量同步：导出当前设备清单",
			Method:             "GET",
			Path:               "/api/v1/northbound/v1/sync/full?data_type=device&format=json",
			Kind:               "正式北向",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/sync/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.data_type", "data.items[]", "data.total", "data.synced_at"}},
		},
		{
			Key:                "nb-export-config",
			Name:               "配置快照导出：按设备ID导出参数",
			Method:             "GET",
			Path:               "/api/v1/northbound/v1/export/config/{deviceId}",
			Kind:               "正式北向",
			DataType:           "config",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/config_handler.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.device_id", "data.parameters[]", "data.total"}},
		},
		{
			Key:                "device-list",
			Name:               "设备查询：按SN/制式/分组分页查询",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/query",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.items[]", "data.total", "data.page", "data.page_size", "data.total_pages", "data.rows?", "data.pageNo?", "data.totalRows?"}},
		},
		{
			Key:                "device-status",
			Name:               "设备状态：在线、小区与MME状态",
			Method:             "GET",
			Path:               "/api/v1/northbound/v1/device/status/{sn}",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.sn", "data.serialNumber", "data.connectionStatus", "data.is_online", "data.technology", "data.cellStatus?", "data.mmeStatus?", "data.ueCount?"}},
		},
		{
			Key:                "device-detail",
			Name:               "设备详情：基础信息与扩展信息",
			Method:             "GET",
			Path:               "/api/v1/northbound/v1/device/infos/{sn}",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id", "data.serial_number", "data.device_name", "data.product_class", "data.firmware_version", "data.technology", "data.is_online"}},
		},
		{
			Key:                "device-register-create",
			Name:               "设备预注册：登记待接入设备",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/register",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_registration_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id", "data.serial_number", "data.group_id", "data.carrier", "data.status", "data.created_at"}},
		},
		{
			Key:                "device-register-list",
			Name:               "设备预注册查询：分页查看登记记录",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/register/page",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_registration_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.items[]", "data.total", "data.page", "data.page_size", "data.total_pages"}},
		},
		{
			Key:                "device-register-delete",
			Name:               "设备预注册删除：移除登记记录",
			Method:             "DELETE",
			Path:               "/api/v1/northbound/v1/device/register/{id}",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_registration_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id"}},
		},
		{
			Key:                "device-group-tree",
			Name:               "设备组查询：获取分组树",
			Method:             "GET",
			Path:               "/api/v1/northbound/v1/device/group",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.items[].id", "data.items[].name", "data.items[].parent_id", "data.items[].children[]", "data.total"}},
		},
		{
			Key:                "device-group-create",
			Name:               "设备组新增：创建一级或子设备组",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/group",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id", "data.name", "data.parent_id", "data.level", "data.status"}},
		},
		{
			Key:                "device-group-update",
			Name:               "设备组修改：更新名称/父级/规则",
			Method:             "PUT",
			Path:               "/api/v1/northbound/v1/device/group/{id}",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id", "data.name", "data.parent_id", "data.level", "data.updated_at"}},
		},
		{
			Key:                "device-group-delete",
			Name:               "设备组删除：删除分组并处理成员",
			Method:             "DELETE",
			Path:               "/api/v1/northbound/v1/device/group/{id}",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.group_id"}},
		},
		{
			Key:                "device-group-add-devices",
			Name:               "设备组成员维护：把设备加入分组",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/group/{id}/devices",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.group_id", "data.affected", "data.device_count"}},
		},
		{
			Key:                "device-group-sub-create",
			Name:               "子设备组新增：创建带父级的设备组",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/group/sub",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id", "data.name", "data.parent_id", "data.level", "data.status"}},
		},
		{
			Key:                "device-group-sub-update",
			Name:               "子设备组修改：更新名称/父级/规则",
			Method:             "PUT",
			Path:               "/api/v1/northbound/v1/device/group/sub",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.id", "data.name", "data.parent_id", "data.level", "data.updated_at"}},
		},
		{
			Key:                "device-group-sub-delete",
			Name:               "子设备组删除：删除指定设备组",
			Method:             "DELETE",
			Path:               "/api/v1/northbound/v1/device/group/sub",
			Kind:               "业务复用",
			DataType:           "group",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/topology/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.group_id"}},
		},
		{
			Key:                "parameter-tree",
			Name:               "参数快照：读取系统已保存参数",
			Method:             "GET",
			Path:               "/api/v1/northbound/v1/device/parameters/{sn}",
			Kind:               "业务复用",
			DataType:           "config",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.sn", "data.parameters", "data.items[].parameter_path", "data.items[].parameter_value", "data.items[].parameter_type", "data.items[].writable", "data.total"}},
		},
		{
			Key:                "parameter-set",
			Name:               "参数下发：异步设置设备参数",
			Method:             "PUT",
			Path:               "/api/v1/northbound/v1/device/parameters/{sn}",
			Kind:               "业务复用",
			DataType:           "config",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.task_id", "data.jobId", "data.sn", "data.waitTime", "data.parameters"}},
		},
		{
			Key:                "parameter-cellname",
			Name:               "基站名称修改：更新OMC名称并可同步设备",
			Method:             "PUT",
			Path:               "/api/v1/northbound/v1/device/parameters/cellname/{sn}",
			Kind:               "业务复用",
			DataType:           "config",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.task_id?", "data.jobId?", "data.sn", "data.cellName", "data.message"}},
		},
		{
			Key:                "config-pull",
			Name:               "参数拉取：异步从设备读取指定路径",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/parameters/query/{sn}",
			Kind:               "业务复用",
			DataType:           "config",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.jobId", "data.sn", "data.waitTime", "data.request_id?", "data.run_id?", "data.task_count", "data.status"}},
		},
		{
			Key:                "task-detail",
			Name:               "任务结果查询：按jobId查看异步结果",
			Method:             "GET",
			Path:               "/api/v1/northbound/v1/job/result/{jobId}",
			Kind:               "业务复用",
			DataType:           "task",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/paramsync/service.go + internal/device/device_service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.jobId", "data.name", "data.status", "data.sn", "data.errorMessage", "data.createTime", "data.completeTime", "data.parameters", "data.total", "data.details"}},
		},
		{
			Key:                "task-page",
			Name:               "任务分页查询：查看设备或日志采集任务",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/job/result/page",
			Kind:               "业务复用",
			DataType:           "task",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/task/service.go + internal/ufte/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.items[]", "data.total", "data.page", "data.page_size", "data.total_pages"}},
		},
		{
			Key:                "device-task-create",
			Name:               "高级任务：按method创建TR-069任务",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/task/{sn}",
			Kind:               "业务复用",
			DataType:           "advanced_task",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/task/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.task_id", "data.jobId", "data.sn", "data.waitTime", "data.method"}},
		},
		{
			Key:                "device-reboot",
			Name:               "设备重启：下发Reboot任务",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/reboot/{sn}",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/task/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.task_id", "data.jobId", "data.sn", "data.waitTime"}},
		},
		{
			Key:                "device-reset",
			Name:               "设备重置：下发FactoryReset任务",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/reset/{sn}",
			Kind:               "业务复用",
			DataType:           "device",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/task/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.task_id", "data.jobId", "data.sn", "data.waitTime"}},
		},
		{
			Key:                "device-log-collect",
			Name:               "设备日志收集：触发运行/故障日志上传",
			Method:             "POST",
			Path:               "/api/v1/northbound/v1/device/log/collect/{sn}",
			Kind:               "业务复用",
			DataType:           "log_collect",
			Enabled:            false,
			OldSystemSupported: true,
			CurrentSupported:   true,
			Source:             "omcgo/internal/northbound/legacy_facade.go + internal/ufte/service.go + internal/software/service.go",
			ResponseContract:   map[string]any{"fields": []string{"ret", "msg", "data.task_id", "data.jobId", "data.sn", "data.waitTime", "data.typeCode", "data.status"}},
		},
	}
}

const (
	OIDNotificationIDValue        = "1.3.6.1.4.1.53058.1.1.1.1.1.1"
	OIDAlarmUniqueIDValue         = "1.3.6.1.4.1.53058.1.1.1.1.1.2"
	OIDNotificationTypeValue      = "1.3.6.1.4.1.53058.1.1.1.1.1.3"
	OIDEventTimeValue             = "1.3.6.1.4.1.53058.1.1.1.1.1.4"
	OIDEquipmentSDNValue          = "1.3.6.1.4.1.53058.1.1.1.1.1.5"
	OIDEquipmentNameValue         = "1.3.6.1.4.1.53058.1.1.1.1.1.6"
	OIDEquipmentClassValue        = "1.3.6.1.4.1.53058.1.1.1.1.1.7"
	OIDObjectSDNValue             = "1.3.6.1.4.1.53058.1.1.1.1.1.8"
	OIDObjectInstanceNameValue    = "1.3.6.1.4.1.53058.1.1.1.1.1.9"
	OIDObjectClassValue           = "1.3.6.1.4.1.53058.1.1.1.1.1.10"
	OIDAdditionalTextValue        = "1.3.6.1.4.1.53058.1.1.1.1.1.11"
	OIDDeviceVendorOUIValue       = "1.3.6.1.4.1.53058.1.1.1.1.1.12"
	OIDSpecificProblemIDValue     = "1.3.6.1.4.1.53058.1.1.1.1.1.13"
	OIDSpecificProblemValue       = "1.3.6.1.4.1.53058.1.1.1.1.1.14"
	OIDAlarmTypeValue             = "1.3.6.1.4.1.53058.1.1.1.1.1.15"
	OIDPerceivedSeverityValue     = "1.3.6.1.4.1.53058.1.1.1.1.1.16"
	OIDProbableCauseValue         = "1.3.6.1.4.1.53058.1.1.1.1.1.17"
	OIDAdditionalInformationValue = "1.3.6.1.4.1.53058.1.1.1.1.1.18"
)
