package pageconfig

var legacyPMBaseFieldsPELTE = []legacyPMBaseFieldSeed{
	{"dn", "legacy.pm.serial_dn", "devices.serial_number / pm_metrics.device_sn", "string", "quote", "Device DN"},
	{"enb_id", "legacy.pm.enb_id", "device_info.enb_id or ECI >> 8", "string", "quote", "eNB ID"},
	{"userlabel", "legacy.pm.userlabel", "device_info.device_name / devices.site_name", "string", "quote", "User label"},
	{"freq_mode", "legacy.pm.freq_mode", "derived from device_info.network_model", "string", "enum", "Duplex mode"},
}

var legacyPMBaseFieldsS0008PC = append([]legacyPMBaseFieldSeed{
	{"date_time", "legacy.pm.file_date_time", "derived from export period end", "datetime", "yyyyMMddHHmmss", "Date time"},
	{"granularity", "legacy.pm.granularity_15", "fixed legacy granularity", "number", "number", "Granularity"},
}, legacyPMBaseFieldsS0001PC...)

var legacyPMBaseFieldsS0016LTEPC = append([]legacyPMBaseFieldSeed{
	{"Time", "legacy.pm.file_date_time", "derived from export period end", "datetime", "yyyyMMddHHmmss", "Time"},
	{"Site ID", "legacy.pm.site_id", "devices.site_id", "string", "quote", "Site ID"},
}, legacyPMBaseFieldsS0001PC...)

var legacyPMBaseFieldsS0009PC = []legacyPMBaseFieldSeed{
	{"Serial Number", "legacy.pm.serial_number", "devices.serial_number / pm_metrics.device_sn", "string", "quote", "Serial number"},
	{"Cell Name", "legacy.pm.cell_name", "device_info.device_name / devices.site_name", "string", "quote", "Cell name"},
	{"Site Name", "legacy.pm.site_name", "devices.site_name", "string", "quote", "Site name"},
	{"ECI", "legacy.pm.eci_hash", "device_info.eci with legacy suffix", "string", "quote", "ECI"},
	{"eNB ID", "legacy.pm.enb_id", "device_info.enb_id or ECI >> 8", "string", "quote", "eNB ID"},
	{"Cell ID", "legacy.pm.cel_id", "ECI & 255 or device_info.cell_id", "string", "quote", "Cell ID"},
	{"Group Name", "legacy.pm.group_name", "device_groups.name", "string", "quote", "Group name"},
	{"Period(Minute)", "legacy.pm.period_minute_15", "fixed legacy period minute", "number", "number", "Period minute"},
}

var legacyPMBaseFieldsGNBPC = []legacyPMBaseFieldSeed{
	{"dn", "legacy.pm.dn", "device_info.eci / pm_metrics.object_ldn", "string", "preserve text", "Cell DN / ECI"},
	{"related_gnb_dn", "legacy.pm.related_gnb_dn", "devices.serial_number / pm_metrics.device_sn", "string", "quote", "Related gNB DN"},
	{"related_gnb_id", "legacy.pm.related_gnb_id", "device_info.enb_id or ECI >> 8", "string", "quote", "Related gNB ID"},
	{"related_gnb_userlabel", "legacy.pm.related_gnb_userlabel", "devices.site_name / device_info.device_name", "string", "quote", "Related gNB label"},
}

var legacyPMBaseFieldsS0013GSMPC = []legacyPMBaseFieldSeed{
	{"dn", "legacy.pm.dn", "device_info.eci / pm_metrics.object_ldn", "string", "preserve text", "Cell DN / ECI"},
	{"related_gsm_dn", "legacy.pm.related_gsm_dn", "devices.serial_number / pm_metrics.device_sn", "string", "quote", "Related GSM DN"},
	{"related_gsm_userlabel", "legacy.pm.related_gsm_userlabel", "devices.site_name / device_info.device_name", "string", "quote", "Related GSM label"},
	{"cel_id_local", "legacy.pm.cel_id_local", "device_info.cell_id", "string", "quote", "Local cell ID"},
	{"userlabel", "legacy.pm.userlabel", "device_info.device_name / devices.site_name", "string", "quote", "Cell label"},
	{"freq_mode", "legacy.pm.freq_mode", "derived from device_info.network_model", "string", "enum", "Duplex mode"},
}

var legacyPMBaseFieldsS0016GSMPC = []legacyPMBaseFieldSeed{
	{"Time", "legacy.pm.file_date_time", "derived from export period end", "datetime", "yyyyMMddHHmmss", "Time"},
	{"Site ID", "legacy.pm.site_id", "devices.site_id", "string", "quote", "Site ID"},
	{"related_gsm_dn", "legacy.pm.related_gsm_dn", "devices.serial_number / pm_metrics.device_sn", "string", "quote", "Related GSM DN"},
	{"related_gsm_userlabel", "legacy.pm.related_gsm_userlabel", "devices.site_name / device_info.device_name", "string", "quote", "Related GSM label"},
	{"userlabel", "legacy.pm.userlabel", "device_info.device_name / devices.site_name", "string", "quote", "Cell label"},
}

var legacyS0002PEMetrics = []legacyPMMetricSeed{
	{metricPath: "C000110003", outputAlias: "EQPT_MeanMeLoad_m", matchAlias: "EQPT_MeanMeLoad_m"},
	{metricPath: "C000110004", outputAlias: "EQPT_MeanMeLoad_s", matchAlias: "EQPT_MeanMeLoad_s"},
	{metricPath: "C000110005", outputAlias: "EQPT_MaxMeLoad_m", matchAlias: "EQPT_MaxMeLoad_m"},
	{metricPath: "C000110006", outputAlias: "EQPT_MaxMeLoad_s", matchAlias: "EQPT_MaxMeLoad_s"},
}

var legacyS0002PCMetrics = []legacyPMMetricSeed{
	{metricPath: "C000080030", outputAlias: "PRACH_NonPreDetected", matchAlias: "PRACH_NonPreDetected"},
	{metricPath: "C000000004", outputAlias: "RRC_UserConnMax", matchAlias: "RRC_UserConnMax"},
	{metricPath: "C000000003", outputAlias: "RRC_UserConnMean", matchAlias: "RRC_UserConnMean"},
	{metricPath: "C000070019", outputAlias: "Traffic_ActUserUl", matchAlias: "Traffic_ActUserUl"},
	{metricPath: "C000070001", outputAlias: "Traffic_ActUserUl_QCI1", matchAlias: "Traffic_ActUserUl_QCI1"},
	{metricPath: "C000070002", outputAlias: "Traffic_ActUserUl_QCI2", matchAlias: "Traffic_ActUserUl_QCI2"},
	{metricPath: "C000070003", outputAlias: "Traffic_ActUserUl_QCI3", matchAlias: "Traffic_ActUserUl_QCI3"},
	{metricPath: "C000070004", outputAlias: "Traffic_ActUserUl_QCI4", matchAlias: "Traffic_ActUserUl_QCI4"},
	{metricPath: "C000070005", outputAlias: "Traffic_ActUserUl_QCI5", matchAlias: "Traffic_ActUserUl_QCI5"},
	{metricPath: "C000070006", outputAlias: "Traffic_ActUserUl_QCI6", matchAlias: "Traffic_ActUserUl_QCI6"},
	{metricPath: "C000070007", outputAlias: "Traffic_ActUserUl_QCI7", matchAlias: "Traffic_ActUserUl_QCI7"},
	{metricPath: "C000070008", outputAlias: "Traffic_ActUserUl_QCI8", matchAlias: "Traffic_ActUserUl_QCI8"},
	{metricPath: "C000070009", outputAlias: "Traffic_ActUserUl_QCI9", matchAlias: "Traffic_ActUserUl_QCI9"},
	{metricPath: "C000070020", outputAlias: "Traffic_ActUserDl", matchAlias: "Traffic_ActUserDl"},
	{metricPath: "C000070010", outputAlias: "Traffic_ActUserDl_QCI1", matchAlias: "Traffic_ActUserDl_QCI1"},
	{metricPath: "C000070011", outputAlias: "Traffic_ActUserDl_QCI2", matchAlias: "Traffic_ActUserDl_QCI2"},
	{metricPath: "C000070012", outputAlias: "Traffic_ActUserDl_QCI3", matchAlias: "Traffic_ActUserDl_QCI3"},
	{metricPath: "C000070013", outputAlias: "Traffic_ActUserDl_QCI4", matchAlias: "Traffic_ActUserDl_QCI4"},
	{metricPath: "C000070014", outputAlias: "Traffic_ActUserDl_QCI5", matchAlias: "Traffic_ActUserDl_QCI5"},
	{metricPath: "C000070015", outputAlias: "Traffic_ActUserDl_QCI6", matchAlias: "Traffic_ActUserDl_QCI6"},
	{metricPath: "C000070016", outputAlias: "Traffic_ActUserDl_QCI7", matchAlias: "Traffic_ActUserDl_QCI7"},
	{metricPath: "C000070017", outputAlias: "Traffic_ActUserDl_QCI8", matchAlias: "Traffic_ActUserDl_QCI8"},
	{metricPath: "C000070018", outputAlias: "Traffic_ActUserDl_QCI9", matchAlias: "Traffic_ActUserDl_QCI9"},
	{metricPath: "C000070021", outputAlias: "Traffic_ActUserMean", matchAlias: "Traffic_ActUserMean"},
	{metricPath: "C000070022", outputAlias: "Traffic_ActUserUlMax", matchAlias: "Traffic_ActUserUlMax"},
	{metricPath: "C000000009", outputAlias: "RRC_AttConnEstab_UE", matchAlias: "RRC_AttConnEstab_UE"},
	{metricPath: "C000000016", outputAlias: "RRC_SuccConnEstab_UE", matchAlias: "RRC_SuccConnEstab_UE"},
	{metricPath: "C000000008", outputAlias: "RRC_AttConnEstab_Net", matchAlias: "RRC_AttConnEstab_Net"},
	{metricPath: "C000000015", outputAlias: "RRC_SuccConnEstab_Net", matchAlias: "RRC_SuccConnEstab_Net"},
	{metricPath: "C000000038", outputAlias: "RRC_FailConnEstab_OtherCause", matchAlias: "RRC_FailConnEstab_OtherCause"},
	{metricPath: "C000120001", outputAlias: "S1Sig_AttConnEstab", matchAlias: "S1Sig_AttConnEstab"},
	{metricPath: "C000120002", outputAlias: "S1Sig_SuccConnEstab", matchAlias: "S1Sig_SuccConnEstab"},
	{metricPath: "C000010070", outputAlias: "ERAB_InitAttEstab", matchAlias: "ERAB_InitAttEstab"},
	{metricPath: "C000010071", outputAlias: "ERAB_InitAttEstab_QCI1", matchAlias: "ERAB_InitAttEstab_QCI1"},
	{metricPath: "C000010072", outputAlias: "ERAB_InitAttEstab_QCI2", matchAlias: "ERAB_InitAttEstab_QCI2"},
	{metricPath: "C000010073", outputAlias: "ERAB_InitAttEstab_QCI3", matchAlias: "ERAB_InitAttEstab_QCI3"},
	{metricPath: "C000010074", outputAlias: "ERAB_InitAttEstab_QCI4", matchAlias: "ERAB_InitAttEstab_QCI4"},
	{metricPath: "C000010075", outputAlias: "ERAB_InitAttEstab_QCI5", matchAlias: "ERAB_InitAttEstab_QCI5"},
	{metricPath: "C000010076", outputAlias: "ERAB_InitAttEstab_QCI6", matchAlias: "ERAB_InitAttEstab_QCI6"},
	{metricPath: "C000010077", outputAlias: "ERAB_InitAttEstab_QCI7", matchAlias: "ERAB_InitAttEstab_QCI7"},
	{metricPath: "C000010078", outputAlias: "ERAB_InitAttEstab_QCI8", matchAlias: "ERAB_InitAttEstab_QCI8"},
	{metricPath: "C000010079", outputAlias: "ERAB_InitAttEstab_QCI9", matchAlias: "ERAB_InitAttEstab_QCI9"},
	{metricPath: "C000010080", outputAlias: "ERAB_InitSuccEstab", matchAlias: "ERAB_InitSuccEstab"},
	{metricPath: "C000010081", outputAlias: "ERAB_InitSuccEstab_QCI1", matchAlias: "ERAB_InitSuccEstab_QCI1"},
	{metricPath: "C000010082", outputAlias: "ERAB_InitSuccEstab_QCI2", matchAlias: "ERAB_InitSuccEstab_QCI2"},
	{metricPath: "C000010083", outputAlias: "ERAB_InitSuccEstab_QCI3", matchAlias: "ERAB_InitSuccEstab_QCI3"},
	{metricPath: "C000010084", outputAlias: "ERAB_InitSuccEstab_QCI4", matchAlias: "ERAB_InitSuccEstab_QCI4"},
	{metricPath: "C000010085", outputAlias: "ERAB_InitSuccEstab_QCI5", matchAlias: "ERAB_InitSuccEstab_QCI5"},
	{metricPath: "C000010086", outputAlias: "ERAB_InitSuccEstab_QCI6", matchAlias: "ERAB_InitSuccEstab_QCI6"},
	{metricPath: "C000010087", outputAlias: "ERAB_InitSuccEstab_QCI7", matchAlias: "ERAB_InitSuccEstab_QCI7"},
	{metricPath: "C000010088", outputAlias: "ERAB_InitSuccEstab_QCI8", matchAlias: "ERAB_InitSuccEstab_QCI8"},
	{metricPath: "C000010089", outputAlias: "ERAB_InitSuccEstab_QCI9", matchAlias: "ERAB_InitSuccEstab_QCI9"},
	{metricPath: "C000010106", outputAlias: "ERAB_AddAttEstab", matchAlias: "ERAB_AddAttEstab"},
	{metricPath: "C000010097", outputAlias: "ERAB_AddAttEstab_QCI1", matchAlias: "ERAB_AddAttEstab_QCI1"},
	{metricPath: "C000010098", outputAlias: "ERAB_AddAttEstab_QCI2", matchAlias: "ERAB_AddAttEstab_QCI2"},
	{metricPath: "C000010099", outputAlias: "ERAB_AddAttEstab_QCI3", matchAlias: "ERAB_AddAttEstab_QCI3"},
	{metricPath: "C000010100", outputAlias: "ERAB_AddAttEstab_QCI4", matchAlias: "ERAB_AddAttEstab_QCI4"},
	{metricPath: "C000010101", outputAlias: "ERAB_AddAttEstab_QCI5", matchAlias: "ERAB_AddAttEstab_QCI5"},
	{metricPath: "C000010102", outputAlias: "ERAB_AddAttEstab_QCI6", matchAlias: "ERAB_AddAttEstab_QCI6"},
	{metricPath: "C000010103", outputAlias: "ERAB_AddAttEstab_QCI7", matchAlias: "ERAB_AddAttEstab_QCI7"},
	{metricPath: "C000010104", outputAlias: "ERAB_AddAttEstab_QCI8", matchAlias: "ERAB_AddAttEstab_QCI8"},
	{metricPath: "C000010105", outputAlias: "ERAB_AddAttEstab_QCI9", matchAlias: "ERAB_AddAttEstab_QCI9"},
	{metricPath: "C000010116", outputAlias: "ERAB_AddSuccEstab", matchAlias: "ERAB_AddSuccEstab"},
	{metricPath: "C000010107", outputAlias: "ERAB_AddSuccEstab_QCI1", matchAlias: "ERAB_AddSuccEstab_QCI1"},
	{metricPath: "C000010108", outputAlias: "ERAB_AddSuccEstab_QCI2", matchAlias: "ERAB_AddSuccEstab_QCI2"},
	{metricPath: "C000010109", outputAlias: "ERAB_AddSuccEstab_QCI3", matchAlias: "ERAB_AddSuccEstab_QCI3"},
	{metricPath: "C000010110", outputAlias: "ERAB_AddSuccEstab_QCI4", matchAlias: "ERAB_AddSuccEstab_QCI4"},
	{metricPath: "C000010111", outputAlias: "ERAB_AddSuccEstab_QCI5", matchAlias: "ERAB_AddSuccEstab_QCI5"},
	{metricPath: "C000010112", outputAlias: "ERAB_AddSuccEstab_QCI6", matchAlias: "ERAB_AddSuccEstab_QCI6"},
	{metricPath: "C000010113", outputAlias: "ERAB_AddSuccEstab_QCI7", matchAlias: "ERAB_AddSuccEstab_QCI7"},
	{metricPath: "C000010114", outputAlias: "ERAB_AddSuccEstab_QCI8", matchAlias: "ERAB_AddSuccEstab_QCI8"},
	{metricPath: "C000010115", outputAlias: "ERAB_AddSuccEstab_QCI9", matchAlias: "ERAB_AddSuccEstab_QCI9"},
	{metricPath: "C000050001", outputAlias: "Paging_S1_Rx", matchAlias: "Paging_S1_Rx"},
	{metricPath: "C000050002", outputAlias: "Paging_Discard_Num", matchAlias: "Paging_Discard_Num"},
	{metricPath: "C000010122", outputAlias: "ERAB_FailEstab_UeNoReply", matchAlias: "ERAB_FailEstab_UeNoReply"},
	{metricPath: "C000010123", outputAlias: "ERAB_FailEstab_TNL", matchAlias: "ERAB_FailEstab_TNL"},
	{metricPath: "C000010119", outputAlias: "ERAB_FailEstab_RNL", matchAlias: "ERAB_FailEstab_RNL"},
	{metricPath: "C000010120", outputAlias: "ERAB_FailEstab_NoRadioRes", matchAlias: "ERAB_FailEstab_NoRadioRes"},
	{metricPath: "C000020021", outputAlias: "UECNTX_AbnormRel", matchAlias: "UECNTX_AbnormRel"},
	{metricPath: "C000020015", outputAlias: "UECNTX_NormRel", matchAlias: "UECNTX_NormRel"},
	{metricPath: "C000010245", outputAlias: "ERAB_AbnormRel_QCI1", matchAlias: "ERAB_AbnormRel_QCI1"},
	{metricPath: "C000010246", outputAlias: "ERAB_AbnormRel_QCI2", matchAlias: "ERAB_AbnormRel_QCI2"},
	{metricPath: "C000010247", outputAlias: "ERAB_AbnormRel_QCI3", matchAlias: "ERAB_AbnormRel_QCI3"},
	{metricPath: "C000010248", outputAlias: "ERAB_AbnormRel_QCI4", matchAlias: "ERAB_AbnormRel_QCI4"},
	{metricPath: "C000010249", outputAlias: "ERAB_AbnormRel_QCI5", matchAlias: "ERAB_AbnormRel_QCI5"},
	{metricPath: "C000010250", outputAlias: "ERAB_AbnormRel_QCI6", matchAlias: "ERAB_AbnormRel_QCI6"},
	{metricPath: "C000010251", outputAlias: "ERAB_AbnormRel_QCI7", matchAlias: "ERAB_AbnormRel_QCI7"},
	{metricPath: "C000010252", outputAlias: "ERAB_AbnormRel_QCI8", matchAlias: "ERAB_AbnormRel_QCI8"},
	{metricPath: "C000010253", outputAlias: "ERAB_AbnormRel_QCI9", matchAlias: "ERAB_AbnormRel_QCI9"},
	{metricPath: "C000010145", outputAlias: "ERAB_NormRel", matchAlias: "ERAB_NormRel"},
	{metricPath: "C000010146", outputAlias: "ERAB_NormRel_QCI1", matchAlias: "ERAB_NormRel_QCI1"},
	{metricPath: "C000010147", outputAlias: "ERAB_NormRel_QCI2", matchAlias: "ERAB_NormRel_QCI2"},
	{metricPath: "C000010148", outputAlias: "ERAB_NormRel_QCI3", matchAlias: "ERAB_NormRel_QCI3"},
	{metricPath: "C000010149", outputAlias: "ERAB_NormRel_QCI4", matchAlias: "ERAB_NormRel_QCI4"},
	{metricPath: "C000010150", outputAlias: "ERAB_NormRel_QCI5", matchAlias: "ERAB_NormRel_QCI5"},
	{metricPath: "C000010151", outputAlias: "ERAB_NormRel_QCI6", matchAlias: "ERAB_NormRel_QCI6"},
	{metricPath: "C000010152", outputAlias: "ERAB_NormRel_QCI7", matchAlias: "ERAB_NormRel_QCI7"},
	{metricPath: "C000010153", outputAlias: "ERAB_NormRel_QCI8", matchAlias: "ERAB_NormRel_QCI8"},
	{metricPath: "C000010154", outputAlias: "ERAB_NormRel_QCI9", matchAlias: "ERAB_NormRel_QCI9"},
	{metricPath: "C000060194", outputAlias: "PDCP_ThrpTimeUl_QCI9", matchAlias: "PDCP_ThrpTimeUl_QCI9"},
	{metricPath: "C000060195", outputAlias: "PDCP_ThrpTimeDl_QCI9", matchAlias: "PDCP_ThrpTimeDl_QCI9"},
	{metricPath: "C000080080", outputAlias: "PDCP_TailTimeUl_QCI1", matchAlias: "PDCP_TailTimeUl_QCI1"},
	{metricPath: "C000080081", outputAlias: "PDCP_TailTimeUl_QCI2", matchAlias: "PDCP_TailTimeUl_QCI2"},
	{metricPath: "C000080082", outputAlias: "PDCP_TailTimeUl_QCI3", matchAlias: "PDCP_TailTimeUl_QCI3"},
	{metricPath: "C000080083", outputAlias: "PDCP_TailTimeUl_QCI4", matchAlias: "PDCP_TailTimeUl_QCI4"},
	{metricPath: "C000080084", outputAlias: "PDCP_TailTimeUl_QCI5", matchAlias: "PDCP_TailTimeUl_QCI5"},
	{metricPath: "C000080085", outputAlias: "PDCP_TailTimeUl_QCI6", matchAlias: "PDCP_TailTimeUl_QCI6"},
	{metricPath: "C000080086", outputAlias: "PDCP_TailTimeUl_QCI7", matchAlias: "PDCP_TailTimeUl_QCI7"},
	{metricPath: "C000080087", outputAlias: "PDCP_TailTimeUl_QCI8", matchAlias: "PDCP_TailTimeUl_QCI8"},
	{metricPath: "C000080088", outputAlias: "PDCP_TailTimeUl_QCI9", matchAlias: "PDCP_TailTimeUl_QCI9"},
	{metricPath: "C000080071", outputAlias: "PDCP_TailTimeDl_QCI1", matchAlias: "PDCP_TailTimeDl_QCI1"},
	{metricPath: "C000080072", outputAlias: "PDCP_TailTimeDl_QCI2", matchAlias: "PDCP_TailTimeDl_QCI2"},
	{metricPath: "C000080073", outputAlias: "PDCP_TailTimeDl_QCI3", matchAlias: "PDCP_TailTimeDl_QCI3"},
	{metricPath: "C000080074", outputAlias: "PDCP_TailTimeDl_QCI4", matchAlias: "PDCP_TailTimeDl_QCI4"},
	{metricPath: "C000080075", outputAlias: "PDCP_TailTimeDl_QCI5", matchAlias: "PDCP_TailTimeDl_QCI5"},
	{metricPath: "C000080076", outputAlias: "PDCP_TailTimeDl_QCI6", matchAlias: "PDCP_TailTimeDl_QCI6"},
	{metricPath: "C000080077", outputAlias: "PDCP_TailTimeDl_QCI7", matchAlias: "PDCP_TailTimeDl_QCI7"},
	{metricPath: "C000080078", outputAlias: "PDCP_TailTimeDl_QCI8", matchAlias: "PDCP_TailTimeDl_QCI8"},
	{metricPath: "C000080079", outputAlias: "PDCP_TailTimeDl_QCI9", matchAlias: "PDCP_TailTimeDl_QCI9"},
	{metricPath: "C000010002", outputAlias: "ERAB_Mean_QCI1", matchAlias: "ERAB_Mean_QCI1"},
	{metricPath: "C000010003", outputAlias: "ERAB_Mean_QCI2", matchAlias: "ERAB_Mean_QCI2"},
	{metricPath: "C000010004", outputAlias: "ERAB_Mean_QCI3", matchAlias: "ERAB_Mean_QCI3"},
	{metricPath: "C000010005", outputAlias: "ERAB_Mean_QCI4", matchAlias: "ERAB_Mean_QCI4"},
	{metricPath: "C000010006", outputAlias: "ERAB_Mean_QCI5", matchAlias: "ERAB_Mean_QCI5"},
	{metricPath: "C000010007", outputAlias: "ERAB_Mean_QCI6", matchAlias: "ERAB_Mean_QCI6"},
	{metricPath: "C000010008", outputAlias: "ERAB_Mean_QCI7", matchAlias: "ERAB_Mean_QCI7"},
	{metricPath: "C000010009", outputAlias: "ERAB_Mean_QCI8", matchAlias: "ERAB_Mean_QCI8"},
	{metricPath: "C000010010", outputAlias: "ERAB_Mean_QCI9", matchAlias: "ERAB_Mean_QCI9"},
	{metricPath: "C000000019", outputAlias: "RRC_AttConnReestab", matchAlias: "RRC_AttConnReestab"},
	{metricPath: "C000000023", outputAlias: "RRC_SuccConnReestab", matchAlias: "RRC_SuccConnReestab"},
	{metricPath: "C000000021", outputAlias: "RRC_AttConReestab_HoFail", matchAlias: "RRC_AttConReestab_HoFail"},
	{metricPath: "C000000020", outputAlias: "RRC_AttConReestab_reconFail", matchAlias: "RRC_AttConReestab_reconFail"},
	{metricPath: "C000000022", outputAlias: "RRC_AttConReestab_OtherCause", matchAlias: "RRC_AttConReestab_OtherCause"},
	{metricPath: "C000030010", outputAlias: "HO_AttOutX2", matchAlias: "HO_AttOutX2"},
	{metricPath: "C000030016", outputAlias: "HO_SuccOutX2", matchAlias: "HO_SuccOutX2"},
	{metricPath: "C000030001", outputAlias: "HO_AttOutS1", matchAlias: "HO_AttOutS1"},
	{metricPath: "C000030007", outputAlias: "HO_SuccOutS1", matchAlias: "HO_SuccOutS1"},
	{metricPath: "C000030036", outputAlias: "HO_AttOutIntraFreq", matchAlias: "HO_AttOutIntraFreq"},
	{metricPath: "C000030037", outputAlias: "HO_SuccOutIntraFreq", matchAlias: "HO_SuccOutIntraFreq"},
	{metricPath: "C000030048", outputAlias: "HO_AttOutLTETo3G", matchAlias: "HO_AttOutLTETo3G"},
	{metricPath: "C000030018", outputAlias: "HO_AvgDuration_X2", matchAlias: "HO_AvgDuration_X2"},
	{metricPath: "C000030009", outputAlias: "HO_AvgDuration_S1", matchAlias: "HO_AvgDuration_S1"},
	{metricPath: "C000030020", outputAlias: "HO_Fail_TimeOut", matchAlias: "HO_Fail_TimeOut"},
	{metricPath: "C000060042", outputAlias: "PDCP_SduPktUl_QCI1", matchAlias: "PDCP_SduPktUl_QCI1"},
	{metricPath: "C000060043", outputAlias: "PDCP_SduPktUl_QCI2", matchAlias: "PDCP_SduPktUl_QCI2"},
	{metricPath: "C000060044", outputAlias: "PDCP_SduPktUl_QCI3", matchAlias: "PDCP_SduPktUl_QCI3"},
	{metricPath: "C000060045", outputAlias: "PDCP_SduPktUl_QCI4", matchAlias: "PDCP_SduPktUl_QCI4"},
	{metricPath: "C000060046", outputAlias: "PDCP_SduPktUl_QCI5", matchAlias: "PDCP_SduPktUl_QCI5"},
	{metricPath: "C000060047", outputAlias: "PDCP_SduPktUl_QCI6", matchAlias: "PDCP_SduPktUl_QCI6"},
	{metricPath: "C000060048", outputAlias: "PDCP_SduPktUl_QCI7", matchAlias: "PDCP_SduPktUl_QCI7"},
	{metricPath: "C000060049", outputAlias: "PDCP_SduPktUl_QCI8", matchAlias: "PDCP_SduPktUl_QCI8"},
	{metricPath: "C000060050", outputAlias: "PDCP_SduPktUl_QCI9", matchAlias: "PDCP_SduPktUl_QCI9"},
	{metricPath: "C000060072", outputAlias: "PDCP_SduPktDl_QCI1", matchAlias: "PDCP_SduPktDl_QCI1"},
	{metricPath: "C000060073", outputAlias: "PDCP_SduPktDl_QCI2", matchAlias: "PDCP_SduPktDl_QCI2"},
	{metricPath: "C000060074", outputAlias: "PDCP_SduPktDl_QCI3", matchAlias: "PDCP_SduPktDl_QCI3"},
	{metricPath: "C000060075", outputAlias: "PDCP_SduPktDl_QCI4", matchAlias: "PDCP_SduPktDl_QCI4"},
	{metricPath: "C000060076", outputAlias: "PDCP_SduPktDl_QCI5", matchAlias: "PDCP_SduPktDl_QCI5"},
	{metricPath: "C000060077", outputAlias: "PDCP_SduPktDl_QCI6", matchAlias: "PDCP_SduPktDl_QCI6"},
	{metricPath: "C000060078", outputAlias: "PDCP_SduPktDl_QCI7", matchAlias: "PDCP_SduPktDl_QCI7"},
	{metricPath: "C000060079", outputAlias: "PDCP_SduPktDl_QCI8", matchAlias: "PDCP_SduPktDl_QCI8"},
	{metricPath: "C000060080", outputAlias: "PDCP_SduPktDl_QCI9", matchAlias: "PDCP_SduPktDl_QCI9"},
	{metricPath: "C000060185", outputAlias: "PDCP_SduTailFlowUl_QCI1", matchAlias: "PDCP_SduTailFlowUl_QCI1"},
	{metricPath: "C000060186", outputAlias: "PDCP_SduTailFlowUl_QCI2", matchAlias: "PDCP_SduTailFlowUl_QCI2"},
	{metricPath: "C000060187", outputAlias: "PDCP_SduTailFlowUl_QCI3", matchAlias: "PDCP_SduTailFlowUl_QCI3"},
	{metricPath: "C000060188", outputAlias: "PDCP_SduTailFlowUl_QCI4", matchAlias: "PDCP_SduTailFlowUl_QCI4"},
	{metricPath: "C000060189", outputAlias: "PDCP_SduTailFlowUl_QCI5", matchAlias: "PDCP_SduTailFlowUl_QCI5"},
	{metricPath: "C000060190", outputAlias: "PDCP_SduTailFlowUl_QCI6", matchAlias: "PDCP_SduTailFlowUl_QCI6"},
	{metricPath: "C000060191", outputAlias: "PDCP_SduTailFlowUl_QCI7", matchAlias: "PDCP_SduTailFlowUl_QCI7"},
	{metricPath: "C000060192", outputAlias: "PDCP_SduTailFlowUl_QCI8", matchAlias: "PDCP_SduTailFlowUl_QCI8"},
	{metricPath: "C000060193", outputAlias: "PDCP_SduTailFlowUl_QCI9", matchAlias: "PDCP_SduTailFlowUl_QCI9"},
	{metricPath: "C000060176", outputAlias: "PDCP_SduTailFlowDl_QCI1", matchAlias: "PDCP_SduTailFlowDl_QCI1"},
	{metricPath: "C000060177", outputAlias: "PDCP_SduTailFlowDl_QCI2", matchAlias: "PDCP_SduTailFlowDl_QCI2"},
	{metricPath: "C000060178", outputAlias: "PDCP_SduTailFlowDl_QCI3", matchAlias: "PDCP_SduTailFlowDl_QCI3"},
	{metricPath: "C000060179", outputAlias: "PDCP_SduTailFlowDl_QCI4", matchAlias: "PDCP_SduTailFlowDl_QCI4"},
	{metricPath: "C000060180", outputAlias: "PDCP_SduTailFlowDl_QCI5", matchAlias: "PDCP_SduTailFlowDl_QCI5"},
	{metricPath: "C000060181", outputAlias: "PDCP_SduTailFlowDl_QCI6", matchAlias: "PDCP_SduTailFlowDl_QCI6"},
	{metricPath: "C000060182", outputAlias: "PDCP_SduTailFlowDl_QCI7", matchAlias: "PDCP_SduTailFlowDl_QCI7"},
	{metricPath: "C000060183", outputAlias: "PDCP_SduTailFlowDl_QCI8", matchAlias: "PDCP_SduTailFlowDl_QCI8"},
	{metricPath: "C000060184", outputAlias: "PDCP_SduTailFlowDl_QCI9", matchAlias: "PDCP_SduTailFlowDl_QCI9"},
	{metricPath: "C000060051", outputAlias: "PDCP_SduLossPktUl", matchAlias: "PDCP_SduLossPktUl"},
	{metricPath: "C000060052", outputAlias: "PDCP_SduLossPktUl_QCI1", matchAlias: "PDCP_SduLossPktUl_QCI1"},
	{metricPath: "C000060053", outputAlias: "PDCP_SduLossPktUl_QCI2", matchAlias: "PDCP_SduLossPktUl_QCI2"},
	{metricPath: "C000060054", outputAlias: "PDCP_SduLossPktUl_QCI3", matchAlias: "PDCP_SduLossPktUl_QCI3"},
	{metricPath: "C000060055", outputAlias: "PDCP_SduLossPktUl_QCI4", matchAlias: "PDCP_SduLossPktUl_QCI4"},
	{metricPath: "C000060056", outputAlias: "PDCP_SduLossPktUl_QCI5", matchAlias: "PDCP_SduLossPktUl_QCI5"},
	{metricPath: "C000060057", outputAlias: "PDCP_SduLossPktUl_QCI6", matchAlias: "PDCP_SduLossPktUl_QCI6"},
	{metricPath: "C000060058", outputAlias: "PDCP_SduLossPktUl_QCI7", matchAlias: "PDCP_SduLossPktUl_QCI7"},
	{metricPath: "C000060059", outputAlias: "PDCP_SduLossPktUl_QCI8", matchAlias: "PDCP_SduLossPktUl_QCI8"},
	{metricPath: "C000060060", outputAlias: "PDCP_SduLossPktUl_QCI9", matchAlias: "PDCP_SduLossPktUl_QCI9"},
	{metricPath: "C000060081", outputAlias: "PDCP_SduLossPktDl", matchAlias: "PDCP_SduLossPktDl"},
	{metricPath: "C000060082", outputAlias: "PDCP_SduLossPktDl_QCI1", matchAlias: "PDCP_SduLossPktDl_QCI1"},
	{metricPath: "C000060083", outputAlias: "PDCP_SduLossPktDl_QCI2", matchAlias: "PDCP_SduLossPktDl_QCI2"},
	{metricPath: "C000060084", outputAlias: "PDCP_SduLossPktDl_QCI3", matchAlias: "PDCP_SduLossPktDl_QCI3"},
	{metricPath: "C000060085", outputAlias: "PDCP_SduLossPktDl_QCI4", matchAlias: "PDCP_SduLossPktDl_QCI4"},
	{metricPath: "C000060086", outputAlias: "PDCP_SduLossPktDl_QCI5", matchAlias: "PDCP_SduLossPktDl_QCI5"},
	{metricPath: "C000060087", outputAlias: "PDCP_SduLossPktDl_QCI6", matchAlias: "PDCP_SduLossPktDl_QCI6"},
	{metricPath: "C000060088", outputAlias: "PDCP_SduLossPktDl_QCI7", matchAlias: "PDCP_SduLossPktDl_QCI7"},
	{metricPath: "C000060089", outputAlias: "PDCP_SduLossPktDl_QCI8", matchAlias: "PDCP_SduLossPktDl_QCI8"},
	{metricPath: "C000060090", outputAlias: "PDCP_SduLossPktDl_QCI9", matchAlias: "PDCP_SduLossPktDl_QCI9"},
	{metricPath: "C000060120", outputAlias: "PDCP_SduDiscardPktDl", matchAlias: "PDCP_SduDiscardPktDl"},
	{metricPath: "C000060121", outputAlias: "PDCP_SduDiscardPktDl_QCI1", matchAlias: "PDCP_SduDiscardPktDl_QCI1"},
	{metricPath: "C000060122", outputAlias: "PDCP_SduDiscardPktDl_QCI2", matchAlias: "PDCP_SduDiscardPktDl_QCI2"},
	{metricPath: "C000060123", outputAlias: "PDCP_SduDiscardPktDl_QCI3", matchAlias: "PDCP_SduDiscardPktDl_QCI3"},
	{metricPath: "C000060124", outputAlias: "PDCP_SduDiscardPktDl_QCI4", matchAlias: "PDCP_SduDiscardPktDl_QCI4"},
	{metricPath: "C000060125", outputAlias: "PDCP_SduDiscardPktDl_QCI5", matchAlias: "PDCP_SduDiscardPktDl_QCI5"},
	{metricPath: "C000060126", outputAlias: "PDCP_SduDiscardPktDl_QCI6", matchAlias: "PDCP_SduDiscardPktDl_QCI6"},
	{metricPath: "C000060127", outputAlias: "PDCP_SduDiscardPktDl_QCI7", matchAlias: "PDCP_SduDiscardPktDl_QCI7"},
	{metricPath: "C000060128", outputAlias: "PDCP_SduDiscardPktDl_QCI8", matchAlias: "PDCP_SduDiscardPktDl_QCI8"},
	{metricPath: "C000060129", outputAlias: "PDCP_SduDiscardPktDl_QCI9", matchAlias: "PDCP_SduDiscardPktDl_QCI9"},
	{metricPath: "C000060101", outputAlias: "PDCP_SduTotDelayDl", matchAlias: "PDCP_SduTotDelayDl"},
	{metricPath: "C000060102", outputAlias: "PDCP_SduTotDelayDl_QCI1", matchAlias: "PDCP_SduTotDelayDl_QCI1"},
	{metricPath: "C000060103", outputAlias: "PDCP_SduTotDelayDl_QCI2", matchAlias: "PDCP_SduTotDelayDl_QCI2"},
	{metricPath: "C000060104", outputAlias: "PDCP_SduTotDelayDl_QCI3", matchAlias: "PDCP_SduTotDelayDl_QCI3"},
	{metricPath: "C000060105", outputAlias: "PDCP_SduTotDelayDl_QCI4", matchAlias: "PDCP_SduTotDelayDl_QCI4"},
	{metricPath: "C000060106", outputAlias: "PDCP_SduTotDelayDl_QCI5", matchAlias: "PDCP_SduTotDelayDl_QCI5"},
	{metricPath: "C000060107", outputAlias: "PDCP_SduTotDelayDl_QCI6", matchAlias: "PDCP_SduTotDelayDl_QCI6"},
	{metricPath: "C000060108", outputAlias: "PDCP_SduTotDelayDl_QCI7", matchAlias: "PDCP_SduTotDelayDl_QCI7"},
	{metricPath: "C000060109", outputAlias: "PDCP_SduTotDelayDl_QCI8", matchAlias: "PDCP_SduTotDelayDl_QCI8"},
	{metricPath: "C000060110", outputAlias: "PDCP_SduTotDelayDl_QCI9", matchAlias: "PDCP_SduTotDelayDl_QCI9"},
	{metricPath: "C000100001", outputAlias: "CQI0", matchAlias: "CQI0"},
	{metricPath: "C000100002", outputAlias: "CQI1", matchAlias: "CQI1"},
	{metricPath: "C000100003", outputAlias: "CQI2", matchAlias: "CQI2"},
	{metricPath: "C000100004", outputAlias: "CQI3", matchAlias: "CQI3"},
	{metricPath: "C000100005", outputAlias: "CQI4", matchAlias: "CQI4"},
	{metricPath: "C000100006", outputAlias: "CQI5", matchAlias: "CQI5"},
	{metricPath: "C000100007", outputAlias: "CQI6", matchAlias: "CQI6"},
	{metricPath: "C000100008", outputAlias: "CQI7", matchAlias: "CQI7"},
	{metricPath: "C000100009", outputAlias: "CQI8", matchAlias: "CQI8"},
	{metricPath: "C000100010", outputAlias: "CQI9", matchAlias: "CQI9"},
	{metricPath: "C000100011", outputAlias: "CQI10", matchAlias: "CQI10"},
	{metricPath: "C000100012", outputAlias: "CQI11", matchAlias: "CQI11"},
	{metricPath: "C000100013", outputAlias: "CQI12", matchAlias: "CQI12"},
	{metricPath: "C000100014", outputAlias: "CQI13", matchAlias: "CQI13"},
	{metricPath: "C000100015", outputAlias: "CQI14", matchAlias: "CQI14"},
	{metricPath: "C000100016", outputAlias: "CQI15", matchAlias: "CQI15"},
	{metricPath: "C000030011", outputAlias: "VlteVoice_HOAttOutX2", matchAlias: "VlteVoice_HOAttOutX2"},
	{metricPath: "C000030017", outputAlias: "VlteVoice_HOSuccOutX2", matchAlias: "VlteVoice_HOSuccOutX2"},
	{metricPath: "C000030002", outputAlias: "VlteVoice_HOAttOutS1", matchAlias: "VlteVoice_HOAttOutS1"},
	{metricPath: "C000030008", outputAlias: "VlteVoice_HOSuccOutS1", matchAlias: "VlteVoice_HOSuccOutS1"},
	{metricPath: "C000070028", outputAlias: "DRB_MaxThpDlUe", matchAlias: "DRB_MaxThpDlUe"},
	{metricPath: "C000070029", outputAlias: "DRB_MaxThpUlUe", matchAlias: "DRB_MaxThpUlUe"},
}

var legacyS0003PCMetrics = []legacyPMMetricSeed{
	{metricPath: "C000080030", outputAlias: "PRACH_NonPreDetected", matchAlias: "PRACH_NonPreDetected"},
	{metricPath: "C000000004", outputAlias: "RRC_UserConnMax", matchAlias: "RRC_UserConnMax"},
	{metricPath: "C000000003", outputAlias: "RRC_UserConnMean", matchAlias: "RRC_UserConnMean"},
	{metricPath: "C000070019", outputAlias: "Traffic_ActUserUl", matchAlias: "Traffic_ActUserUl"},
	{metricPath: "C000070001", outputAlias: "Traffic_ActUserUl_QCI1", matchAlias: "Traffic_ActUserUl_QCI1"},
	{metricPath: "C000070002", outputAlias: "Traffic_ActUserUl_QCI2", matchAlias: "Traffic_ActUserUl_QCI2"},
	{metricPath: "C000070003", outputAlias: "Traffic_ActUserUl_QCI3", matchAlias: "Traffic_ActUserUl_QCI3"},
	{metricPath: "C000070004", outputAlias: "Traffic_ActUserUl_QCI4", matchAlias: "Traffic_ActUserUl_QCI4"},
	{metricPath: "C000070005", outputAlias: "Traffic_ActUserUl_QCI5", matchAlias: "Traffic_ActUserUl_QCI5"},
	{metricPath: "C000070006", outputAlias: "Traffic_ActUserUl_QCI6", matchAlias: "Traffic_ActUserUl_QCI6"},
	{metricPath: "C000070007", outputAlias: "Traffic_ActUserUl_QCI7", matchAlias: "Traffic_ActUserUl_QCI7"},
	{metricPath: "C000070008", outputAlias: "Traffic_ActUserUl_QCI8", matchAlias: "Traffic_ActUserUl_QCI8"},
	{metricPath: "C000070009", outputAlias: "Traffic_ActUserUl_QCI9", matchAlias: "Traffic_ActUserUl_QCI9"},
	{metricPath: "C000070020", outputAlias: "Traffic_ActUserDl", matchAlias: "Traffic_ActUserDl"},
	{metricPath: "C000070010", outputAlias: "Traffic_ActUserDl_QCI1", matchAlias: "Traffic_ActUserDl_QCI1"},
	{metricPath: "C000070011", outputAlias: "Traffic_ActUserDl_QCI2", matchAlias: "Traffic_ActUserDl_QCI2"},
	{metricPath: "C000070012", outputAlias: "Traffic_ActUserDl_QCI3", matchAlias: "Traffic_ActUserDl_QCI3"},
	{metricPath: "C000070013", outputAlias: "Traffic_ActUserDl_QCI4", matchAlias: "Traffic_ActUserDl_QCI4"},
	{metricPath: "C000070014", outputAlias: "Traffic_ActUserDl_QCI5", matchAlias: "Traffic_ActUserDl_QCI5"},
	{metricPath: "C000070015", outputAlias: "Traffic_ActUserDl_QCI6", matchAlias: "Traffic_ActUserDl_QCI6"},
	{metricPath: "C000070016", outputAlias: "Traffic_ActUserDl_QCI7", matchAlias: "Traffic_ActUserDl_QCI7"},
	{metricPath: "C000070017", outputAlias: "Traffic_ActUserDl_QCI8", matchAlias: "Traffic_ActUserDl_QCI8"},
	{metricPath: "C000070018", outputAlias: "Traffic_ActUserDl_QCI9", matchAlias: "Traffic_ActUserDl_QCI9"},
	{metricPath: "C000070021", outputAlias: "Traffic_ActUserMean", matchAlias: "Traffic_ActUserMean"},
	{metricPath: "C000070022", outputAlias: "Traffic_ActUserUlMax", matchAlias: "Traffic_ActUserUlMax"},
	{metricPath: "C000000009", outputAlias: "RRC_AttConnEstab_UE", matchAlias: "RRC_AttConnEstab_UE"},
	{metricPath: "C000000016", outputAlias: "RRC_SuccConnEstab_UE", matchAlias: "RRC_SuccConnEstab_UE"},
	{metricPath: "C000000008", outputAlias: "RRC_AttConnEstab_Net", matchAlias: "RRC_AttConnEstab_Net"},
	{metricPath: "C000000015", outputAlias: "RRC_SuccConnEstab_Net", matchAlias: "RRC_SuccConnEstab_Net"},
	{metricPath: "C000000038", outputAlias: "RRC_FailConnEstab_OtherCause", matchAlias: "RRC_FailConnEstab_OtherCause"},
	{metricPath: "C000120001", outputAlias: "S1Sig_AttConnEstab", matchAlias: "S1Sig_AttConnEstab"},
	{metricPath: "C000120002", outputAlias: "S1Sig_SuccConnEstab", matchAlias: "S1Sig_SuccConnEstab"},
	{metricPath: "C000010070", outputAlias: "ERAB_InitAttEstab", matchAlias: "ERAB_InitAttEstab"},
	{metricPath: "C000010071", outputAlias: "ERAB_InitAttEstab_QCI1", matchAlias: "ERAB_InitAttEstab_QCI1"},
	{metricPath: "C000010072", outputAlias: "ERAB_InitAttEstab_QCI2", matchAlias: "ERAB_InitAttEstab_QCI2"},
	{metricPath: "C000010073", outputAlias: "ERAB_InitAttEstab_QCI3", matchAlias: "ERAB_InitAttEstab_QCI3"},
	{metricPath: "C000010074", outputAlias: "ERAB_InitAttEstab_QCI4", matchAlias: "ERAB_InitAttEstab_QCI4"},
	{metricPath: "C000010075", outputAlias: "ERAB_InitAttEstab_QCI5", matchAlias: "ERAB_InitAttEstab_QCI5"},
	{metricPath: "C000010076", outputAlias: "ERAB_InitAttEstab_QCI6", matchAlias: "ERAB_InitAttEstab_QCI6"},
	{metricPath: "C000010077", outputAlias: "ERAB_InitAttEstab_QCI7", matchAlias: "ERAB_InitAttEstab_QCI7"},
	{metricPath: "C000010078", outputAlias: "ERAB_InitAttEstab_QCI8", matchAlias: "ERAB_InitAttEstab_QCI8"},
	{metricPath: "C000010079", outputAlias: "ERAB_InitAttEstab_QCI9", matchAlias: "ERAB_InitAttEstab_QCI9"},
	{metricPath: "C000010080", outputAlias: "ERAB_InitSuccEstab", matchAlias: "ERAB_InitSuccEstab"},
	{metricPath: "C000010081", outputAlias: "ERAB_InitSuccEstab_QCI1", matchAlias: "ERAB_InitSuccEstab_QCI1"},
	{metricPath: "C000010082", outputAlias: "ERAB_InitSuccEstab_QCI2", matchAlias: "ERAB_InitSuccEstab_QCI2"},
	{metricPath: "C000010083", outputAlias: "ERAB_InitSuccEstab_QCI3", matchAlias: "ERAB_InitSuccEstab_QCI3"},
	{metricPath: "C000010084", outputAlias: "ERAB_InitSuccEstab_QCI4", matchAlias: "ERAB_InitSuccEstab_QCI4"},
	{metricPath: "C000010085", outputAlias: "ERAB_InitSuccEstab_QCI5", matchAlias: "ERAB_InitSuccEstab_QCI5"},
	{metricPath: "C000010086", outputAlias: "ERAB_InitSuccEstab_QCI6", matchAlias: "ERAB_InitSuccEstab_QCI6"},
	{metricPath: "C000010087", outputAlias: "ERAB_InitSuccEstab_QCI7", matchAlias: "ERAB_InitSuccEstab_QCI7"},
	{metricPath: "C000010088", outputAlias: "ERAB_InitSuccEstab_QCI8", matchAlias: "ERAB_InitSuccEstab_QCI8"},
	{metricPath: "C000010089", outputAlias: "ERAB_InitSuccEstab_QCI9", matchAlias: "ERAB_InitSuccEstab_QCI9"},
	{metricPath: "C000010106", outputAlias: "ERAB_AddAttEstab", matchAlias: "ERAB_AddAttEstab"},
	{metricPath: "C000010097", outputAlias: "ERAB_AddAttEstab_QCI1", matchAlias: "ERAB_AddAttEstab_QCI1"},
	{metricPath: "C000010098", outputAlias: "ERAB_AddAttEstab_QCI2", matchAlias: "ERAB_AddAttEstab_QCI2"},
	{metricPath: "C000010099", outputAlias: "ERAB_AddAttEstab_QCI3", matchAlias: "ERAB_AddAttEstab_QCI3"},
	{metricPath: "C000010100", outputAlias: "ERAB_AddAttEstab_QCI4", matchAlias: "ERAB_AddAttEstab_QCI4"},
	{metricPath: "C000010101", outputAlias: "ERAB_AddAttEstab_QCI5", matchAlias: "ERAB_AddAttEstab_QCI5"},
	{metricPath: "C000010102", outputAlias: "ERAB_AddAttEstab_QCI6", matchAlias: "ERAB_AddAttEstab_QCI6"},
	{metricPath: "C000010103", outputAlias: "ERAB_AddAttEstab_QCI7", matchAlias: "ERAB_AddAttEstab_QCI7"},
	{metricPath: "C000010104", outputAlias: "ERAB_AddAttEstab_QCI8", matchAlias: "ERAB_AddAttEstab_QCI8"},
	{metricPath: "C000010105", outputAlias: "ERAB_AddAttEstab_QCI9", matchAlias: "ERAB_AddAttEstab_QCI9"},
	{metricPath: "C000010116", outputAlias: "ERAB_AddSuccEstab", matchAlias: "ERAB_AddSuccEstab"},
	{metricPath: "C000010107", outputAlias: "ERAB_AddSuccEstab_QCI1", matchAlias: "ERAB_AddSuccEstab_QCI1"},
	{metricPath: "C000010108", outputAlias: "ERAB_AddSuccEstab_QCI2", matchAlias: "ERAB_AddSuccEstab_QCI2"},
	{metricPath: "C000010109", outputAlias: "ERAB_AddSuccEstab_QCI3", matchAlias: "ERAB_AddSuccEstab_QCI3"},
	{metricPath: "C000010110", outputAlias: "ERAB_AddSuccEstab_QCI4", matchAlias: "ERAB_AddSuccEstab_QCI4"},
	{metricPath: "C000010111", outputAlias: "ERAB_AddSuccEstab_QCI5", matchAlias: "ERAB_AddSuccEstab_QCI5"},
	{metricPath: "C000010112", outputAlias: "ERAB_AddSuccEstab_QCI6", matchAlias: "ERAB_AddSuccEstab_QCI6"},
	{metricPath: "C000010113", outputAlias: "ERAB_AddSuccEstab_QCI7", matchAlias: "ERAB_AddSuccEstab_QCI7"},
	{metricPath: "C000010114", outputAlias: "ERAB_AddSuccEstab_QCI8", matchAlias: "ERAB_AddSuccEstab_QCI8"},
	{metricPath: "C000010115", outputAlias: "ERAB_AddSuccEstab_QCI9", matchAlias: "ERAB_AddSuccEstab_QCI9"},
	{metricPath: "C000050001", outputAlias: "Paging_S1_Rx", matchAlias: "Paging_S1_Rx"},
	{metricPath: "C000050002", outputAlias: "Paging_Discard_Num", matchAlias: "Paging_Discard_Num"},
	{metricPath: "C000010122", outputAlias: "ERAB_FailEstab_UeNoReply", matchAlias: "ERAB_FailEstab_UeNoReply"},
	{metricPath: "C000010123", outputAlias: "ERAB_FailEstab_TNL", matchAlias: "ERAB_FailEstab_TNL"},
	{metricPath: "C000010119", outputAlias: "ERAB_FailEstab_RNL", matchAlias: "ERAB_FailEstab_RNL"},
	{metricPath: "C000010120", outputAlias: "ERAB_FailEstab_NoRadioRes", matchAlias: "ERAB_FailEstab_NoRadioRes"},
	{metricPath: "C000020021", outputAlias: "UECNTX_AbnormRel", matchAlias: "UECNTX_AbnormRel"},
	{metricPath: "C000020015", outputAlias: "UECNTX_NormRel", matchAlias: "UECNTX_NormRel"},
	{metricPath: "C000010245", outputAlias: "ERAB_AbnormRel_QCI1", matchAlias: "ERAB_AbnormRel_QCI1"},
	{metricPath: "C000010246", outputAlias: "ERAB_AbnormRel_QCI2", matchAlias: "ERAB_AbnormRel_QCI2"},
	{metricPath: "C000010247", outputAlias: "ERAB_AbnormRel_QCI3", matchAlias: "ERAB_AbnormRel_QCI3"},
	{metricPath: "C000010248", outputAlias: "ERAB_AbnormRel_QCI4", matchAlias: "ERAB_AbnormRel_QCI4"},
	{metricPath: "C000010249", outputAlias: "ERAB_AbnormRel_QCI5", matchAlias: "ERAB_AbnormRel_QCI5"},
	{metricPath: "C000010250", outputAlias: "ERAB_AbnormRel_QCI6", matchAlias: "ERAB_AbnormRel_QCI6"},
	{metricPath: "C000010251", outputAlias: "ERAB_AbnormRel_QCI7", matchAlias: "ERAB_AbnormRel_QCI7"},
	{metricPath: "C000010252", outputAlias: "ERAB_AbnormRel_QCI8", matchAlias: "ERAB_AbnormRel_QCI8"},
	{metricPath: "C000010253", outputAlias: "ERAB_AbnormRel_QCI9", matchAlias: "ERAB_AbnormRel_QCI9"},
	{metricPath: "C000010145", outputAlias: "ERAB_NormRel", matchAlias: "ERAB_NormRel"},
	{metricPath: "C000010146", outputAlias: "ERAB_NormRel_QCI1", matchAlias: "ERAB_NormRel_QCI1"},
	{metricPath: "C000010147", outputAlias: "ERAB_NormRel_QCI2", matchAlias: "ERAB_NormRel_QCI2"},
	{metricPath: "C000010148", outputAlias: "ERAB_NormRel_QCI3", matchAlias: "ERAB_NormRel_QCI3"},
	{metricPath: "C000010149", outputAlias: "ERAB_NormRel_QCI4", matchAlias: "ERAB_NormRel_QCI4"},
	{metricPath: "C000010150", outputAlias: "ERAB_NormRel_QCI5", matchAlias: "ERAB_NormRel_QCI5"},
	{metricPath: "C000010151", outputAlias: "ERAB_NormRel_QCI6", matchAlias: "ERAB_NormRel_QCI6"},
	{metricPath: "C000010152", outputAlias: "ERAB_NormRel_QCI7", matchAlias: "ERAB_NormRel_QCI7"},
	{metricPath: "C000010153", outputAlias: "ERAB_NormRel_QCI8", matchAlias: "ERAB_NormRel_QCI8"},
	{metricPath: "C000010154", outputAlias: "ERAB_NormRel_QCI9", matchAlias: "ERAB_NormRel_QCI9"},
	{metricPath: "C000060194", outputAlias: "PDCP_ThrpTimeUl_QCI9", matchAlias: "PDCP_ThrpTimeUl_QCI9"},
	{metricPath: "C000060195", outputAlias: "PDCP_ThrpTimeDl_QCI9", matchAlias: "PDCP_ThrpTimeDl_QCI9"},
	{metricPath: "C000080080", outputAlias: "PDCP_TailTimeUl_QCI1", matchAlias: "PDCP_TailTimeUl_QCI1"},
	{metricPath: "C000080081", outputAlias: "PDCP_TailTimeUl_QCI2", matchAlias: "PDCP_TailTimeUl_QCI2"},
	{metricPath: "C000080082", outputAlias: "PDCP_TailTimeUl_QCI3", matchAlias: "PDCP_TailTimeUl_QCI3"},
	{metricPath: "C000080083", outputAlias: "PDCP_TailTimeUl_QCI4", matchAlias: "PDCP_TailTimeUl_QCI4"},
	{metricPath: "C000080084", outputAlias: "PDCP_TailTimeUl_QCI5", matchAlias: "PDCP_TailTimeUl_QCI5"},
	{metricPath: "C000080085", outputAlias: "PDCP_TailTimeUl_QCI6", matchAlias: "PDCP_TailTimeUl_QCI6"},
	{metricPath: "C000080086", outputAlias: "PDCP_TailTimeUl_QCI7", matchAlias: "PDCP_TailTimeUl_QCI7"},
	{metricPath: "C000080087", outputAlias: "PDCP_TailTimeUl_QCI8", matchAlias: "PDCP_TailTimeUl_QCI8"},
	{metricPath: "C000080088", outputAlias: "PDCP_TailTimeUl_QCI9", matchAlias: "PDCP_TailTimeUl_QCI9"},
	{metricPath: "C000080071", outputAlias: "PDCP_TailTimeDl_QCI1", matchAlias: "PDCP_TailTimeDl_QCI1"},
	{metricPath: "C000080072", outputAlias: "PDCP_TailTimeDl_QCI2", matchAlias: "PDCP_TailTimeDl_QCI2"},
	{metricPath: "C000080073", outputAlias: "PDCP_TailTimeDl_QCI3", matchAlias: "PDCP_TailTimeDl_QCI3"},
	{metricPath: "C000080074", outputAlias: "PDCP_TailTimeDl_QCI4", matchAlias: "PDCP_TailTimeDl_QCI4"},
	{metricPath: "C000080075", outputAlias: "PDCP_TailTimeDl_QCI5", matchAlias: "PDCP_TailTimeDl_QCI5"},
	{metricPath: "C000080076", outputAlias: "PDCP_TailTimeDl_QCI6", matchAlias: "PDCP_TailTimeDl_QCI6"},
	{metricPath: "C000080077", outputAlias: "PDCP_TailTimeDl_QCI7", matchAlias: "PDCP_TailTimeDl_QCI7"},
	{metricPath: "C000080078", outputAlias: "PDCP_TailTimeDl_QCI8", matchAlias: "PDCP_TailTimeDl_QCI8"},
	{metricPath: "C000080079", outputAlias: "PDCP_TailTimeDl_QCI9", matchAlias: "PDCP_TailTimeDl_QCI9"},
	{metricPath: "C000010002", outputAlias: "ERAB_Mean_QCI1", matchAlias: "ERAB_Mean_QCI1"},
	{metricPath: "C000010003", outputAlias: "ERAB_Mean_QCI2", matchAlias: "ERAB_Mean_QCI2"},
	{metricPath: "C000010004", outputAlias: "ERAB_Mean_QCI3", matchAlias: "ERAB_Mean_QCI3"},
	{metricPath: "C000010005", outputAlias: "ERAB_Mean_QCI4", matchAlias: "ERAB_Mean_QCI4"},
	{metricPath: "C000010006", outputAlias: "ERAB_Mean_QCI5", matchAlias: "ERAB_Mean_QCI5"},
	{metricPath: "C000010007", outputAlias: "ERAB_Mean_QCI6", matchAlias: "ERAB_Mean_QCI6"},
	{metricPath: "C000010008", outputAlias: "ERAB_Mean_QCI7", matchAlias: "ERAB_Mean_QCI7"},
	{metricPath: "C000010009", outputAlias: "ERAB_Mean_QCI8", matchAlias: "ERAB_Mean_QCI8"},
	{metricPath: "C000010010", outputAlias: "ERAB_Mean_QCI9", matchAlias: "ERAB_Mean_QCI9"},
	{metricPath: "C000000019", outputAlias: "RRC_AttConnReestab", matchAlias: "RRC_AttConnReestab"},
	{metricPath: "C000000023", outputAlias: "RRC_SuccConnReestab", matchAlias: "RRC_SuccConnReestab"},
	{metricPath: "C000000021", outputAlias: "RRC_AttConReestab_HoFail", matchAlias: "RRC_AttConReestab_HoFail"},
	{metricPath: "C000000020", outputAlias: "RRC_AttConReestab_reconFail", matchAlias: "RRC_AttConReestab_reconFail"},
	{metricPath: "C000000022", outputAlias: "RRC_AttConReestab_OtherCause", matchAlias: "RRC_AttConReestab_OtherCause"},
	{metricPath: "C000030010", outputAlias: "HO_AttOutX2", matchAlias: "HO_AttOutX2"},
	{metricPath: "C000030016", outputAlias: "HO_SuccOutX2", matchAlias: "HO_SuccOutX2"},
	{metricPath: "C000030001", outputAlias: "HO_AttOutS1", matchAlias: "HO_AttOutS1"},
	{metricPath: "C000030007", outputAlias: "HO_SuccOutS1", matchAlias: "HO_SuccOutS1"},
	{metricPath: "C000030036", outputAlias: "HO_AttOutIntraFreq", matchAlias: "HO_AttOutIntraFreq"},
	{metricPath: "C000030037", outputAlias: "HO_SuccOutIntraFreq", matchAlias: "HO_SuccOutIntraFreq"},
	{metricPath: "C000030048", outputAlias: "HO_AttOutLTETo3G", matchAlias: "HO_AttOutLTETo3G"},
	{metricPath: "C000030018", outputAlias: "HO_AvgDuration_X2", matchAlias: "HO_AvgDuration_X2"},
	{metricPath: "C000030009", outputAlias: "HO_AvgDuration_S1", matchAlias: "HO_AvgDuration_S1"},
	{metricPath: "C000030020", outputAlias: "HO_Fail_TimeOut", matchAlias: "HO_Fail_TimeOut"},
	{metricPath: "C000060042", outputAlias: "PDCP_SduPktUl_QCI1", matchAlias: "PDCP_SduPktUl_QCI1"},
	{metricPath: "C000060043", outputAlias: "PDCP_SduPktUl_QCI2", matchAlias: "PDCP_SduPktUl_QCI2"},
	{metricPath: "C000060044", outputAlias: "PDCP_SduPktUl_QCI3", matchAlias: "PDCP_SduPktUl_QCI3"},
	{metricPath: "C000060045", outputAlias: "PDCP_SduPktUl_QCI4", matchAlias: "PDCP_SduPktUl_QCI4"},
	{metricPath: "C000060046", outputAlias: "PDCP_SduPktUl_QCI5", matchAlias: "PDCP_SduPktUl_QCI5"},
	{metricPath: "C000060047", outputAlias: "PDCP_SduPktUl_QCI6", matchAlias: "PDCP_SduPktUl_QCI6"},
	{metricPath: "C000060048", outputAlias: "PDCP_SduPktUl_QCI7", matchAlias: "PDCP_SduPktUl_QCI7"},
	{metricPath: "C000060049", outputAlias: "PDCP_SduPktUl_QCI8", matchAlias: "PDCP_SduPktUl_QCI8"},
	{metricPath: "C000060050", outputAlias: "PDCP_SduPktUl_QCI9", matchAlias: "PDCP_SduPktUl_QCI9"},
	{metricPath: "C000060072", outputAlias: "PDCP_SduPktDl_QCI1", matchAlias: "PDCP_SduPktDl_QCI1"},
	{metricPath: "C000060073", outputAlias: "PDCP_SduPktDl_QCI2", matchAlias: "PDCP_SduPktDl_QCI2"},
	{metricPath: "C000060074", outputAlias: "PDCP_SduPktDl_QCI3", matchAlias: "PDCP_SduPktDl_QCI3"},
	{metricPath: "C000060075", outputAlias: "PDCP_SduPktDl_QCI4", matchAlias: "PDCP_SduPktDl_QCI4"},
	{metricPath: "C000060076", outputAlias: "PDCP_SduPktDl_QCI5", matchAlias: "PDCP_SduPktDl_QCI5"},
	{metricPath: "C000060077", outputAlias: "PDCP_SduPktDl_QCI6", matchAlias: "PDCP_SduPktDl_QCI6"},
	{metricPath: "C000060078", outputAlias: "PDCP_SduPktDl_QCI7", matchAlias: "PDCP_SduPktDl_QCI7"},
	{metricPath: "C000060079", outputAlias: "PDCP_SduPktDl_QCI8", matchAlias: "PDCP_SduPktDl_QCI8"},
	{metricPath: "C000060080", outputAlias: "PDCP_SduPktDl_QCI9", matchAlias: "PDCP_SduPktDl_QCI9"},
	{metricPath: "C000060185", outputAlias: "PDCP_SduTailFlowUl_QCI1", matchAlias: "PDCP_SduTailFlowUl_QCI1"},
	{metricPath: "C000060186", outputAlias: "PDCP_SduTailFlowUl_QCI2", matchAlias: "PDCP_SduTailFlowUl_QCI2"},
	{metricPath: "C000060187", outputAlias: "PDCP_SduTailFlowUl_QCI3", matchAlias: "PDCP_SduTailFlowUl_QCI3"},
	{metricPath: "C000060188", outputAlias: "PDCP_SduTailFlowUl_QCI4", matchAlias: "PDCP_SduTailFlowUl_QCI4"},
	{metricPath: "C000060189", outputAlias: "PDCP_SduTailFlowUl_QCI5", matchAlias: "PDCP_SduTailFlowUl_QCI5"},
	{metricPath: "C000060190", outputAlias: "PDCP_SduTailFlowUl_QCI6", matchAlias: "PDCP_SduTailFlowUl_QCI6"},
	{metricPath: "C000060191", outputAlias: "PDCP_SduTailFlowUl_QCI7", matchAlias: "PDCP_SduTailFlowUl_QCI7"},
	{metricPath: "C000060192", outputAlias: "PDCP_SduTailFlowUl_QCI8", matchAlias: "PDCP_SduTailFlowUl_QCI8"},
	{metricPath: "C000060193", outputAlias: "PDCP_SduTailFlowUl_QCI9", matchAlias: "PDCP_SduTailFlowUl_QCI9"},
	{metricPath: "C000060176", outputAlias: "PDCP_SduTailFlowDl_QCI1", matchAlias: "PDCP_SduTailFlowDl_QCI1"},
	{metricPath: "C000060177", outputAlias: "PDCP_SduTailFlowDl_QCI2", matchAlias: "PDCP_SduTailFlowDl_QCI2"},
	{metricPath: "C000060178", outputAlias: "PDCP_SduTailFlowDl_QCI3", matchAlias: "PDCP_SduTailFlowDl_QCI3"},
	{metricPath: "C000060179", outputAlias: "PDCP_SduTailFlowDl_QCI4", matchAlias: "PDCP_SduTailFlowDl_QCI4"},
	{metricPath: "C000060180", outputAlias: "PDCP_SduTailFlowDl_QCI5", matchAlias: "PDCP_SduTailFlowDl_QCI5"},
	{metricPath: "C000060181", outputAlias: "PDCP_SduTailFlowDl_QCI6", matchAlias: "PDCP_SduTailFlowDl_QCI6"},
	{metricPath: "C000060182", outputAlias: "PDCP_SduTailFlowDl_QCI7", matchAlias: "PDCP_SduTailFlowDl_QCI7"},
	{metricPath: "C000060183", outputAlias: "PDCP_SduTailFlowDl_QCI8", matchAlias: "PDCP_SduTailFlowDl_QCI8"},
	{metricPath: "C000060184", outputAlias: "PDCP_SduTailFlowDl_QCI9", matchAlias: "PDCP_SduTailFlowDl_QCI9"},
	{metricPath: "C000060051", outputAlias: "PDCP_SduLossPktUl", matchAlias: "PDCP_SduLossPktUl"},
	{metricPath: "C000060052", outputAlias: "PDCP_SduLossPktUl_QCI1", matchAlias: "PDCP_SduLossPktUl_QCI1"},
	{metricPath: "C000060053", outputAlias: "PDCP_SduLossPktUl_QCI2", matchAlias: "PDCP_SduLossPktUl_QCI2"},
	{metricPath: "C000060054", outputAlias: "PDCP_SduLossPktUl_QCI3", matchAlias: "PDCP_SduLossPktUl_QCI3"},
	{metricPath: "C000060055", outputAlias: "PDCP_SduLossPktUl_QCI4", matchAlias: "PDCP_SduLossPktUl_QCI4"},
	{metricPath: "C000060056", outputAlias: "PDCP_SduLossPktUl_QCI5", matchAlias: "PDCP_SduLossPktUl_QCI5"},
	{metricPath: "C000060057", outputAlias: "PDCP_SduLossPktUl_QCI6", matchAlias: "PDCP_SduLossPktUl_QCI6"},
	{metricPath: "C000060058", outputAlias: "PDCP_SduLossPktUl_QCI7", matchAlias: "PDCP_SduLossPktUl_QCI7"},
	{metricPath: "C000060059", outputAlias: "PDCP_SduLossPktUl_QCI8", matchAlias: "PDCP_SduLossPktUl_QCI8"},
	{metricPath: "C000060060", outputAlias: "PDCP_SduLossPktUl_QCI9", matchAlias: "PDCP_SduLossPktUl_QCI9"},
	{metricPath: "C000060081", outputAlias: "PDCP_SduLossPktDl", matchAlias: "PDCP_SduLossPktDl"},
	{metricPath: "C000060082", outputAlias: "PDCP_SduLossPktDl_QCI1", matchAlias: "PDCP_SduLossPktDl_QCI1"},
	{metricPath: "C000060083", outputAlias: "PDCP_SduLossPktDl_QCI2", matchAlias: "PDCP_SduLossPktDl_QCI2"},
	{metricPath: "C000060084", outputAlias: "PDCP_SduLossPktDl_QCI3", matchAlias: "PDCP_SduLossPktDl_QCI3"},
	{metricPath: "C000060085", outputAlias: "PDCP_SduLossPktDl_QCI4", matchAlias: "PDCP_SduLossPktDl_QCI4"},
	{metricPath: "C000060086", outputAlias: "PDCP_SduLossPktDl_QCI5", matchAlias: "PDCP_SduLossPktDl_QCI5"},
	{metricPath: "C000060087", outputAlias: "PDCP_SduLossPktDl_QCI6", matchAlias: "PDCP_SduLossPktDl_QCI6"},
	{metricPath: "C000060088", outputAlias: "PDCP_SduLossPktDl_QCI7", matchAlias: "PDCP_SduLossPktDl_QCI7"},
	{metricPath: "C000060089", outputAlias: "PDCP_SduLossPktDl_QCI8", matchAlias: "PDCP_SduLossPktDl_QCI8"},
	{metricPath: "C000060090", outputAlias: "PDCP_SduLossPktDl_QCI9", matchAlias: "PDCP_SduLossPktDl_QCI9"},
	{metricPath: "C000060120", outputAlias: "PDCP_SduDiscardPktDl", matchAlias: "PDCP_SduDiscardPktDl"},
	{metricPath: "C000060121", outputAlias: "PDCP_SduDiscardPktDl_QCI1", matchAlias: "PDCP_SduDiscardPktDl_QCI1"},
	{metricPath: "C000060122", outputAlias: "PDCP_SduDiscardPktDl_QCI2", matchAlias: "PDCP_SduDiscardPktDl_QCI2"},
	{metricPath: "C000060123", outputAlias: "PDCP_SduDiscardPktDl_QCI3", matchAlias: "PDCP_SduDiscardPktDl_QCI3"},
	{metricPath: "C000060124", outputAlias: "PDCP_SduDiscardPktDl_QCI4", matchAlias: "PDCP_SduDiscardPktDl_QCI4"},
	{metricPath: "C000060125", outputAlias: "PDCP_SduDiscardPktDl_QCI5", matchAlias: "PDCP_SduDiscardPktDl_QCI5"},
	{metricPath: "C000060126", outputAlias: "PDCP_SduDiscardPktDl_QCI6", matchAlias: "PDCP_SduDiscardPktDl_QCI6"},
	{metricPath: "C000060127", outputAlias: "PDCP_SduDiscardPktDl_QCI7", matchAlias: "PDCP_SduDiscardPktDl_QCI7"},
	{metricPath: "C000060128", outputAlias: "PDCP_SduDiscardPktDl_QCI8", matchAlias: "PDCP_SduDiscardPktDl_QCI8"},
	{metricPath: "C000060129", outputAlias: "PDCP_SduDiscardPktDl_QCI9", matchAlias: "PDCP_SduDiscardPktDl_QCI9"},
	{metricPath: "C000060101", outputAlias: "PDCP_SduTotDelayDl", matchAlias: "PDCP_SduTotDelayDl"},
	{metricPath: "C000060102", outputAlias: "PDCP_SduTotDelayDl_QCI1", matchAlias: "PDCP_SduTotDelayDl_QCI1"},
	{metricPath: "C000060103", outputAlias: "PDCP_SduTotDelayDl_QCI2", matchAlias: "PDCP_SduTotDelayDl_QCI2"},
	{metricPath: "C000060104", outputAlias: "PDCP_SduTotDelayDl_QCI3", matchAlias: "PDCP_SduTotDelayDl_QCI3"},
	{metricPath: "C000060105", outputAlias: "PDCP_SduTotDelayDl_QCI4", matchAlias: "PDCP_SduTotDelayDl_QCI4"},
	{metricPath: "C000060106", outputAlias: "PDCP_SduTotDelayDl_QCI5", matchAlias: "PDCP_SduTotDelayDl_QCI5"},
	{metricPath: "C000060107", outputAlias: "PDCP_SduTotDelayDl_QCI6", matchAlias: "PDCP_SduTotDelayDl_QCI6"},
	{metricPath: "C000060108", outputAlias: "PDCP_SduTotDelayDl_QCI7", matchAlias: "PDCP_SduTotDelayDl_QCI7"},
	{metricPath: "C000060109", outputAlias: "PDCP_SduTotDelayDl_QCI8", matchAlias: "PDCP_SduTotDelayDl_QCI8"},
	{metricPath: "C000060110", outputAlias: "PDCP_SduTotDelayDl_QCI9", matchAlias: "PDCP_SduTotDelayDl_QCI9"},
	{metricPath: "C000100002", outputAlias: "CQI1", matchAlias: "CQI1"},
	{metricPath: "C000100003", outputAlias: "CQI2", matchAlias: "CQI2"},
	{metricPath: "C000100004", outputAlias: "CQI3", matchAlias: "CQI3"},
	{metricPath: "C000100005", outputAlias: "CQI4", matchAlias: "CQI4"},
	{metricPath: "C000100006", outputAlias: "CQI5", matchAlias: "CQI5"},
	{metricPath: "C000100007", outputAlias: "CQI6", matchAlias: "CQI6"},
	{metricPath: "C000100008", outputAlias: "CQI7", matchAlias: "CQI7"},
	{metricPath: "C000100009", outputAlias: "CQI8", matchAlias: "CQI8"},
	{metricPath: "C000100010", outputAlias: "CQI9", matchAlias: "CQI9"},
	{metricPath: "C000100011", outputAlias: "CQI10", matchAlias: "CQI10"},
	{metricPath: "C000100012", outputAlias: "CQI11", matchAlias: "CQI11"},
	{metricPath: "C000100013", outputAlias: "CQI12", matchAlias: "CQI12"},
	{metricPath: "C000100014", outputAlias: "CQI13", matchAlias: "CQI13"},
	{metricPath: "C000100015", outputAlias: "CQI14", matchAlias: "CQI14"},
	{metricPath: "C000100016", outputAlias: "CQI15", matchAlias: "CQI15"},
	{metricPath: "C000100067", outputAlias: "PRB1_InterfNoiseV", matchAlias: "PRB1_InterfNoiseV"},
	{metricPath: "C000100068", outputAlias: "PRB2_InterfNoiseV", matchAlias: "PRB2_InterfNoiseV"},
	{metricPath: "C000100069", outputAlias: "PRB3_InterfNoiseV", matchAlias: "PRB3_InterfNoiseV"},
	{metricPath: "C000100070", outputAlias: "PRB4_InterfNoiseV", matchAlias: "PRB4_InterfNoiseV"},
	{metricPath: "C000100071", outputAlias: "PRB5_InterfNoiseV", matchAlias: "PRB5_InterfNoiseV"},
	{metricPath: "C000100072", outputAlias: "PRB6_InterfNoiseV", matchAlias: "PRB6_InterfNoiseV"},
	{metricPath: "C000100073", outputAlias: "PRB7_InterfNoiseV", matchAlias: "PRB7_InterfNoiseV"},
	{metricPath: "C000100074", outputAlias: "PRB8_InterfNoiseV", matchAlias: "PRB8_InterfNoiseV"},
	{metricPath: "C000100075", outputAlias: "PRB9_InterfNoiseV", matchAlias: "PRB9_InterfNoiseV"},
	{metricPath: "C000100076", outputAlias: "PRB10_InterfNoiseV", matchAlias: "PRB10_InterfNoiseV"},
	{metricPath: "C000100077", outputAlias: "PRB11_InterfNoiseV", matchAlias: "PRB11_InterfNoiseV"},
	{metricPath: "C000100078", outputAlias: "PRB12_InterfNoiseV", matchAlias: "PRB12_InterfNoiseV"},
	{metricPath: "C000100079", outputAlias: "PRB13_InterfNoiseV", matchAlias: "PRB13_InterfNoiseV"},
	{metricPath: "C000100080", outputAlias: "PRB14_InterfNoiseV", matchAlias: "PRB14_InterfNoiseV"},
	{metricPath: "C000100081", outputAlias: "PRB15_InterfNoiseV", matchAlias: "PRB15_InterfNoiseV"},
	{metricPath: "C000100082", outputAlias: "PRB16_InterfNoiseV", matchAlias: "PRB16_InterfNoiseV"},
	{metricPath: "C000100083", outputAlias: "PRB17_InterfNoiseV", matchAlias: "PRB17_InterfNoiseV"},
	{metricPath: "C000100084", outputAlias: "PRB18_InterfNoiseV", matchAlias: "PRB18_InterfNoiseV"},
	{metricPath: "C000100085", outputAlias: "PRB19_InterfNoiseV", matchAlias: "PRB19_InterfNoiseV"},
	{metricPath: "C000100086", outputAlias: "PRB20_InterfNoiseV", matchAlias: "PRB20_InterfNoiseV"},
	{metricPath: "C000100087", outputAlias: "PRB21_InterfNoiseV", matchAlias: "PRB21_InterfNoiseV"},
	{metricPath: "C000100088", outputAlias: "PRB22_InterfNoiseV", matchAlias: "PRB22_InterfNoiseV"},
	{metricPath: "C000100089", outputAlias: "PRB23_InterfNoiseV", matchAlias: "PRB23_InterfNoiseV"},
	{metricPath: "C000100090", outputAlias: "PRB24_InterfNoiseV", matchAlias: "PRB24_InterfNoiseV"},
	{metricPath: "C000100091", outputAlias: "PRB25_InterfNoiseV", matchAlias: "PRB25_InterfNoiseV"},
	{metricPath: "C000100092", outputAlias: "PRB26_InterfNoiseV", matchAlias: "PRB26_InterfNoiseV"},
	{metricPath: "C000100093", outputAlias: "PRB27_InterfNoiseV", matchAlias: "PRB27_InterfNoiseV"},
	{metricPath: "C000100094", outputAlias: "PRB28_InterfNoiseV", matchAlias: "PRB28_InterfNoiseV"},
	{metricPath: "C000100095", outputAlias: "PRB29_InterfNoiseV", matchAlias: "PRB29_InterfNoiseV"},
	{metricPath: "C000100096", outputAlias: "PRB30_InterfNoiseV", matchAlias: "PRB30_InterfNoiseV"},
	{metricPath: "C000100097", outputAlias: "PRB31_InterfNoiseV", matchAlias: "PRB31_InterfNoiseV"},
	{metricPath: "C000100098", outputAlias: "PRB32_InterfNoiseV", matchAlias: "PRB32_InterfNoiseV"},
	{metricPath: "C000100099", outputAlias: "PRB33_InterfNoiseV", matchAlias: "PRB33_InterfNoiseV"},
	{metricPath: "C000100100", outputAlias: "PRB34_InterfNoiseV", matchAlias: "PRB34_InterfNoiseV"},
	{metricPath: "C000100101", outputAlias: "PRB35_InterfNoiseV", matchAlias: "PRB35_InterfNoiseV"},
	{metricPath: "C000100102", outputAlias: "PRB36_InterfNoiseV", matchAlias: "PRB36_InterfNoiseV"},
	{metricPath: "C000100103", outputAlias: "PRB37_InterfNoiseV", matchAlias: "PRB37_InterfNoiseV"},
	{metricPath: "C000100104", outputAlias: "PRB38_InterfNoiseV", matchAlias: "PRB38_InterfNoiseV"},
	{metricPath: "C000100105", outputAlias: "PRB39_InterfNoiseV", matchAlias: "PRB39_InterfNoiseV"},
	{metricPath: "C000100106", outputAlias: "PRB40_InterfNoiseV", matchAlias: "PRB40_InterfNoiseV"},
	{metricPath: "C000100107", outputAlias: "PRB41_InterfNoiseV", matchAlias: "PRB41_InterfNoiseV"},
	{metricPath: "C000100108", outputAlias: "PRB42_InterfNoiseV", matchAlias: "PRB42_InterfNoiseV"},
	{metricPath: "C000100109", outputAlias: "PRB43_InterfNoiseV", matchAlias: "PRB43_InterfNoiseV"},
	{metricPath: "C000100110", outputAlias: "PRB44_InterfNoiseV", matchAlias: "PRB44_InterfNoiseV"},
	{metricPath: "C000100111", outputAlias: "PRB45_InterfNoiseV", matchAlias: "PRB45_InterfNoiseV"},
	{metricPath: "C000100112", outputAlias: "PRB46_InterfNoiseV", matchAlias: "PRB46_InterfNoiseV"},
	{metricPath: "C000100113", outputAlias: "PRB47_InterfNoiseV", matchAlias: "PRB47_InterfNoiseV"},
	{metricPath: "C000100114", outputAlias: "PRB48_InterfNoiseV", matchAlias: "PRB48_InterfNoiseV"},
	{metricPath: "C000100115", outputAlias: "PRB49_InterfNoiseV", matchAlias: "PRB49_InterfNoiseV"},
	{metricPath: "C000100116", outputAlias: "PRB50_InterfNoiseV", matchAlias: "PRB50_InterfNoiseV"},
	{metricPath: "C000100117", outputAlias: "PRB51_InterfNoiseV", matchAlias: "PRB51_InterfNoiseV"},
	{metricPath: "C000100118", outputAlias: "PRB52_InterfNoiseV", matchAlias: "PRB52_InterfNoiseV"},
	{metricPath: "C000100119", outputAlias: "PRB53_InterfNoiseV", matchAlias: "PRB53_InterfNoiseV"},
	{metricPath: "C000100120", outputAlias: "PRB54_InterfNoiseV", matchAlias: "PRB54_InterfNoiseV"},
	{metricPath: "C000100121", outputAlias: "PRB55_InterfNoiseV", matchAlias: "PRB55_InterfNoiseV"},
	{metricPath: "C000100122", outputAlias: "PRB56_InterfNoiseV", matchAlias: "PRB56_InterfNoiseV"},
	{metricPath: "C000100123", outputAlias: "PRB57_InterfNoiseV", matchAlias: "PRB57_InterfNoiseV"},
	{metricPath: "C000100124", outputAlias: "PRB58_InterfNoiseV", matchAlias: "PRB58_InterfNoiseV"},
	{metricPath: "C000100125", outputAlias: "PRB59_InterfNoiseV", matchAlias: "PRB59_InterfNoiseV"},
	{metricPath: "C000100126", outputAlias: "PRB60_InterfNoiseV", matchAlias: "PRB60_InterfNoiseV"},
	{metricPath: "C000100127", outputAlias: "PRB61_InterfNoiseV", matchAlias: "PRB61_InterfNoiseV"},
	{metricPath: "C000100128", outputAlias: "PRB62_InterfNoiseV", matchAlias: "PRB62_InterfNoiseV"},
	{metricPath: "C000100129", outputAlias: "PRB63_InterfNoiseV", matchAlias: "PRB63_InterfNoiseV"},
	{metricPath: "C000100130", outputAlias: "PRB64_InterfNoiseV", matchAlias: "PRB64_InterfNoiseV"},
	{metricPath: "C000100131", outputAlias: "PRB65_InterfNoiseV", matchAlias: "PRB65_InterfNoiseV"},
	{metricPath: "C000100132", outputAlias: "PRB66_InterfNoiseV", matchAlias: "PRB66_InterfNoiseV"},
	{metricPath: "C000100133", outputAlias: "PRB67_InterfNoiseV", matchAlias: "PRB67_InterfNoiseV"},
	{metricPath: "C000100134", outputAlias: "PRB68_InterfNoiseV", matchAlias: "PRB68_InterfNoiseV"},
	{metricPath: "C000100135", outputAlias: "PRB69_InterfNoiseV", matchAlias: "PRB69_InterfNoiseV"},
	{metricPath: "C000100136", outputAlias: "PRB70_InterfNoiseV", matchAlias: "PRB70_InterfNoiseV"},
	{metricPath: "C000100137", outputAlias: "PRB71_InterfNoiseV", matchAlias: "PRB71_InterfNoiseV"},
	{metricPath: "C000100138", outputAlias: "PRB72_InterfNoiseV", matchAlias: "PRB72_InterfNoiseV"},
	{metricPath: "C000100139", outputAlias: "PRB73_InterfNoiseV", matchAlias: "PRB73_InterfNoiseV"},
	{metricPath: "C000100140", outputAlias: "PRB74_InterfNoiseV", matchAlias: "PRB74_InterfNoiseV"},
	{metricPath: "C000100141", outputAlias: "PRB75_InterfNoiseV", matchAlias: "PRB75_InterfNoiseV"},
	{metricPath: "C000100142", outputAlias: "PRB76_InterfNoiseV", matchAlias: "PRB76_InterfNoiseV"},
	{metricPath: "C000100143", outputAlias: "PRB77_InterfNoiseV", matchAlias: "PRB77_InterfNoiseV"},
	{metricPath: "C000100144", outputAlias: "PRB78_InterfNoiseV", matchAlias: "PRB78_InterfNoiseV"},
	{metricPath: "C000100145", outputAlias: "PRB79_InterfNoiseV", matchAlias: "PRB79_InterfNoiseV"},
	{metricPath: "C000100146", outputAlias: "PRB80_InterfNoiseV", matchAlias: "PRB80_InterfNoiseV"},
	{metricPath: "C000100147", outputAlias: "PRB81_InterfNoiseV", matchAlias: "PRB81_InterfNoiseV"},
	{metricPath: "C000100148", outputAlias: "PRB82_InterfNoiseV", matchAlias: "PRB82_InterfNoiseV"},
	{metricPath: "C000100149", outputAlias: "PRB83_InterfNoiseV", matchAlias: "PRB83_InterfNoiseV"},
	{metricPath: "C000100150", outputAlias: "PRB84_InterfNoiseV", matchAlias: "PRB84_InterfNoiseV"},
	{metricPath: "C000100151", outputAlias: "PRB85_InterfNoiseV", matchAlias: "PRB85_InterfNoiseV"},
	{metricPath: "C000100152", outputAlias: "PRB86_InterfNoiseV", matchAlias: "PRB86_InterfNoiseV"},
	{metricPath: "C000100153", outputAlias: "PRB87_InterfNoiseV", matchAlias: "PRB87_InterfNoiseV"},
	{metricPath: "C000100154", outputAlias: "PRB88_InterfNoiseV", matchAlias: "PRB88_InterfNoiseV"},
	{metricPath: "C000100155", outputAlias: "PRB89_InterfNoiseV", matchAlias: "PRB89_InterfNoiseV"},
	{metricPath: "C000100156", outputAlias: "PRB90_InterfNoiseV", matchAlias: "PRB90_InterfNoiseV"},
	{metricPath: "C000100157", outputAlias: "PRB91_InterfNoiseV", matchAlias: "PRB91_InterfNoiseV"},
	{metricPath: "C000100158", outputAlias: "PRB92_InterfNoiseV", matchAlias: "PRB92_InterfNoiseV"},
	{metricPath: "C000100159", outputAlias: "PRB93_InterfNoiseV", matchAlias: "PRB93_InterfNoiseV"},
	{metricPath: "C000100160", outputAlias: "PRB94_InterfNoiseV", matchAlias: "PRB94_InterfNoiseV"},
	{metricPath: "C000100161", outputAlias: "PRB95_InterfNoiseV", matchAlias: "PRB95_InterfNoiseV"},
	{metricPath: "C000100162", outputAlias: "PRB96_InterfNoiseV", matchAlias: "PRB96_InterfNoiseV"},
	{metricPath: "C000100163", outputAlias: "PRB97_InterfNoiseV", matchAlias: "PRB97_InterfNoiseV"},
	{metricPath: "C000100164", outputAlias: "PRB98_InterfNoiseV", matchAlias: "PRB98_InterfNoiseV"},
	{metricPath: "C000100165", outputAlias: "PRB99_InterfNoiseV", matchAlias: "PRB99_InterfNoiseV"},
	{metricPath: "C000100166", outputAlias: "PRB100_InterfNoiseV", matchAlias: "PRB100_InterfNoiseV"},
	{metricPath: "C000100167", outputAlias: "PRB_InterfNoiseV", matchAlias: "PRB_InterfNoiseV"},
	{metricPath: "C000030011", outputAlias: "VlteVoice_HOAttOutX2", matchAlias: "VlteVoice_HOAttOutX2"},
	{metricPath: "C000030017", outputAlias: "VlteVoice_HOSuccOutX2", matchAlias: "VlteVoice_HOSuccOutX2"},
	{metricPath: "C000030002", outputAlias: "VlteVoice_HOAttOutS1", matchAlias: "VlteVoice_HOAttOutS1"},
	{metricPath: "C000030008", outputAlias: "VlteVoice_HOSuccOutS1", matchAlias: "VlteVoice_HOSuccOutS1"},
}

var legacyS0009PCMetrics = []legacyPMMetricSeed{
	{metricPath: "C000000005", outputAlias: "RRC.AttConnEstab(time)", matchAlias: "RRC_AttConnEstab(time)"},
	{metricPath: "C000000012", outputAlias: "RRC.SuccConnEstab(time)", matchAlias: "RRC_SuccConnEstab(time)"},
	{metricPath: "C000000052", outputAlias: "RRC.Csfb.PrepAtt(time)", matchAlias: "RRC_Csfb_PrepAtt(time)"},
	{metricPath: "C000000053", outputAlias: "RRC.Csfb.PrepSucc(time)", matchAlias: "RRC_Csfb_PrepSucc(time)"},
	{metricPath: "C000010050", outputAlias: "ERAB.NbrAttEstab(number)", matchAlias: "ERAB_NbrAttEstab(number)"},
	{metricPath: "C000010060", outputAlias: "ERAB.NbrSuccEstab(number)", matchAlias: "ERAB_NbrSuccEstab(number)"},
	{metricPath: "C000010070", outputAlias: "ERAB.EstabInitAttNbr.sum(time)", matchAlias: "ERAB_EstabInitAttNbr_sum(time)"},
	{metricPath: "C000010076", outputAlias: "ERAB.EstabInitAttNbr.QCI6(time)", matchAlias: "ERAB_EstabInitAttNbr_QCI6(time)"},
	{metricPath: "C000010080", outputAlias: "ERAB.EstEstabInitSuccNbr.sum(time)", matchAlias: "ERAB_EstEstabInitSuccNbr_sum(time)"},
	{metricPath: "C000010086", outputAlias: "ERAB.EstabInitSuccNbr.QCI6(time)", matchAlias: "ERAB_EstabInitSuccNbr_QCI6(time)"},
	{metricPath: "C000010106", outputAlias: "ERAB.EstabAddAttNbr.sum(time)", matchAlias: "ERAB_EstabAddAttNbr_sum(time)"},
	{metricPath: "C000010116", outputAlias: "ERAB.EstabAddSuccNbr.sum(time)", matchAlias: "ERAB_EstabAddSuccNbr_sum(time)"},
	{metricPath: "C000010120", outputAlias: "ERAB.EstabAddFailNbr.NoRadioResourcesAvailableInTargetCell(time)", matchAlias: "ERAB_EstabAddFailNbr_NoRadioResourcesAvailableInTargetCell(time)"},
	{metricPath: "C000010145", outputAlias: "ERAB.NbrReqRelEnb.Normal(number)", matchAlias: "ERAB_NbrReqRelEnb_Normal(number)"},
	{metricPath: "C000010164", outputAlias: "ERAB.RelFailNbr.Sum(time)", matchAlias: "ERAB_RelFailNbr_Sum(time)"},
	{metricPath: "C000010259", outputAlias: "ERAB.EstabInitFailNbr.NoRadioResourcesAvailableInTargetCell(number)", matchAlias: "ERAB_EstabInitFailNbr_NoRadioResourcesAvailableInTargetCell(number)"},
	{metricPath: "C000030048", outputAlias: "HO.InterRatOutAtt.Csfb.Utran(time)", matchAlias: "HO_InterRatOutAtt_Csfb_Utran(time)"},
	{metricPath: "C000030052", outputAlias: "HO.InterRatOutSucc.Csfb.Utran(time)", matchAlias: "HO_InterRatOutSucc_Csfb_Utran(time)"},
	{metricPath: "C000030071", outputAlias: "HO.InterFreqPrepAtt(time)", matchAlias: "HO_InterFreqPrepAtt(time)"},
	{metricPath: "C000030101", outputAlias: "HO.SuccOutInterFreq(time)", matchAlias: "HO_SuccOutInterFreq(time)"},
	{metricPath: "C000060001", outputAlias: "PDCP.UpOctUl(KByte)", matchAlias: "PDCP_UpOctUl(KByte)"},
	{metricPath: "C000060011", outputAlias: "PDCP.UpOctDl(KByte)", matchAlias: "PDCP_UpOctDl(KByte)"},
	{metricPath: "C000060160", outputAlias: "DRB.PdcpSduBitrateDlMax(Kbps)", matchAlias: "DRB_PdcpSduBitrateDlMax(Kbps)"},
	{metricPath: "C000060161", outputAlias: "DRB.PdcpSduBitrateUlMax(Kbps)", matchAlias: "DRB_PdcpSduBitrateUlMax(Kbps)"},
	{metricPath: "C000070020", outputAlias: "DRB.UEActiveDl.Sum(number)", matchAlias: "DRB_UEActiveDl_Sum(number)"},
	{metricPath: "C000090113", outputAlias: "MAC.TaUenum.range1(number)", matchAlias: "MAC_TaUenum_range1(number)"},
	{metricPath: "C000090114", outputAlias: "MAC.TaUenum.range2(number)", matchAlias: "MAC_TaUenum_range2(number)"},
	{metricPath: "C000090115", outputAlias: "MAC.TaUenum.range3(number)", matchAlias: "MAC_TaUenum_range3(number)"},
	{metricPath: "C000100184", outputAlias: "L.UL.Interference.Avg.20(dBm)", matchAlias: "L_UL_Interference_Avg_20(dBm)"},
	{metricPath: "C000100185", outputAlias: "L.UL.Interference.Avg.03(dBm)", matchAlias: "L_UL_Interference_Avg_03(dBm)"},
	{metricPath: "C000100186", outputAlias: "L.UL.RSRP.PUSCH.Index0(number)", matchAlias: "L_UL_RSRP_PUSCH_Index0(number)"},
	{metricPath: "C000100187", outputAlias: "L.UL.RSRP.PUSCH.Index1(number)", matchAlias: "L_UL_RSRP_PUSCH_Index1(number)"},
	{metricPath: "C000100188", outputAlias: "L.UL.RSRP.PUSCH.Index2(number)", matchAlias: "L_UL_RSRP_PUSCH_Index2(number)"},
	{metricPath: "C000100189", outputAlias: "L.UL.RSRP.PUSCH.Index3(number)", matchAlias: "L_UL_RSRP_PUSCH_Index3(number)"},
	{metricPath: "C000100190", outputAlias: "L.UL.RSRP.PUSCH.Index4(number)", matchAlias: "L_UL_RSRP_PUSCH_Index4(number)"},
	{metricPath: "C000100191", outputAlias: "L.UL.RSRP.PUSCH.Index5(number)", matchAlias: "L_UL_RSRP_PUSCH_Index5(number)"},
	{metricPath: "C000100192", outputAlias: "L.UL.RSRP.PUSCH.Index6(number)", matchAlias: "L_UL_RSRP_PUSCH_Index6(number)"},
	{metricPath: "C000100193", outputAlias: "L.UL.RSRP.PUSCH.Index7(number)", matchAlias: "L_UL_RSRP_PUSCH_Index7(number)"},
	{metricPath: "C000100194", outputAlias: "L.UL.RSRP.PUSCH.Index8(number)", matchAlias: "L_UL_RSRP_PUSCH_Index8(number)"},
	{metricPath: "C000100195", outputAlias: "L.UL.RSRP.PUSCH.Index9(number)", matchAlias: "L_UL_RSRP_PUSCH_Index9(number)"},
	{metricPath: "K900000001", outputAlias: "RRC setup success rate(%)", matchAlias: "RRC setup success rate(%)"},
	{metricPath: "K900010005", outputAlias: "E-RAB setup success rate(%)", matchAlias: "E-RAB setup success rate(%)"},
	{metricPath: "K900010027", outputAlias: "E-RAB drop rate(H)(%)", matchAlias: "E-RAB drop rate(H)(%)"},
	{metricPath: "K900000010", outputAlias: "RRC drop rate(%)", matchAlias: "RRC drop rate(%)"},
	{metricPath: "K900010015", outputAlias: "Data Volume DL(MByte)", matchAlias: "Data Volume DL(MByte)"},
	{metricPath: "K900010016", outputAlias: "Data Volume UL(MByte)", matchAlias: "Data Volume UL(MByte)"},
	{metricPath: "K900010017", outputAlias: "HO.IntraFreqOutSucc.Rate(%)", matchAlias: "HO_IntraFreqOutSucc_Rate(%)"},
	{metricPath: "K900010018", outputAlias: "HO.InterFreqOutSucc.Rate(%)", matchAlias: "HO_InterFreqOutSucc_Rate(%)"},
	{metricPath: "K900010019", outputAlias: "HO InterEnbOutSucc Rate S1(%)", matchAlias: "HO InterEnbOutSucc Rate S1(%)"},
	{metricPath: "K900010022", outputAlias: "HO IntraFreqInSucc Rate(%)", matchAlias: "HO IntraFreqInSucc Rate(%)"},
	{metricPath: "K900010023", outputAlias: "HO InterFreqInSucc Rate(%)", matchAlias: "HO InterFreqInSucc Rate(%)"},
	{metricPath: "K900010024", outputAlias: "HO InterEnbInSucc Rate S1(%)", matchAlias: "HO InterEnbInSucc Rate S1(%)"},
	{metricPath: "K900010029", outputAlias: "CSFB Success Rate(%)", matchAlias: "CSFB Success Rate(%)"},
	{metricPath: "K900010031", outputAlias: "Uplink PRB utilization rate(Q)(%)", matchAlias: "Uplink PRB utilization rate(Q)(%)"},
	{metricPath: "K900010032", outputAlias: "Downlink PRB utilization rate(Q)(%)", matchAlias: "Downlink PRB utilization rate(Q)(%)"},
	{metricPath: "K900010038", outputAlias: "RRC resource congestion rate(%)", matchAlias: "RRC resource congestion rate(%)"},
	{metricPath: "K900010039", outputAlias: "E-RAB resource congestion rate(%)", matchAlias: "E-RAB resource congestion rate(%)"},
	{metricPath: "N88ILSK900000001", outputAlias: "Inter RAN HO success Rate(%)", matchAlias: "Inter RAN HO success Rate(%)"},
	{metricPath: "N88ILSK900000005", outputAlias: "% of CQI 0-6(%)", matchAlias: "% of CQI 0-6(%)"},
}

var legacyS0011GSMPCMetrics = []legacyPMMetricSeed{
	{metricPath: "KGSM0101", outputAlias: "KPI.HandoverSuccessRate", matchAlias: "KPI_HandoverSuccessRate"},
	{metricPath: "KGSM0102", outputAlias: "KPI.CallSetupSuccRate", matchAlias: "KPI_CallSetupSuccRate"},
	{metricPath: "KGSM0103", outputAlias: "KPI.CallDropRate", matchAlias: "KPI_CallDropRate"},
	{metricPath: "KGSM0104", outputAlias: "KPI.SDCCHDropRate", matchAlias: "KPI_SDCCHDropRate"},
	{metricPath: "KGSM0105", outputAlias: "KPI.SDCCHBlockingRate", matchAlias: "KPI_SDCCHBlockingRate"},
	{metricPath: "KGSM0106", outputAlias: "KPI.SDCCHEstSuccessRate", matchAlias: "KPI_SDCCHEstSuccessRate"},
	{metricPath: "KGSM0107", outputAlias: "KPI.TCHAssignSuccessRate", matchAlias: "KPI_TCHAssignSuccessRate"},
	{metricPath: "KGSM0108", outputAlias: "KPI.TCHUtilizationRate", matchAlias: "KPI_TCHUtilizationRate"},
	{metricPath: "KGSM0109", outputAlias: "KPI.TCHAvaliableRate", matchAlias: "KPI_TCHAvaliableRate"},
	{metricPath: "CGSM0010001", outputAlias: "HO.Completed", matchAlias: "HO_Completed"},
	{metricPath: "CGSM0010002", outputAlias: "HO.Attempted", matchAlias: "HO_Attempted"},
	{metricPath: "CGSM0020001", outputAlias: "Call.TotalAttempts", matchAlias: "Call_TotalAttempts"},
	{metricPath: "CGSM0020002", outputAlias: "Call.Completed", matchAlias: "Call_Completed"},
	{metricPath: "CGSM0020003", outputAlias: "Call.TotalTchDrops", matchAlias: "Call_TotalTchDrops"},
	{metricPath: "CGSM0030001", outputAlias: "SDCCH.FailedAttempt", matchAlias: "SDCCH_FailedAttempt"},
	{metricPath: "CGSM0030002", outputAlias: "SDCCH.Completed", matchAlias: "SDCCH_Completed"},
	{metricPath: "CGSM0030003", outputAlias: "SDCCH.TotalSdcchChannel", matchAlias: "SDCCH_TotalSdcchChannel"},
	{metricPath: "CGSM0030004", outputAlias: "SDCCH.NoSdcchChannel", matchAlias: "SDCCH_NoSdcchChannel"},
	{metricPath: "CGSM0030005", outputAlias: "SDCCH.SdcchChannelSuccess", matchAlias: "SDCCH_SdcchChannelSuccess"},
	{metricPath: "CGSM0040001", outputAlias: "TCH.Attempts", matchAlias: "TCH_Attempts"},
	{metricPath: "CGSM0040002", outputAlias: "TCH.Completes", matchAlias: "TCH_Completes"},
	{metricPath: "CGSM0040003", outputAlias: "TCH.ChannelLoad", matchAlias: "TCH_ChannelLoad"},
	{metricPath: "CGSM0040004", outputAlias: "TCH.ActiveMillisecondsTotal", matchAlias: "TCH_ActiveMillisecondsTotal"},
	{metricPath: "CGSM0040005", outputAlias: "TCH.AllocatedChannel", matchAlias: "TCH_AllocatedChannel"},
}

var legacyS0012GNBPCMetrics = []legacyPMMetricSeed{
	{metricPath: "KGNB0101", outputAlias: "KPI.RrcSuccConnRate", matchAlias: "KPI_RrcSuccConnRate"},
	{metricPath: "KGNB0102", outputAlias: "KPI.FlowSuccConnRate", matchAlias: "KPI_FlowSuccConnRate"},
	{metricPath: "KGNB0103", outputAlias: "KPI.NGSIG.SuccConnRate", matchAlias: "KPI_NGSIG_SuccConnRate"},
	{metricPath: "KGNB0104", outputAlias: "KPI.WirelessSuccConnRate", matchAlias: "KPI_WirelessSuccConnRate"},
	{metricPath: "KGNB0301", outputAlias: "KPI.WirelessDropRate.CellLevel", matchAlias: "KPI_WirelessDropRate_CellLevel"},
	{metricPath: "KGNB0302", outputAlias: "KPI.FlowDropRate.CellLevel", matchAlias: "KPI_FlowDropRate_CellLevel"},
	{metricPath: "KGNB0303", outputAlias: "KPI.RrcConnReestabRate", matchAlias: "KPI_RrcConnReestabRate"},
	{metricPath: "KGNB0401", outputAlias: "KPI.RlcNbrPktLossRateDl", matchAlias: "KPI_RlcNbrPktLossRateDl"},
	{metricPath: "KGNB0417", outputAlias: "KPI.RLCPktDelayDL", matchAlias: "KPI_RLCPktDelayDL"},
	{metricPath: "KGNB0501", outputAlias: "KPI.RlcUpOctUl", matchAlias: "KPI_RlcUpOctUl"},
	{metricPath: "KGNB0502", outputAlias: "KPI.RlcUpOctDl", matchAlias: "KPI_RlcUpOctDl"},
	{metricPath: "KGNB0510", outputAlias: "KPI.PdcpUpOctUl", matchAlias: "KPI_PdcpUpOctUl"},
	{metricPath: "KGNB0511", outputAlias: "KPI.PdcpUpOctDl", matchAlias: "KPI_PdcpUpOctDl"},
	{metricPath: "KGNB0516", outputAlias: "KPI.AvgDataRateUl", matchAlias: "KPI_AvgDataRateUl"},
	{metricPath: "KGNB0517", outputAlias: "KPI.AvgDataRateDl", matchAlias: "KPI_AvgDataRateDl"},
	{metricPath: "C010000001", outputAlias: "RRU.RachPreambleRcvd", matchAlias: "RRU_RachPreambleRcvd"},
	{metricPath: "C010000002", outputAlias: "RRU.PdcchCceAvail", matchAlias: "RRU_PdcchCceAvail"},
	{metricPath: "C010000003", outputAlias: "RRU.PuschPrbAssn", matchAlias: "RRU_PuschPrbAssn"},
	{metricPath: "C010000004", outputAlias: "RRU.PdschPrbAssn", matchAlias: "RRU_PdschPrbAssn"},
	{metricPath: "C010000005", outputAlias: "RRU.PdcchCceUtil", matchAlias: "RRU_PdcchCceUtil"},
	{metricPath: "C010000006", outputAlias: "RRU.PuschPrbTot", matchAlias: "RRU_PuschPrbTot"},
	{metricPath: "C010000007", outputAlias: "RRU.PdschPrbTot", matchAlias: "RRU_PdschPrbTot"},
	{metricPath: "C010010001", outputAlias: "MAC.NbrTbUl", matchAlias: "MAC_NbrTbUl"},
	{metricPath: "C010010002", outputAlias: "MAC.NbrInitTbUl", matchAlias: "MAC_NbrInitTbUl"},
	{metricPath: "C010010003", outputAlias: "MAC.NbrInitTbUl.Qpsk", matchAlias: "MAC_NbrInitTbUl_Qpsk"},
	{metricPath: "C010010004", outputAlias: "MAC.NbrInitTbUl.16Qam", matchAlias: "MAC_NbrInitTbUl_16Qam"},
	{metricPath: "C010010005", outputAlias: "MAC.NbrInitTbUl.64Qam", matchAlias: "MAC_NbrInitTbUl_64Qam"},
	{metricPath: "C010010006", outputAlias: "MAC.NbrInitTbUl.256Qam", matchAlias: "MAC_NbrInitTbUl_256Qam"},
	{metricPath: "C010010007", outputAlias: "MAC.NbrResErrTbUl", matchAlias: "MAC_NbrResErrTbUl"},
	{metricPath: "C010010008", outputAlias: "MAC.NbrTbDl", matchAlias: "MAC_NbrTbDl"},
	{metricPath: "C010010009", outputAlias: "MAC.NbrTbDl.Rank1", matchAlias: "MAC_NbrTbDl_Rank1"},
	{metricPath: "C010010010", outputAlias: "MAC.NbrTbDl.Rank2", matchAlias: "MAC_NbrTbDl_Rank2"},
	{metricPath: "C010010011", outputAlias: "MAC.NbrTbDl.Rank3", matchAlias: "MAC_NbrTbDl_Rank3"},
	{metricPath: "C010010012", outputAlias: "MAC.NbrTbDl.Rank4", matchAlias: "MAC_NbrTbDl_Rank4"},
	{metricPath: "C010010013", outputAlias: "MAC.NbrInitTbDl", matchAlias: "MAC_NbrInitTbDl"},
	{metricPath: "C010010014", outputAlias: "MAC.NbrInitTbDl.Qpsk", matchAlias: "MAC_NbrInitTbDl_Qpsk"},
	{metricPath: "C010010015", outputAlias: "MAC.NbrInitTbDl.16Qam", matchAlias: "MAC_NbrInitTbDl_16Qam"},
	{metricPath: "C010010016", outputAlias: "MAC.NbrInitTbDl.64Qam", matchAlias: "MAC_NbrInitTbDl_64Qam"},
	{metricPath: "C010010017", outputAlias: "MAC.NbrInitTbDl.256Qam", matchAlias: "MAC_NbrInitTbDl_256Qam"},
	{metricPath: "C010010018", outputAlias: "MAC.NbrResErrTbDl", matchAlias: "MAC_NbrResErrTbDl"},
	{metricPath: "C010010019", outputAlias: "MAC.CpOctUl", matchAlias: "MAC_CpOctUl"},
	{metricPath: "C010010020", outputAlias: "MAC.CpOctDl", matchAlias: "MAC_CpOctDl"},
	{metricPath: "C010020001", outputAlias: "RLC.UpOctUl", matchAlias: "RLC_UpOctUl"},
	{metricPath: "C010020002", outputAlias: "RLC.UpOctDl", matchAlias: "RLC_UpOctDl"},
	{metricPath: "C010030001", outputAlias: "PDCP.NbrPktUl", matchAlias: "PDCP_NbrPktUl"},
	{metricPath: "C010030002", outputAlias: "PDCP.NbrPktLossUl", matchAlias: "PDCP_NbrPktLossUl"},
	{metricPath: "C010030003", outputAlias: "PDCP.NbrPktDl", matchAlias: "PDCP_NbrPktDl"},
	{metricPath: "C010030004", outputAlias: "PDCP.UpPktDiscardDl", matchAlias: "PDCP_UpPktDiscardDl"},
	{metricPath: "C010030005", outputAlias: "PDCP.UpOctUl", matchAlias: "PDCP_UpOctUl"},
	{metricPath: "C010030006", outputAlias: "PDCP.UpOctDl", matchAlias: "PDCP_UpOctDl"},
	{metricPath: "C010040001", outputAlias: "DRB.NbrMeanEstab", matchAlias: "DRB_NbrMeanEstab"},
	{metricPath: "C010040002", outputAlias: "DRB.NbrMaxEstab", matchAlias: "DRB_NbrMaxEstab"},
	{metricPath: "C010040003", outputAlias: "DRB.NbrLeft", matchAlias: "DRB_NbrLeft"},
	{metricPath: "C010040004", outputAlias: "DRB.ActiveMeanNbrDL", matchAlias: "DRB_ActiveMeanNbrDL"},
	{metricPath: "C010040005", outputAlias: "DRB.ActiveMaxNbrDL", matchAlias: "DRB_ActiveMaxNbrDL"},
	{metricPath: "C010050001", outputAlias: "PHY.CellMeanTxPower", matchAlias: "PHY_CellMeanTxPower"},
	{metricPath: "C010050002", outputAlias: "PHY.CellMaxTxPower", matchAlias: "PHY_CellMaxTxPower"},
	{metricPath: "C010060001", outputAlias: "CONTEXT.AttSetupDU", matchAlias: "CONTEXT_AttSetupDU"},
	{metricPath: "C010060002", outputAlias: "CONTEXT.SuccSetupDU", matchAlias: "CONTEXT_SuccSetupDU"},
	{metricPath: "C010060003", outputAlias: "CONTEXT.FailSetupDU", matchAlias: "CONTEXT_FailSetupDU"},
	{metricPath: "C010060004", outputAlias: "CONTEXT.AttModByDU", matchAlias: "CONTEXT_AttModByDU"},
	{metricPath: "C010060005", outputAlias: "CONTEXT.SuccModbyDU", matchAlias: "CONTEXT_SuccModbyDU"},
	{metricPath: "C010060006", outputAlias: "CONTEXT.FailModByDU", matchAlias: "CONTEXT_FailModByDU"},
	{metricPath: "C010060007", outputAlias: "CONTEXT.AttRelByDU", matchAlias: "CONTEXT_AttRelByDU"},
	{metricPath: "C010060008", outputAlias: "CONTEXT.SuccInitalSetup", matchAlias: "CONTEXT_SuccInitalSetup"},
	{metricPath: "C010060009", outputAlias: "CONTEXT.AttRelgNB", matchAlias: "CONTEXT_AttRelgNB"},
	{metricPath: "C010060010", outputAlias: "CONTEXT.AttRelgNB.Normal", matchAlias: "CONTEXT_AttRelgNB_Normal"},
	{metricPath: "C010060011", outputAlias: "CONTEXT.NbrLeft", matchAlias: "CONTEXT_NbrLeft"},
	{metricPath: "C010070001", outputAlias: "RRC.AttConnEstab", matchAlias: "RRC_AttConnEstab"},
	{metricPath: "C010070002", outputAlias: "RRC.SuccConnEstab", matchAlias: "RRC_SuccConnEstab"},
	{metricPath: "C010070003", outputAlias: "RRC.SuccConnReestab", matchAlias: "RRC_SuccConnReestab"},
	{metricPath: "C010070004", outputAlias: "RRC.ConnMean", matchAlias: "RRC_ConnMean"},
	{metricPath: "C010070005", outputAlias: "RRC.SAnNsaConnUserMean", matchAlias: "RRC_SAnNsaConnUserMean"},
	{metricPath: "C010070006", outputAlias: "RRC.ConnMax", matchAlias: "RRC_ConnMax"},
	{metricPath: "C010070007", outputAlias: "RRC.SAnNsaConnUserMax", matchAlias: "RRC_SAnNsaConnUserMax"},
	{metricPath: "C010070008", outputAlias: "RRC.RedirectToLTE", matchAlias: "RRC_RedirectToLTE"},
	{metricPath: "C010070009", outputAlias: "RRC.RedirectToLTE.Epsfallback", matchAlias: "RRC_RedirectToLTE_Epsfallback"},
	{metricPath: "C010070010", outputAlias: "RRC.AttConnResume", matchAlias: "RRC_AttConnResume"},
	{metricPath: "C010070011", outputAlias: "RRC.SuccConnResume", matchAlias: "RRC_SuccConnResume"},
	{metricPath: "C010080001", outputAlias: "Flow.NbrAttEstab", matchAlias: "Flow_NbrAttEstab"},
	{metricPath: "C010080002", outputAlias: "Flow.NbrAttEstab.EPSFB", matchAlias: "Flow_NbrAttEstab_EPSFB"},
	{metricPath: "C010080003", outputAlias: "Flow.NbrSuccEstab", matchAlias: "Flow_NbrSuccEstab"},
	{metricPath: "C010080004", outputAlias: "Flow.NbrReqRelGnb", matchAlias: "Flow_NbrReqRelGnb"},
	{metricPath: "C010080005", outputAlias: "Flow.NbrReqRelGnb.CauseUserInactivity", matchAlias: "Flow_NbrReqRelGnb_CauseUserInactivity"},
	{metricPath: "C010080006", outputAlias: "Flow.NbrReqRelGnb.Normal", matchAlias: "Flow_NbrReqRelGnb_Normal"},
	{metricPath: "C010080007", outputAlias: "Flow.NbrReqRelAMFInitNoHo", matchAlias: "Flow_NbrReqRelAMFInitNoHo"},
	{metricPath: "C010080008", outputAlias: "Flow.NbrReqRelGnbByHo", matchAlias: "Flow_NbrReqRelGnbByHo"},
	{metricPath: "C010080009", outputAlias: "Flow.NbrLeft", matchAlias: "Flow_NbrLeft"},
	{metricPath: "C010080010", outputAlias: "Flow.NbrHoInc", matchAlias: "Flow_NbrHoInc"},
	{metricPath: "C010090001", outputAlias: "HO.AttOutInterCuNG", matchAlias: "HO_AttOutInterCuNG"},
	{metricPath: "C010090002", outputAlias: "HO.SuccOutPrepInterCuNG", matchAlias: "HO_SuccOutPrepInterCuNG"},
	{metricPath: "C010090003", outputAlias: "HO.SuccOutInterCuNG", matchAlias: "HO_SuccOutInterCuNG"},
	{metricPath: "C010090004", outputAlias: "HO.SuccOutPrepInterCuXn", matchAlias: "HO_SuccOutPrepInterCuXn"},
	{metricPath: "C010090005", outputAlias: "HO.AttOutExecInterCuXn", matchAlias: "HO_AttOutExecInterCuXn"},
	{metricPath: "C010090006", outputAlias: "HO.AvgTimeInterCuXn", matchAlias: "HO_AvgTimeInterCuXn"},
	{metricPath: "C010090007", outputAlias: "HO.AttOutCUIntraDU", matchAlias: "HO_AttOutCUIntraDU"},
	{metricPath: "C010090008", outputAlias: "HO.SuccOutIntraDU", matchAlias: "HO_SuccOutIntraDU"},
	{metricPath: "C010090009", outputAlias: "HO.AttPrepInc", matchAlias: "HO_AttPrepInc"},
	{metricPath: "C010090010", outputAlias: "HO.SuccExecInc", matchAlias: "HO_SuccExecInc"},
	{metricPath: "C010100001", outputAlias: "IRATHO.AttOutEutran", matchAlias: "IRATHO_AttOutEutran"},
	{metricPath: "C010100002", outputAlias: "IRATHO.AttOutEutran.EpsFallBack", matchAlias: "IRATHO_AttOutEutran_EpsFallBack"},
	{metricPath: "C010100003", outputAlias: "IRATHO.SuccPrepOutEutran", matchAlias: "IRATHO_SuccPrepOutEutran"},
	{metricPath: "C010100004", outputAlias: "IRATHO.SuccPrepOutEutran.EpsFallBack", matchAlias: "IRATHO_SuccPrepOutEutran_EpsFallBack"},
	{metricPath: "C010100005", outputAlias: "IRATHO.SuccOutEutran", matchAlias: "IRATHO_SuccOutEutran"},
	{metricPath: "C010100006", outputAlias: "IRATHO.SuccOutEutran.EpsFallBack", matchAlias: "IRATHO_SuccOutEutran_EpsFallBack"},
	{metricPath: "C010110001", outputAlias: "NGSIG.ConnEstabAtt", matchAlias: "NGSIG_ConnEstabAtt"},
	{metricPath: "C010110002", outputAlias: "NGSIG.ConnEstabSucc", matchAlias: "NGSIG_ConnEstabSucc"},
	{metricPath: "C010070012", outputAlias: "RRC.AttConnReestab", matchAlias: "RRC_AttConnReestab"},
	{metricPath: "C010070013", outputAlias: "RRC.SuccConnReestab.NonSrccell", matchAlias: "RRC_SuccConnReestab_NonSrccell"},
	{metricPath: "C010080011", outputAlias: "Flow.HoAdmitFail", matchAlias: "Flow_HoAdmitFail"},
	{metricPath: "C010020003", outputAlias: "RLC.NbrPktLossDl", matchAlias: "RLC_NbrPktLossDl"},
	{metricPath: "C010020004", outputAlias: "RLC.NbrPktDl", matchAlias: "RLC_NbrPktDl"},
	{metricPath: "C010020005", outputAlias: "RLC.PktDelayDL", matchAlias: "RLC_PktDelayDL"},
	{metricPath: "C010000008", outputAlias: "RRU.DtchPrbAssnUl", matchAlias: "RRU_DtchPrbAssnUl"},
	{metricPath: "C010000009", outputAlias: "RRU.DtchPrbAssnDl", matchAlias: "RRU_DtchPrbAssnDl"},
	{metricPath: "C010020006", outputAlias: "RLC.UpLastTtiOctUl", matchAlias: "RLC_UpLastTtiOctUl"},
	{metricPath: "C010020007", outputAlias: "RLC.UpLastTtiOctDl", matchAlias: "RLC_UpLastTtiOctDl"},
	{metricPath: "C010020008", outputAlias: "RLC.ThrpTimeUL", matchAlias: "RLC_ThrpTimeUL"},
	{metricPath: "C010020009", outputAlias: "RLC.ThrpTimeDL", matchAlias: "RLC_ThrpTimeDL"},
}

var legacyS0013GSMPCMetrics = []legacyPMMetricSeed{
	{metricPath: "C000080004", outputAlias: "RRU.PuschPrbMeanTot", matchAlias: "RRU_PuschPrbMeanTot"},
	{metricPath: "C000080005", outputAlias: "RRU.PdschPrbMeanTot", matchAlias: "RRU_PdschPrbMeanTot"},
	{metricPath: "C000080006", outputAlias: "RRU.TtiTotUl", matchAlias: "RRU_TtiTotUl"},
	{metricPath: "C000080007", outputAlias: "RRU.TtiTotDl", matchAlias: "RRU_TtiTotDl"},
}

var legacyS0016GSMPCMetrics = []legacyPMMetricSeed{
	{metricPath: "KGSM0104", outputAlias: "KPI.SDCCHDropRate", matchAlias: "KPI_SDCCHDropRate"},
	{metricPath: "KGSM0105", outputAlias: "KPI.SDCCHBlockingRate", matchAlias: "KPI_SDCCHBlockingRate"},
	{metricPath: "KGSM0106", outputAlias: "KPI.SDCCHEstSuccessRate", matchAlias: "KPI_SDCCHEstSuccessRate"},
	{metricPath: "KGSM0107", outputAlias: "KPI.TCHAssignSuccessRate", matchAlias: "KPI_TCHAssignSuccessRate"},
	{metricPath: "KGSM0108", outputAlias: "KPI.TCHUtilizationRate", matchAlias: "KPI_TCHUtilizationRate"},
	{metricPath: "KGSM0109", outputAlias: "KPI.TCHAvaliableRate", matchAlias: "KPI_TCHAvaliableRate"},
	{metricPath: "KGSM0110", outputAlias: "KPI.Call.SameTimeMaxUe", matchAlias: "KPI_Call_SameTimeMaxUe"},
	{metricPath: "KGSM0113", outputAlias: "KPI.Paging.Responded", matchAlias: "KPI_Paging_Responded"},
	{metricPath: "N88ILSK900000001", outputAlias: "TCH.Erlang", matchAlias: "TCH_Erlang"},
}

var legacyPMAdditionalProfileSpecs = []legacyPMProfileSpec{
	{profile: legacyPMS0002PEProfile, objectCode: "PE", tech: "LTE", baseFields: legacyPMBaseFieldsPELTE, metrics: legacyS0002PEMetrics},
	{profile: legacyPMS0002PCProfile, objectCode: "PC", tech: "LTE", baseFields: legacyPMBaseFieldsS0001PC, metrics: legacyS0002PCMetrics},
	{profile: legacyPMS0003PCProfile, objectCode: "PC", tech: "LTE", baseFields: legacyPMBaseFieldsS0001PC, metrics: legacyS0003PCMetrics},
	{profile: legacyPMS0008PCProfile, objectCode: "PC", tech: "LTE", baseFields: legacyPMBaseFieldsS0008PC, metrics: legacyS0001PCMetrics},
	{profile: legacyPMS0009PCProfile, objectCode: "PC", tech: "LTE", baseFields: legacyPMBaseFieldsS0009PC, metrics: legacyS0009PCMetrics},
	{profile: legacyPMS0011GSMPCProfile, objectCode: "PC", tech: "GSM", baseFields: legacyPMBaseFieldsS0001PC, metrics: legacyS0011GSMPCMetrics},
	{profile: legacyPMS0012GNBPCProfile, objectCode: "PC", tech: "GNB", baseFields: legacyPMBaseFieldsGNBPC, metrics: legacyS0012GNBPCMetrics},
	{profile: legacyPMS0013GSMPCProfile, objectCode: "PC", tech: "LTE", baseFields: legacyPMBaseFieldsS0013GSMPC, metrics: legacyS0013GSMPCMetrics},
	{profile: legacyPMS0016LTEPCProfile, objectCode: "PC", tech: "LTE", baseFields: legacyPMBaseFieldsS0016LTEPC, metrics: legacyS0001PCMetrics},
	{profile: legacyPMS0016GSMPCProfile, objectCode: "PC", tech: "GSM", baseFields: legacyPMBaseFieldsS0016GSMPC, metrics: legacyS0016GSMPCMetrics},
}
