FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOPROXY=https://goproxy.cn,direct GOOS=linux go build -ldflags="-s -w" -o /build/bin/omcgo-acs ./cmd/acs

# ---

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /build/bin/omcgo-acs /usr/local/bin/omcgo-acs
COPY --from=builder /build/cmd/acs/etc/config.prod.yaml /etc/omcgo/acs.yaml

EXPOSE 7547 7548 9090

ENTRYPOINT ["omcgo-acs"]
CMD ["--config", "/etc/omcgo/acs.yaml"]
