-- +goose Up
-- ============================================================
-- 000004_mml_enhance.sql —— 已下线 noop（2026-05-22）
--
-- 原内容：
--   A) mml_tasks ALTER ADD COLUMN（execute_type / scheduled_at / period_* /
--      retry / 统计计数 / result 等 16 列），用 DO $$ IF NOT EXISTS THEN ALTER
--      包裹做 idempotent；
--   B) mml_commands ALTER ADD COLUMN（operation_type / param_paths /
--      supported_operations / help_doc / notes），同样 idempotent；
--   C) DELETE + INSERT 25 条 mml_commands 老 seed，按 7 大类组织；
--   D) 字典种子：sys_dictionaries / sys_dictionary_details 灌产品类型 +
--      MML 命令分类。
--
-- 下线原因：
--   1. C 段 INSERT 引用列 param_template / param_paths / supported_operations
--      / product_types，这些列在 migrations/000090_mml_schema_rebuild.sql Up
--      段被 DROP（catalog v2 重构），fresh DB 上 INSERT 必报 SQLSTATE 42703
--      "column ... does not exist"。
--   2. A 段 mml_tasks ALTER 已被 main/000020_mml_tasks_lifecycle.sql 等后续
--      schema migrations 接管（execute_type / scheduled_at / retry 字段早已
--      作为正式 schema 落地，IF NOT EXISTS 守护层多余）。
--   3. B 段同上：mml_commands operation_type 由 main/000090 显式 ADD COLUMN
--      并 SET NOT NULL，本 seed 里的 DEFAULT 'LST' TEXT 与 schema/000090 的
--      VARCHAR(20) 类型也不一致，留着是数据形态漂移源。
--   4. 25 条 mml_commands 老 seed 全部由 v2 catalog (seed/000152
--      cmcc_tdlte_v23_mml_commands + 000155 canonicalize) 重新写入，老数据
--      在 000090 已 TRUNCATE，prod 上无残留。
--   5. D 段 sys_dictionaries('product_type', 'mml_command_category') 字典
--      数据已由 seed/000154_dict_rename_product_type_to_product_class.sql
--      (UPDATE 重命名 + WHERE NOT EXISTS 兜底 INSERT) 接管 / 重组。
--
-- 与 seed/000005..000008 同期 noop 处理一致（这一批 mml 早期 seed 由 catalog
-- v2 重构整体替代）。Down 段保持 noop 对称。
-- ============================================================
SELECT 1;

-- +goose Down
SELECT 1;
