-- Import alarm library from CSV
-- +goose Up

-- 同一条语句 truncate 两张有 FK 关系的表（alarm_library_i18n.library_id →
-- alarm_libraries.id ON DELETE CASCADE）。两条独立 TRUNCATE 会被 PG 拒绝：
-- 被 FK 引用的表必须与所有引用方同时 truncate，否则要 CASCADE。
TRUNCATE alarm_library_i18n, alarm_libraries RESTART IDENTITY;

INSERT INTO alarm_libraries (alarm_identifier, alarm_source, event_type, severity, enabled, probable_cause, explanation) VALUES
('10', 'omc', 'communicationsAlarm', 1, true, '主机切换告警', '主机系统发生故障，导致主备系统切换'),
('10001', 'gnb', 'equipmentAlarm', 2, true, '数字板一般过温', '温度高于90度，触发一般过温告警'),
('10002', 'gnb', 'equipmentAlarm', 1, true, '数字板严重过温', '温度高于100度，触发严重过温告警，通道阻塞'),
('10003', 'gnb', 'equipmentAlarm', 1, true, '数字板低温', '温度低于-40度'),
('10004', 'gnb', 'equipmentAlarm', 3, true, '光模块接收功率一般过低', '光纤连接不稳或未接光纤'),
('10005', 'gnb', 'equipmentAlarm', 2, true, '光模块接收功率严重过低', '光纤连接不稳或未接光纤'),
('10006', 'gnb', 'equipmentAlarm', 3, true, '光模块接收功率一般过高', '光纤连接不稳，接收光功率高'),
('10007', 'gnb', 'equipmentAlarm', 2, true, '光模块接收功率严重过高', '光纤连接不稳，接收光功率过高'),
('10008', 'gnb', 'equipmentAlarm', 3, true, '光模块发送功率一般过低', '光纤连接不稳或未接光纤'),
('10009', 'gnb', 'equipmentAlarm', 2, true, '光模块发送功率严重过低', '光纤连接不稳或未接光纤'),
('10010', 'gnb', 'equipmentAlarm', 3, true, '光模块发送功率一般过高', '光纤连接不稳，发送光功率高'),
('10011', 'gnb', 'equipmentAlarm', 2, true, '光模块发送功率严重过高', '光纤连接不稳，发送光功率过高'),
('10012', 'gnb', 'equipmentAlarm', 3, true, '光模块一般欠压', '光纤连接不稳，光功率欠压'),
('10013', 'gnb', 'equipmentAlarm', 2, true, '光模块严重欠压', '光纤连接不稳，光功率严重欠压'),
('10014', 'gnb', 'equipmentAlarm', 4, true, 'RRU升级失败', '软件版本升级失败'),
('10015', 'gnb', 'equipmentAlarm', 1, true, '设备上电初始化失败', '设备上电初始化失败'),
('10016', 'gnb', 'equipmentAlarm', 1, true, '上行接收通道异常失败(通道1)', '上行接收通道异常失败(通道1)'),
('10017', 'gnb', 'equipmentAlarm', 1, true, '上行接收通道异常失败(通道2)', '上行接收通道异常失败(通道2)'),
('10018', 'gnb', 'equipmentAlarm', 1, true, '上行接收通道异常失败(通道3)', '上行接收通道异常失败(通道3)'),
('10019', 'gnb', 'equipmentAlarm', 1, true, '上行接收通道异常失败(通道4)', '上行接收通道异常失败(通道4)'),
('10020', 'gnb', 'equipmentAlarm', 1, true, '上行接收通道异常失败(通道5)', '上行接收通道异常失败(通道5)'),
('10021', 'gnb', 'equipmentAlarm', 1, true, '上行接收通道异常失败(通道6)', '上行接收通道异常失败(通道6)'),
('10024', 'gnb', 'equipmentAlarm', 1, true, '下行发送通道异常失败(通道1)', '下行发送通道异常失败(通道1)'),
('10025', 'gnb', 'equipmentAlarm', 1, true, '下行发送通道异常失败(通道2)', '下行发送通道异常失败(通道2)'),
('10026', 'gnb', 'equipmentAlarm', 1, true, '下行发送通道异常失败(通道3)', '下行发送通道异常失败(通道3)'),
('10027', 'gnb', 'equipmentAlarm', 1, true, '下行发送通道异常失败(通道4)', '下行发送通道异常失败(通道4)'),
('10028', 'gnb', 'equipmentAlarm', 1, true, '下行发送通道异常失败(通道5)', '下行发送通道异常失败(通道5)'),
('10029', 'gnb', 'equipmentAlarm', 1, true, '下行发送通道异常失败(通道6)', '下行发送通道异常失败(通道6)'),
('10032', 'gnb', 'equipmentAlarm', 2, true, '下行通道增益控制异常(通道1)', '下行通道增益控制异常(通道1)'),
('10033', 'gnb', 'equipmentAlarm', 2, true, '下行通道增益控制异常(通道2)', '下行通道增益控制异常(通道2)'),
('10034', 'gnb', 'equipmentAlarm', 2, true, '下行通道增益控制异常(通道3)', '下行通道增益控制异常(通道3)'),
('10035', 'gnb', 'equipmentAlarm', 2, true, '下行通道增益控制异常(通道4)', '下行通道增益控制异常(通道4)'),
('10036', 'gnb', 'equipmentAlarm', 2, true, '下行通道增益控制异常(通道5)', '下行通道增益控制异常(通道5)'),
('10037', 'gnb', 'equipmentAlarm', 2, true, '下行通道增益控制异常(通道6)', '下行通道增益控制异常(通道6)'),
('10040', 'gnb', 'equipmentAlarm', 1, true, '时钟失锁', '时钟失锁'),
('10041', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率过载(通道1)', '下行通道数字功率过载(通道1)'),
('10042', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率过载(通道2)', '下行通道数字功率过载(通道2)'),
('10043', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率过载(通道3)', '下行通道数字功率过载(通道3)'),
('10044', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率过载(通道4)', '下行通道数字功率过载(通道4)'),
('10045', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率过载(通道5)', '下行通道数字功率过载(通道5)'),
('10046', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率过载(通道6)', '下行通道数字功率过载(通道6)'),
('10049', 'gnb', 'equipmentAlarm', 2, true, '下行功放保护异常', '下行功放保护异常'),
('10050', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率欠功率(通道1)', '下行通道数字功率欠功率(通道1)'),
('10051', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率欠功率(通道2)', '下行通道数字功率欠功率(通道2)'),
('10052', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率欠功率(通道3)', '下行通道数字功率欠功率(通道3)'),
('10053', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率欠功率(通道4)', '下行通道数字功率欠功率(通道4)'),
('10054', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率欠功率(通道5)', '下行通道数字功率欠功率(通道5)'),
('10055', 'gnb', 'equipmentAlarm', 2, true, '下行通道数字功率欠功率(通道6)', '下行通道数字功率欠功率(通道6)'),
('10058', 'gnb', 'equipmentAlarm', 2, true, 'Cpri接口失步', 'Cpri接口失步'),
('10059', 'enb', 'equipmentAlarm', 2, true, 'ECI冲突告警', '')
ON CONFLICT (alarm_identifier) DO UPDATE SET
  alarm_source = EXCLUDED.alarm_source,
  event_type = EXCLUDED.event_type,
  severity = EXCLUDED.severity,
  probable_cause = EXCLUDED.probable_cause,
  explanation = EXCLUDED.explanation,
  updated_at = now();

INSERT INTO alarm_libraries (alarm_identifier, alarm_source, event_type, severity, enabled, probable_cause, explanation) VALUES
('10060', 'enb', 'equipmentAlarm', 2, true, '小区去激活告警', ''),
('11', 'enb', 'equipmentAlarm', 1, true, 'SAS异常告警', 'SAS异常告警'),
('11109', 'enb', 'communicationsAlarm', 2, true, 'S1接口故障告警', ''),
('11110', 'enb', 'communicationsAlarm', 2, true, 'X2接口故障告警', ''),
('11111', 'enb', 'equipmentAlarm', 1, true, '内存空间不足', ''),
('11112', 'enb', 'communicationsAlarm', 1, true, 'SCTP链路故障告警', ''),
('11113', 'enb', 'communicationsAlarm', 4, true, '用户面承载链路故障', ''),
('11128', 'enb', 'processingErrorAlarm', 2, true, 'RLCUL configuration failure', 'Config fail for RLCUL during static config'),
('11164', 'enb', 'equipmentAlarm', 2, true, '邻区动态配置失败告警', '邻区动态配置'),
('11180', 'enb', 'processingErrorAlarm', 1, true, '小区PCI冲突告警', ''),
('11181', 'enb', 'processingErrorAlarm', 1, true, '小区PCI混淆告警', ''),
('11182', 'enb', 'environmentalAlarm', 2, true, '单板温度异常告警', ''),
('11184', 'enb', 'equipmentAlarm', 1, true, '小区不可用告警', ''),
('11185', 'enb', 'equipmentAlarm', 3, true, '无用户在线告警', ''),
('11187', 'enb', 'equipmentAlarm', 2, true, '主区版本不可用告警', ''),
('11189', 'enb', 'equipmentAlarm', 2, true, '时钟源同步失败告警', ''),
('11190', 'enb', 'equipmentAlarm', 2, true, 'GPS不可用告警', ''),
('11191', 'enb', 'processingErrorAlarm', 3, true, '时间同步失败告警', ''),
('11196', 'enb', 'equipmentAlarm', 4, true, '未知板卡类型告警', ''),
('11197', 'enb', 'processingErrorAlarm', 4, true, '配置检查失败告警', ''),
('11200', 'enb', 'processingErrorAlarm', 1, true, 'PCI自配置失败', ''),
('11201', 'enb', 'environmentalAlarm', 2, true, 'SFP温度过高告警', ''),
('11202', 'enb', 'environmentalAlarm', 2, true, 'SFP温度过低告警', ''),
('11203', 'enb', 'equipmentAlarm', 2, true, 'SFP电压过高告警', ''),
('11204', 'enb', 'equipmentAlarm', 2, true, 'SFP电压过低告警', ''),
('11205', 'enb', 'equipmentAlarm', 2, true, 'SFP偏压值过高告警', ''),
('11206', 'enb', 'equipmentAlarm', 2, true, 'SFP偏压值过低告警', ''),
('11207', 'enb', 'equipmentAlarm', 3, true, 'SFP Tx功率过高告警', ''),
('11208', 'enb', 'equipmentAlarm', 3, true, 'SFP Tx功率过低告警', ''),
('11209', 'enb', 'equipmentAlarm', 3, true, 'SFP Rx功率过高告警', ''),
('11210', 'enb', 'equipmentAlarm', 3, true, 'SFP Rx功率过低告警', ''),
('11211', 'enb', 'equipmentAlarm', 3, true, 'SFP Tx_Fault状态异常告警', ''),
('11212', 'enb', 'equipmentAlarm', 3, true, 'SFP Rxlos状态异常告警', ''),
('11213', 'enb', 'equipmentAlarm', 2, true, 'SFP不在位告警', ''),
('11217', 'enb', 'equipmentAlarm', 2, true, 'WAN口丢包率过大告警', ''),
('11218', 'enb', 'equipmentAlarm', 2, true, 'WAN口误帧率过大告警', ''),
('11219', 'enb', 'equipmentAlarm', 2, true, 'GPS模块故障', ''),
('11220', 'enb', 'equipmentAlarm', 2, true, '时钟锁相环失锁次要告警', ''),
('11221', 'enb', 'equipmentAlarm', 2, true, '时钟锁相环失锁严重告警', ''),
('11223', 'enb', 'equipmentAlarm', 2, true, 'GPS天线不在位告警', ''),
('11224', 'enb', 'equipmentAlarm', 4, true, '有来自邻区的干扰告警', ''),
('11225', 'enb', 'processingErrorAlarm', 2, true, 'License将会过期', ''),
('11226', 'enb', 'processingErrorAlarm', 1, true, 'License已经过期', ''),
('11228', 'enb', 'processingErrorAlarm', 2, true, '流量限制达到最大限额', '流量限制达到最大限额'),
('11300', 'enb', 'equipmentAlarm', 2, true, '1588配置命令执行失败告警', ''),
('11301', 'enb', 'equipmentAlarm', 2, true, '1588不可用告警', ''),
('11302', 'enb', 'processingErrorAlarm', 1, true, '1588 License 过期', ''),
('11303', 'enb', 'equipmentAlarm', 1, true, '以太网链路故障', ''),
('11304', 'enb', 'equipmentAlarm', 1, true, '传输光接口错误（仅限直流）', ''),
('11305', 'enb', 'equipmentAlarm', 1, true, '以太网中继链路故障（仅限直流）', '')
ON CONFLICT (alarm_identifier) DO UPDATE SET
  alarm_source = EXCLUDED.alarm_source,
  event_type = EXCLUDED.event_type,
  severity = EXCLUDED.severity,
  probable_cause = EXCLUDED.probable_cause,
  explanation = EXCLUDED.explanation,
  updated_at = now();

INSERT INTO alarm_libraries (alarm_identifier, alarm_source, event_type, severity, enabled, probable_cause, explanation) VALUES
('11306', 'enb', 'communicationsAlarm', 1, true, 'S1-SCTP link failure', ''),
('11307', 'enb', 'communicationsAlarm', 1, true, 'X2-SCTP link failure', ''),
('11308', 'enb', 'equipmentAlarm', 2, true, 'GPS开路告警', ''),
('11309', 'enb', 'equipmentAlarm', 2, true, 'GPS短路告警', ''),
('11400', 'enb', 'equipmentAlarm', 1, true, '下行本振失锁告警', '下行本振不同步引起的告警'),
('11401', 'enb', 'equipmentAlarm', 4, true, '上行本振失锁告警', '上行本振不同步引起的告警'),
('11402', 'enb', 'equipmentAlarm', 1, true, '下行过功率告警', '下行功率超过最大值时引起的告警'),
('11403', 'enb', 'equipmentAlarm', 4, true, '下行欠功率告警', '上行功率超过最大值时引起的告警'),
('11404', 'enb', 'equipmentAlarm', 4, true, '上行差异告警', '接收错误'),
('11405', 'enb', 'equipmentAlarm', 1, true, '温度严重告警', '载体温度已超过临界温度阈值'),
('11406', 'enb', 'equipmentAlarm', 4, true, '温度一般告警', '载体温度已超过告警温度阈值'),
('11407', 'enb', 'processingErrorAlarm', 1, true, '非法射频配置告警', '所选的配置不支持引起的告警'),
('11408', 'enb', 'processingErrorAlarm', 1, true, '校准缺失告警', '校准数据不支持指定的配置引起的告警'),
('11409', 'enb', 'equipmentAlarm', 1, true, 'DPD Critical告警', 'DPD软件检测到错误引起的告警'),
('11410', 'enb', 'equipmentAlarm', 1, true, '频率同步丢失', '频率失步引起的告警'),
('11411', 'enb', 'equipmentAlarm', 1, true, '时间同步丢失', '时间同步丢失引起的告警'),
('11412', 'enb', 'equipmentAlarm', 1, true, '同步源丢失', '同步源丢失引起的告警，只有在获得源并随后丢失源时才会发出警报'),
('11413', 'enb', 'communicationsAlarm', 2, true, 'SCTP断链', 'RRC/SCTP连接失败告警'),
('11415', 'enb', 'processingErrorAlarm', 1, true, 'LTE参数配置错误', 'RRC/S1AP连接成功告警'),
('11416', 'enb', 'processingErrorAlarm', 1, true, '配置列表无可用PCI', 'OAM配置失败告警'),
('11419', 'enb', 'communicationsAlarm', 4, true, '丢包率过高', '回传网络拥塞或目的地不可达'),
('11420', 'enb', 'communicationsAlarm', 4, true, '时延过大', 'ping时延过大'),
('11421', 'enb', 'processingErrorAlarm', 2, true, 'CrM无法提供LTEU服务', '由配置错误，网络监听，或不正确或缺少802.11驱动程序或固件或硬件，导致降级服务所引起的告警'),
('11422', 'enb', 'processingErrorAlarm', 2, true, 'PCI冲突', 'PCI选择失败报警，eNB将继续用冲突PCI'),
('11423', 'enb', 'processingErrorAlarm', 2, true, 'UE审核上下文不匹配', 'UE上下文不匹配告警'),
('11424', 'enb', 'processingErrorAlarm', 2, true, 'UE审核Gbr使用率不匹配', 'UE核准GBR使用不匹配告警'),
('11425', 'enb', 'processingErrorAlarm', 2, true, '小区自操作失败', '执行小区相关操作失败告警'),
('11426', 'enb', 'processingErrorAlarm', 2, true, '基本配置丢失', '缺失基本配置参数告警'),
('11427', 'enb', 'processingErrorAlarm', 1, true, '配置错误', '记录实例的配置无效告警'),
('11428', 'enb', 'processingErrorAlarm', 4, true, '配置警告', '记录实例的配置无效告警'),
('11429', 'enb', 'equipmentAlarm', 2, true, 'DPD Serious告警', 'DPD软件检测到严重的错误引起的告警'),
('11430', 'enb', 'environmentalAlarm', 4, true, '周边强干扰', '该报警是由SON产生的，当同频邻居的信号功率达到一定的阈值，即检测到高干扰'),
('11431', 'enb', 'communicationsAlarm', 2, true, 'IP地址冲突', '设备ip地址冲突'),
('11432', 'enb', 'equipmentAlarm', 1, true, '小区不可用告警', '小区状态持续5分钟不可用'),
('11433', 'enb', 'equipmentAlarm', 1, true, '天线异常告警', '基站启动时天线电缆TX1-TX4异常'),
('11434', 'enb', 'equipmentAlarm', 3, true, 'SOC过温一般告警', 'CPU温度已经超过最小阈值(87°)'),
('11435', 'enb', 'equipmentAlarm', 2, true, 'SOC过温严重告警', 'CPU温度已经超过最大阈值(90°)'),
('11436', 'enb', 'processingErrorAlarm', 2, true, 'NBR PCI混淆', '服务小区的PCI与邻居的邻居的PCI相同'),
('11437', 'enb', 'equipmentAlarm', 1, true, '7834设备异常', 'Amc7834自检失败'),
('11438', 'enb', 'equipmentAlarm', 1, true, 'LM75自检失败', 'Lm75不存在或读取温度不在-40~100范围Pa电流超过致命告警阈值内'),
('11439', 'enb', 'equipmentAlarm', 1, true, 'AMC7823自检失败', '启动时自检失败(Amc7823不存在；AMC7823版本不正确；AMC7823读写错误)'),
('11440', 'enb', 'equipmentAlarm', 1, true, 'FPGA自检失败', 'Fpga版本无效；fpga读/写错误'),
('11441', 'enb', 'equipmentAlarm', 1, true, '电压检测异常', '电压检查失败，电压异常(5.5V、12V、2射频芯片初始化失败8V、48V电压未在法定范围内)'),
('11442', 'enb', 'equipmentAlarm', 2, true, '功放过温严重告警', 'Pa温度超过临界温度'),
('11443', 'enb', 'equipmentAlarm', 1, true, '功放过温致命告警', 'Pa温度超过超温阈值'),
('11444', 'enb', 'equipmentAlarm', 1, true, '功放过流致命告警', 'Pa电流超过致命告警阈值'),
('11448', 'enb', 'equipmentAlarm', 1, true, '射频芯片自检失败', '射频芯片初始化失败'),
('11449', 'enb', 'equipmentAlarm', 1, true, '驻波检测失败', 'RF天线不存在'),
('11450', 'enb', 'equipmentAlarm', 1, true, '栅压芯片自检失败', '门电路电压芯片温度不在-50~100范围内'),
('11452', 'enb', 'equipmentAlarm', 1, true, 'ntp同步失败', 'NTP同步在启动时失败')
ON CONFLICT (alarm_identifier) DO UPDATE SET
  alarm_source = EXCLUDED.alarm_source,
  event_type = EXCLUDED.event_type,
  severity = EXCLUDED.severity,
  probable_cause = EXCLUDED.probable_cause,
  explanation = EXCLUDED.explanation,
  updated_at = now();

INSERT INTO alarm_libraries (alarm_identifier, alarm_source, event_type, severity, enabled, probable_cause, explanation) VALUES
('11453', 'enb', 'environmentalAlarm', 1, true, '纬度或经度是非法的', '基站不在许可证的授权位置'),
('11454', 'enb', 'processingErrorAlarm', 2, true, 'PCI混淆', 'SON检测到相邻小区的PCI与邻居的一个邻居的PCI相同'),
('11456', 'enb', 'equipmentAlarm', 1, true, '射频关闭告警', '射频关闭'),
('11457', 'enb', 'equipmentAlarm', 1, true, '内存不足', '内存不足'),
('11458', 'enb', 'equipmentAlarm', 1, true, 'cpu利用率太高', 'cpu利用率太高'),
('11459', 'enb', 'communicationsAlarm', 2, true, '没有收到MME的响应或MME回复建立失败', '基站发出注册请求，但没有收到MME的响应或MME回复建立失败'),
('11460', 'enb', 'processingErrorAlarm', 2, true, '系统负载过高', '接入的UE过多超过了设置值'),
('11461', 'enb', 'equipmentAlarm', 1, true, '驻波值异常', '驻波值异常'),
('11462', 'enb', 'equipmentAlarm', 1, true, '驻波值过高', '驻波值过高'),
('11463', 'enb', 'processingErrorAlarm', 2, true, '许可证将过期', '如果许可证的剩余空闲天数少于30天，则每周一次；如果剩余可用天数少于7天，则每天一次'),
('11464', 'enb', 'processingErrorAlarm', 1, true, '许可证已过期', '如果许可剩余天数为0天，请报告一次'),
('11467', 'enb', 'equipmentAlarm', 1, true, 'MAC锁定告警', 'MAC锁定'),
('11468', 'enb', 'equipmentAlarm', 2, true, 'PMTU值异常', 'PMTU值不等于MTU值'),
('11469', 'enb', 'equipmentAlarm', 1, true, 'IMSI上报失败', '配置的时间内IMSI上报失败'),
('11471', 'enb', 'equipmentAlarm', 4, true, 'LMT密码过期', 'LMT登录密码超过90天未修改'),
('11472', 'enb', 'processingErrorAlarm', 2, true, 'LMT短期连续输错密码', 'LMT短期连续输错密码'),
('11500', 'enb', 'equipmentAlarm', 1, true, '射频开关关闭', '对应射频的开关被关闭'),
('11501', 'enb', 'equipmentAlarm', 1, true, '没有射频接入', '启站后大约15min没有射频接入或有RU接入后又全部离线'),
('11502', 'enb', 'equipmentAlarm', 1, true, 'CPRI链路断开', 'CPRI链路断开'),
('12', 'cpe', 'equipmentAlarm', 1, true, 'SAS异常告警', 'SAS异常告警'),
('12400', 'enb', 'equipmentAlarm', 1, true, '设备硬件自检失败', ''),
('12401', 'enb', 'equipmentAlarm', 2, true, '温度过高', ''),
('12402', 'enb', 'equipmentAlarm', 1, true, '驻波比过大', ''),
('12403', 'enb', 'equipmentAlarm', 3, true, 'APD工作异常', ''),
('12404', 'enb', 'equipmentAlarm', 2, true, '功放过流', ''),
('12405', 'enb', 'equipmentAlarm', 2, true, '无Tx功率告警', ''),
('12406', 'enb', 'equipmentAlarm', 2, true, '通道RSSI不平衡告警', ''),
('12407', 'enb', 'equipmentAlarm', 2, true, 'Tx增益超出范围', ''),
('12408', 'enb', 'equipmentAlarm', 2, true, '射频单元时钟问题', ''),
('12409', 'enb', 'equipmentAlarm', 1, true, '一般过温', '当检测到基站射频单元温度达到85度时，触发告警'),
('12410', 'enb', 'equipmentAlarm', 1, true, '严重过温', '当检测到基站射频单元温度达到90度时，触发告警'),
('12411', 'enb', 'equipmentAlarm', 1, true, '驻波', '当驻波值达到3时触发告警'),
('12412', 'enb', 'equipmentAlarm', 1, true, '配置参数无效', '配置参数无效时触发告警'),
('12413', 'enb', 'equipmentAlarm', 1, true, '射频参数无效', '射频参数无效时触发告警'),
('12414', 'enb', 'equipmentAlarm', 1, true, '电调告警', '电调天线链路断开'),
('12501', 'enb', 'equipmentAlarm', 1, true, '锁相环失锁', 'RU检测到中频或者射频时钟失锁'),
('12502', 'enb', 'equipmentAlarm', 1, true, '功率过高', 'RU检测到下行链路功率超过设计阈值。'),
('12503', 'enb', 'equipmentAlarm', 1, true, '射频检测错误', '射频自检失败'),
('12504', 'enb', 'equipmentAlarm', 3, true, 'X2 sctp 失败', 'X2建立时SCTP链路不通'),
('12505', 'enb', 'equipmentAlarm', 3, true, '频谱分析告警', '频谱分析打开'),
('12506', 'enb', 'equipmentAlarm', 4, true, '驻波', '当驻波值达到1.5时触发告警'),
('12507', 'enb', 'equipmentAlarm', 1, true, 'eNB 和 gNB 之间的EnDc X2AP 链路连接失败', 'x2链路异常告警'),
('12508', 'enb', 'equipmentAlarm', 1, true, 'SCTP 链路连接失败', 'x2链路stcp告警'),
('13', 'omc', 'communicationsAlarm', 1, true, 'SAS DP 证书即将过期告警', 'SAS证书即将过期告警'),
('14', 'omc', 'equipmentAlarm', 2, true, '磁盘占用率过高重要告警', '磁盘占用率超过告警阈值'),
('15', 'omc', 'equipmentAlarm', 1, true, '磁盘占用率过高紧急告警', '磁盘占用率超过告警阈值'),
('16', 'omc', 'equipmentAlarm', 2, true, '服务器负载过高告警', '系统负载超过阈值'),
('17', 'omc', 'equipmentAlarm', 2, true, '内存使用率过高重要告警', '内存使用率超过阈值'),
('18', 'omc', 'equipmentAlarm', 1, true, '内存使用率过高紧急告警', '内存使用率超过阈值'),
('23', 'omc', 'communicationsAlarm', 1, true, 'gNB网络断开', 'GNB与OMC网络中断')
ON CONFLICT (alarm_identifier) DO UPDATE SET
  alarm_source = EXCLUDED.alarm_source,
  event_type = EXCLUDED.event_type,
  severity = EXCLUDED.severity,
  probable_cause = EXCLUDED.probable_cause,
  explanation = EXCLUDED.explanation,
  updated_at = now();

INSERT INTO alarm_libraries (alarm_identifier, alarm_source, event_type, severity, enabled, probable_cause, explanation) VALUES
('24', 'cpe', 'equipmentAlarm', 1, true, 'SIM卡异常告警', 'SIM卡异常'),
('25', 'omc', 'equipmentAlarm', 1, true, '服务器告警', '服务器异常'),
('26', 'omc', 'equipmentAlarm', 1, true, '服务器CPU告警', '服务器CPU异常'),
('27', 'omc', 'equipmentAlarm', 1, true, '服务器memory告警', '服务器内存异常'),
('28', 'omc', 'equipmentAlarm', 1, true, '服务器网卡告警', '服务器网卡异常'),
('29', 'omc', 'equipmentAlarm', 1, true, '服务器电源告警', '服务器电源异常'),
('30', 'omc', 'equipmentAlarm', 1, true, '服务器风扇告警', '服务器风扇异常'),
('300', 'enb', 'qualityOfServiceAlarm', 2, true, 'KPI告警', ''),
('31', 'omc', 'equipmentAlarm', 1, true, '服务器硬盘告警', '服务器硬盘异常'),
('31002', 'wcg', 'equipmentAlarm', 4, true, 'CPU利用率超过阈值', ''),
('31003', 'wcg', 'equipmentAlarm', 4, true, '内存使用率超过阈值', ''),
('31004', 'wcg', 'equipmentAlarm', 4, true, '磁盘空间使用超过阈值', ''),
('31005', 'wcg', 'equipmentAlarm', 4, true, '历史日志超过阈值', ''),
('31006', 'wcg', 'equipmentAlarm', 1, true, 'wcg业务进程发生复位', ''),
('32', 'enb', 'equipmentAlarm', 1, true, 'SAS异常告警', 'SAS异常告警'),
('32002', 'wcg', 'equipmentAlarm', 1, true, '端口故障', ''),
('32004', 'wcg', 'communicationsAlarm', 1, true, '4G SCTP链路断开', ''),
('32501', 'wcg', 'communicationsAlarm', 1, true, '5G SCTP链路断开', ''),
('33', 'enb', 'equipmentAlarm', 1, true, 'SAS异常告警', 'SAS异常告警'),
('33001', 'wcg', 'equipmentAlarm', 4, true, '在线基站数量超阈值', ''),
('33002', 'wcg', 'equipmentAlarm', 4, true, '在线UE数量超过阈值', ''),
('33003', 'wcg', 'equipmentAlarm', 4, true, 'IPsec隧道数量超过阈值', ''),
('33501', 'wcg', 'equipmentAlarm', 4, true, '5G在线cell数量超过阈值', ''),
('33502', 'wcg', 'equipmentAlarm', 4, true, '5G在线UE数量超过阈值', ''),
('34', 'gnb', 'equipmentAlarm', 1, true, 'SAS异常告警', 'SAS异常告警'),
('35', 'omc', 'communicationsAlarm', 1, true, '主机安全检测告警', '主机可能遭到攻击，请检查各安全检测项'),
('35001', 'wcg', 'qualityOfServiceAlarm', 1, true, 'License有效期小于阈值', ''),
('35003', 'wcg', 'qualityOfServiceAlarm', 1, true, 'License已经超出有效期', ''),
('36', 'omc', 'communicationsAlarm', 1, true, 'site离线告警', 'site offline'),
('36001', 'wcg', 'equipmentAlarm', 4, true, '基站非法访问网络设备', '存在基站非法访问网络设备情况'),
('4', 'omc', 'communicationsAlarm', 1, true, 'GSM网络断开', ''),
('42000', 'ups', 'equipmentAlarm', 2, true, 'AC Power Off', ''),
('42001', 'ups', 'equipmentAlarm', 2, true, 'LTC故障', 'LTC故障'),
('42002', 'ups', 'equipmentAlarm', 2, true, '直流无输出', '直流无输出'),
('42003', 'ups', 'equipmentAlarm', 2, true, '电源过温告警', '电源过温告警'),
('42004', 'ups', 'equipmentAlarm', 2, true, '电源过流告警', '电源过流告警'),
('42005', 'ups', 'equipmentAlarm', 2, true, '低温保护', '低温保护'),
('42006', 'ups', 'equipmentAlarm', 2, true, '高温充电保护', '高温充电保护'),
('42007', 'ups', 'equipmentAlarm', 2, true, '高温放电保护', '高温放电保护'),
('42008', 'ups', 'equipmentAlarm', 2, true, '电芯故障', '电芯故障'),
('42009', 'ups', 'equipmentAlarm', 2, true, 'Battery over discharge alarm voltage', ''),
('42010', 'ups', 'equipmentAlarm', 2, true, 'Battery Communication Error', ''),
('42011', 'ups', 'equipmentAlarm', 2, true, 'Alarm When Door Opened', ''),
('42012', 'ups', 'equipmentAlarm', 2, true, 'Cabin was soggy', ''),
('42013', 'ups', 'equipmentAlarm', 2, true, 'Smoking detected in cabin', ''),
('42014', 'ups', 'equipmentAlarm', 2, true, 'SPD Out', ''),
('42015', 'ups', 'equipmentAlarm', 2, true, 'Fan out work', ''),
('42016', 'ups', 'equipmentAlarm', 2, true, 'Inverter overload', ''),
('42017', 'ups', 'equipmentAlarm', 2, true, 'High temperature', ''),
('42018', 'ups', 'equipmentAlarm', 2, true, 'Low temperature', '')
ON CONFLICT (alarm_identifier) DO UPDATE SET
  alarm_source = EXCLUDED.alarm_source,
  event_type = EXCLUDED.event_type,
  severity = EXCLUDED.severity,
  probable_cause = EXCLUDED.probable_cause,
  explanation = EXCLUDED.explanation,
  updated_at = now();

INSERT INTO alarm_libraries (alarm_identifier, alarm_source, event_type, severity, enabled, probable_cause, explanation) VALUES
('5', 'omc', 'communicationsAlarm', 1, true, 'unison异常告警', '网络异常'),
('50000', 'gnb', 'equipmentAlarm', 1, true, '设备硬件自检失败', '模块在启动过程中检测各个硬件状态是否正常'),
('50001', 'gnb', 'equipmentAlarm', 1, true, '光模块收发异常告警', '上电后已经完成硬件组网连接的设备检测到光模块收发有异常'),
('50002', 'gnb', 'equipmentAlarm', 2, true, 'GPS同步失败告警', '小区建立后检测到GPS（北斗） 同步失败'),
('50003', 'gnb', 'communicationsAlarm', 3, true, '时间同步失败告警', '启动时或运行过程中，如果预设的NTP服务器都不可用产生该告警；产生该告警后NTP同步成功清除该告警'),
('50004', 'gnb', 'equipmentAlarm', 1, true, '内存空间不足', '当发生基站内存空间耗尽的情况，产生此告警。'),
('50005', 'gnb', 'communicationsAlarm', 1, true, 'SCTP链路故障告警', '当基站检测到SCTP（Stream Control Transmission Protocol，流控制传输协议）链路无法承载业务时，产生此告警。'),
('50006', 'gnb', 'processingErrorAlarm', 2, true, 'License will expir', 'License到期前7-30天每周发一次，License到期前0-7天每天发一次'),
('50007', 'gnb', 'processingErrorAlarm', 1, true, 'License has expired', 'License由未过期到过期发一次'),
('50010', 'gnb', 'communicationsAlarm', 1, true, 'NG链路故障', '添加NG接口后，当amf返回ng setup failure时或者基站检测到SCTP链路无法承载业务，产生该告警。'),
('50011', 'gnb', 'communicationsAlarm', 1, true, 'XN链路故障', '添加XN接口后，当对端站返回xn setup failure或者基站检测到SCTP链路无法承载业务时，产生该告警。'),
('50012', 'gnb', 'communicationsAlarm', 1, true, 'F1链路故障', '添加F1接口后，当向对端du发送f1 setup failure或者基站检测到SCTP链路无法承载业务时，产生该告警。'),
('50013', 'gnb', 'equipmentAlarm', 1, true, 'BBU设备温度告警', '当系统检测到BBU温度低于于阈值时，产生此告警。'),
('50014', 'gnb', 'equipmentAlarm', 1, true, 'BBU设备温度告警', '当系统检测到BBU温度高于阈值时，产生此告警。'),
('50015', 'gnb', 'equipmentAlarm', 1, true, 'BBU设备温度告警', '当系统检测到BBU温度远远高于阈值时，产生此告警。'),
('50016', 'gnb', 'processingErrorAlarm', 1, true, '软件版本升级失败', '软件版本升级失败'),
('50017', 'gnb', 'processingErrorAlarm', 1, true, 'BBU FPGA升级异常', '升级BBU FPGA版本时出现异常，产生此告警。'),
('50018', 'gnb', 'processingErrorAlarm', 1, true, '软件运行异常', '当前运行软件运行异常导致设备重启时，产生此告警。'),
('50019', 'gnb', 'processingErrorAlarm', 1, true, '软件运行异常', '当前运行软件运行异常导致设备重启时，产生此告警。'),
('50020', 'gnb', 'processingErrorAlarm', 1, true, '软件运行异常', '当前运行软件运行异常导致设备重启时，产生此告警。'),
('50021', 'gnb', 'processingErrorAlarm', 1, true, '软件运行异常', '当前运行软件运行异常导致设备重启时，产生此告警。'),
('50022', 'gnb', 'processingErrorAlarm', 1, true, '软件运行异常', '当前运行软件运行异常导致设备重启时，产生此告警。'),
('50023', 'gnb', 'processingErrorAlarm', 1, true, '软件运行异常', '当前运行软件运行异常导致设备重启时，产生此告警。'),
('50024', 'gnb', 'equipmentAlarm', 2, true, 'HUB下线告警', 'HUB下线告警'),
('50025', 'gnb', 'equipmentAlarm', 2, true, 'RRU下线告警', 'RRU下线告警'),
('50026', 'gnb', 'equipmentAlarm', 1, true, 'gNodeB退服告警', '当gNodeB基站同一双工模式且同一工作频段下的所有小区都不可用（除节能或用户手动闭塞NR DU小区引起的小区不可用）时，产生此告警。当至少一个小区可用或处于节能状态或处于用户手动闭塞状态时，恢复此告警。'),
('50027', 'gnb', 'equipmentAlarm', 4, true, '驻波比异常告警', '驻波告警主要是天线口的匹配问题。正常产品出现这个告警一般是外接天线异常了或者空口没接天线发功导致。一般都是硬件检查了外接天线或者射频链路异常了'),
('50028', 'gnb', 'equipmentAlarm', 2, true, '驻波比异常告警', '驻波告警主要是天线口的匹配问题。正常产品出现这个告警一般是外接天线异常了或者空口没接天线发功导致。一般都是硬件检查了外接天线或者射频链路异常了'),
('50029', 'gnb', 'equipmentAlarm', 4, true, '驻波比异常告警', '驻波告警主要是天线口的匹配问题。正常产品出现这个告警一般是外接天线异常了或者空口没接天线发功导致。一般都是硬件检查了外接天线或者射频链路异常了'),
('50030', 'gnb', 'equipmentAlarm', 2, true, '驻波比异常告警', '驻波告警主要是天线口的匹配问题。正常产品出现这个告警一般是外接天线异常了或者空口没接天线发功导致。一般都是硬件检查了外接天线或者射频链路异常了'),
('50031', 'gnb', 'equipmentAlarm', 1, true, 'PA温度超过90告警', '当系统检测到PA温度过高时，触发该告警'),
('50033', 'gnb', 'equipmentAlarm', 2, true, 'license剩余时间在0-7天', '当license剩余时间在0-7天范围内，产生此告警'),
('50034', 'gnb', 'equipmentAlarm', 2, true, 'license剩余时间在7-30天', '当license剩余时间在7-30天范围内，产生此告警'),
('50039', 'gnb', 'equipmentAlarm', 2, true, '无效License文件', 'License文件校验失败或文件不存在'),
('50042', 'gnb', 'equipmentAlarm', 4, true, '登录密码过期', 'Lmt登录密码超过有效期限'),
('50043', 'gnb', 'equipmentAlarm', 1, true, '磁盘空间检测告警', '(/),(/log),(/cfg)目录中一个或多个剩余空间大小超过门限设置，门限设置于NV参数中'),
('50044', 'gnb', 'communicationsAlarm', 2, true, '天线开路或短路告警', '1.开路：基站内部gps芯片与蘑菇头之间的物理连接线被检测到处于断路状态 
 2.短路：基站内部gps芯片与蘑菇头之间的物理连接线被检测到处于短路状态'),
('50045', 'gnb', 'equipmentAlarm', 1, true, 'gNB 和eNB 之间的EnDc X2Ap 链路连接失败', 'x2链路异常告警'),
('50101', 'gnb', 'equipmentAlarm', 1, true, '小区不可用告警', '小区未完成建立或小区shutdown时产生告警，小区恢复时发清除'),
('50102', 'gnb', 'equipmentAlarm', 1, true, '小区闭塞告警', '当用户手动闭塞小区成功时，产生此告警。闭塞小区是为了进行业务测试或故障小区隔离，请在测试完毕或故障修复后将小区解闭塞。'),
('51000', 'gnb', 'equipmentAlarm', 3, true, '光模块接收功率一般过低', '光纤连接不稳或未接光纤'),
('51001', 'gnb', 'equipmentAlarm', 2, true, '光模块接收功率严重过低', '光纤连接不稳或未接光纤'),
('51002', 'gnb', 'equipmentAlarm', 3, true, '光模块接收功率一般过高', '光纤连接不稳，接收光功率高'),
('51003', 'gnb', 'equipmentAlarm', 2, true, '光模块接收功率严重过高', '光纤连接不稳，接收光功率过高'),
('51004', 'gnb', 'equipmentAlarm', 3, true, '光模块发送功率一般过低', '光纤连接不稳或未接光纤'),
('51005', 'gnb', 'equipmentAlarm', 2, true, '光模块发送功率严重过低', '光纤连接不稳或未接光纤'),
('51006', 'gnb', 'equipmentAlarm', 3, true, '光模块发送功率一般过高', '光纤连接不稳，发送光功率高'),
('51007', 'gnb', 'equipmentAlarm', 2, true, '光模块发送功率严重过高', '光纤连接不稳，发送光功率过高'),
('51008', 'gnb', 'equipmentAlarm', 3, true, '光模块一般欠压', '光纤连接不稳，光功率欠压'),
('51009', 'gnb', 'equipmentAlarm', 2, true, '光模块严重欠压', '光纤连接不稳，光功率严重欠压')
ON CONFLICT (alarm_identifier) DO UPDATE SET
  alarm_source = EXCLUDED.alarm_source,
  event_type = EXCLUDED.event_type,
  severity = EXCLUDED.severity,
  probable_cause = EXCLUDED.probable_cause,
  explanation = EXCLUDED.explanation,
  updated_at = now();

INSERT INTO alarm_libraries (alarm_identifier, alarm_source, event_type, severity, enabled, probable_cause, explanation) VALUES
('51010', 'gnb', 'equipmentAlarm', 1, true, 'aurora0接口不稳定,多次闪断', '当链路出现状态异常时，产生此告警。'),
('51011', 'gnb', 'equipmentAlarm', 1, true, 'aurora1接口不稳定,多次闪断', '当链路出现状态异常时，产生此告警。'),
('51012', 'gnb', 'equipmentAlarm', 1, true, 'aurora0采用64b/66b 编码，允许硬件问题或链路噪声可能导致的编码错误', '当链路出现状态不稳定时，产生此告警。'),
('51013', 'gnb', 'equipmentAlarm', 1, true, 'aurora1采用64b/66b 编码，允许硬件问题或链路噪声可能导致的编码错误', '当链路出现状态不稳定时，产生此告警。'),
('51014', 'gnb', 'equipmentAlarm', 1, true, '光模块异常告警', '光模块异常告警的原因可分为：
• Rx_Los
• Tx_Fault
• Crc_Error
• Remote_Fault'),
('51015', 'gnb', 'equipmentAlarm', 1, true, '光模块异常告警', '光模块异常告警的原因可分为：
• Rx_Los
• Tx_Fault
• Crc_Error
• Remote_Fault'),
('51016', 'gnb', 'equipmentAlarm', 1, true, '光模块不在位', '当系统检测到光模块不在位时，产生该告警。'),
('51018', 'gnb', 'equipmentAlarm', 1, true, 'HUB掉电告警', 'HUB掉电告警'),
('51501', 'gnb', 'equipmentAlarm', 1, true, 'HUB CPRI链路异常告警', '作为事件通知BBU，cpri no link，事件发生，cpri link，事件关闭'),
('51502', 'gnb', 'equipmentAlarm', 1, true, 'HUB温度异常告警', '当RHUB内部工作温度超过额定工作范围时，产生此告警。'),
('6', 'omc', 'communicationsAlarm', 1, true, '备机网络异常告警', '备机系统发生故障或者网络异常'),
('60001', 'enb', 'communicationsAlarm', 1, true, '网络断开或者abis配置有问题（remote ip、ipa unit-id等）', 'BTS无法连接BSC'),
('60002', 'enb', 'communicationsAlarm', 1, true, '网络断开', 'BSC无法连接MSC'),
('60003', 'enb', 'equipmentAlarm', 2, true, 'BTS不可用', '所有TRX均初始化失败，此BTS不可用'),
('60004', 'enb', 'communicationsAlarm', 1, true, '网络断开', 'BSC无法连接MSC'),
('60005', 'enb', 'communicationsAlarm', 1, true, '网络断开', 'BSC无法连接MSC'),
('7', 'omc', 'communicationsAlarm', 1, true, 'eNB网络断开', ''),
('70002', 'enb', 'equipmentAlarm', 1, true, 'PCI模3告警', ''),
('70004', 'enb', 'equipmentAlarm', 1, true, '干接点1断开', ''),
('70005', 'enb', 'equipmentAlarm', 1, true, '干接点2断开', ''),
('70006', 'enb', 'equipmentAlarm', 1, true, '干接点3断开', ''),
('70007', 'enb', 'equipmentAlarm', 1, true, '干接点4断开', ''),
('9', 'enb', 'communicationsAlarm', 1, true, 'CPE网络断开', '')
ON CONFLICT (alarm_identifier) DO UPDATE SET
  alarm_source = EXCLUDED.alarm_source,
  event_type = EXCLUDED.event_type,
  severity = EXCLUDED.severity,
  probable_cause = EXCLUDED.probable_cause,
  explanation = EXCLUDED.explanation,
  updated_at = now();

-- +goose Down

TRUNCATE alarm_library_i18n, alarm_libraries RESTART IDENTITY;
